### PR TITLE
Simple Moments class for Java

### LINKED ISSUE #5017: imgproc.Moments missing in OpenCV 3.0 for Android
Transferred from http://code.opencv.org/issues/4404
```
|| Karim Virani on 2015-06-13 15:44
|| Priority: High
|| Affected: branch 'master' (3.0-dev)
|| Category: android
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: Any / Android
```

imgproc.Moments missing in OpenCV 3.0 for Android
-----------
```
imgproc.Moments seems to have disappeared in openCVLibrary300 for java.

Looking in Improc.java it says this:

// Return type 'Moments' is not supported, skipping the function
Same for huMoments

These were supported as of 2.4.11

In the 3.0 android distribution, the whole Moments.java file seems to be missing from the imgproc folder and bindings seem removed from Imgproc.java

This breaks a lot of working code.
```

History
-------
##### Maksim Shabunin on 2015-06-15 12:25
```
-   Target version changed from 3.0 to 3.1
-   Assignee changed from Alexander Smorkalov to Maksim Shabunin
```

### PR DESCRIPTION
**Pull request by mshabunin**
Should fix #5017

### CODE REVIEW

**Comment by mshabunin** [comment]
Tested it with the following sample:
```.java
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.CvType;
import org.opencv.core.Scalar;
import org.opencv.imgproc.Imgproc;
import org.opencv.imgproc.Moments;

class SimpleSample {
  static{ System.loadLibrary(Core.NATIVE_LIBRARY_NAME); }
  public static void main(String[] args) {
    System.out.println("Welcome to OpenCV " + Core.VERSION);
    Mat m = new Mat(3,3, CvType.CV_8UC1, new Scalar(1));
    m.row(1).setTo(new Scalar(5));
    Moments res = Imgproc.moments(m);
    System.out.println("OpenCV Mat data:\n" + m.dump());
    System.out.println("Moments:\n" + res.toString());
  }
}
```
Result:
```
Welcome to OpenCV 3.0.0-dev
OpenCV Mat data:
[  1,   1,   1;
   5,   5,   5;
   1,   1,   1]
Moments:
Moments [ 
m00=21.0, 
m10=21.0, m01=21.0, 
m20=35.0, m11=21.0, m02=27.0, 
m30=63.0, m21=35.0, m12=27.0, m03=39.0, 
mu20=14.0, mu11=0.0, mu02=6.0, 
mu30=0.0, mu21=0.0, mu12=0.0, mu03=0.0, 
nu20=0.031746031746031744, nu11=0.0, nu02=0.013605442176870746, 
nu30=0.0, nu21=0.0, nu12=0.0, nu03=0.0, 
]
```
@apavlenko , could you please take a look?

**Comment by ilya-lavrenov** [comment]
> Tested it with the following sample

Can this snippet be added to tests?

**Comment by mshabunin** [comment]
@ilya-lavrenov , added:
```
    [junit] Running org.opencv.test.imgproc.MomentsTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec
```

**Comment by apavlenko** [comment]
:+1:

**Comment by IronReignRobotics** [comment]
I'm a little confused.  Wouldn't a full fix for the original OpenCV4Android bug report involve generating JNI wrappers for the full C++ code for moments?  It doesn't look like this partial java implementation would handle hu moments or contour moments.

If you look at the 2.4.11 distribution, it seems this was all automatically generated:
OpenCV-2.4.11-android-sdk.zip\OpenCV-android-sdk\sdk\java\src\org\opencv\imgproc

**Comment by apavlenko** [comment]
@IronReignRobotics, could you share the code that works in 2.4.11 Java API and doesn't work now? (preferably in form of Java test)

**Comment by mshabunin** [comment]
@IronReignRobotics , this PR adds support for the structure containing resulting moments, but the `moments` function wrapper is generated automatically.

**Pull request merged**
