### PR TITLE
VS2015/Windows 10 and Universal Windows App support, remove copyright Microsoft code

### PR DESCRIPTION
**Pull request by GregoryMorse**
Updated from last pull request except Microsoft code is now deleted from the project.

In the future a code generation will be added to the build process which can copy the files and modify them with regular expressions/diff method without including Microsoft source code.  License for these codes is uncertain but it is include folder and more recently crt/src/stl.

For now changes working, except do not build WinRT with MSMF option turned on until code generator patch is in.

### CODE REVIEW

**Comment by vpisarev** [comment]
@GregoryMorse, thanks for the quick update!
@alalek, could you please review it?

**Comment by alalek** [comment]
Please squash commits into one to remove unnecessary intermediate changes

**Comment by GregoryMorse** [comment]
Yes, squashed.  All the definition code that crept in is cleaned up, and the Microsoft source is deleted.  WinRT with MSMF is not supported until the library code modifying tool is finished.

**Comment by alalek** [comment]
Thanks! :+1:

**Pull request merged**
