### PR TITLE
fix test failures in perf_calib3d on Win32

### PR DESCRIPTION
**Pull request by vpisarev**
made the solvepnp test a bit more modest; test 5-point configuration instead of 4-point in some cases; reduce the noise in 4-point configurations in other cases; also:
   - disabled upnp and dls algorithms - they are not quite stable
   - fixed solvePnPRansac: in the end solvePnP is called with all the inliers. That should improve the accuracy.

### CODE REVIEW

**Comment by mkostin** [comment]
[This issue](https://github.com/MSOpenTech/opencv/issues/21) might be related, although this is a different module the situation is the same - x32 fails while x64 passes.

**Comment by mshabunin** [comment]
@mkostin, the issue you mentioned should be fixed now (see #3794).

**Comment by vpisarev** [comment]
@mkostin, it was a problem with poor stability of the new OpenCV pose estimation algorithms

**Comment by mkostin** [comment]
@mshabunin, @vpisarev, thanks, checked it out and had no repro.

**Comment by vpisarev** [comment]
:+1:

**Comment by PhilLab** [comment]
I understand that the implementations of upnp and dls are unstable but the way how they have been disabled is **highly** counter-intuitive. Just executing EPNP regardless of the given flag confuses all users. If somebody wants to evaluate the OpenCV version of uPnP, let him do that (and not silently executing epnp in the background). Imagine somebody wants to evaluate the available PnP solvers in OpenCV and finds out that it does not matter which one he chooses because the results are all the same.

So please either a) remove the upnp and dls flags completely or b) leave them in and document the unstable behavior with a warning in the online documentation.
Personally, I would strongly vote for b) since this leaves the user more possibilities

**Pull request merged**
