### PR TITLE
Adding UNIX support for run.py

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
This updates UNIX binaries to use relative RPATH to libraries and updates run.py to copy bin and lib folders to the same dir when performing --tests_move.

OSX support is not implemented because of technical difficulties. It looks like the most common for OSX is post build updating of the absolute paths on binaries.

### CODE REVIEW

**Comment by EvgenyAgafonchikov** [comment]
Something like this should work for OSX (Checked manual way from [there](https://blogs.oracle.com/dipol/entry/dynamic_libraries_rpath_and_mac)):
```
otool -l binary | grep -oE "[^ ]libopencv[^ ]*" | xargs -I % install_name_tool -change % @loader_path/../lib/<substitution of library name>
```

However it is difficult to get and substitute **```<substitution of library name>```** part in this command using OSX terminal utilities.

In case there are any ideas or suggestions on OSX, I can try to extend run.py move functionality for OSX too.

**Comment by vpisarev** [comment]
thanks for the PR!
I'm afraid though that we will not accept it.
I believe, it's one of the best cmake features is that it it puts absolute rpath into the binaries. You may have arbitrary number of opencv versions on your machine, arbitrary number of different build configurations and they will work completely independently from each other. You can be absolutely sure that you use the right version regardless of whether opencv is installed in a system path or not. And you do not have to use "make install".  And with LD_LIBRARY_PATH (DYLD_LIBRARY_PATH on OSX), PYTHONPATH and OPENCV_TEST_DATA_PATH you can always specify the proper paths in your scripts.
I think, the switch to relative paths is like opening pandora box. Let's not do that.

**Comment by mkostin** [comment]
Makes sense for this approach, thank you. 
@vpisarev do you think having a preloaded wrapper script for linux systems with ```*_PATH``` set to make tests movable would be useful?

**Comment by vpisarev** [comment]
well, we did not need such a feature even once during our 15 years with opencv and 6 years of using CMake. We just run the tests right from the build directory and, if needed, give it all the environment variables it needs to run properly. Absolute rpath's on Linux/OSX give us 100% insurance that the tests/samples/apps will use the proper version of opencv. As soon as you allow relative paths and plan to move binaries around, and do it not via "make install" (where CMake updates embedded rpath's), you raise a risk of conflicts.

If you need such a feature in your test systems, I think, you can create a dedicated script that updates rpaths just like CMake does it during "make install". I just can not recommend such a practice and build in  such feature in opencv.

**Pull request closed without merging**
