### PR TITLE
Add GPU models

### PR DESCRIPTION
**Pull request by StevenPuttemans**
This solves the undesired consequence of breaking the GPU interface when replacing the models by their new version counterpart in an earlier PR ... it also allows wrappers like JavaCV to use these models in their wrappers, since new versions do not work there.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@vpisarev Alexander Shiskov told me to ask you too also look into this topic: http://code.opencv.org/issues/4218. It seems that multiple cascade detect interfaces are broken. Working on fixes as we speak. This one should fix the GPU problems in 2.4.

**Comment by StevenPuttemans** [comment]
Btw, a complete wrapup of my findings was just posted at the issue page. Just to know why I did these changes. I do need someone to take a look at the OpenCL functions.

**Comment by Dikay900** [comment]
these models are the old models and can be loaded by the GPU Class of the CascadeClassifier in 2.4 Thanks

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by jet47** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
:D buildbot is slow these days :D

**Comment by StevenPuttemans** [comment]
@jet47 and @vpisarev it is more easier to contact you here. As you can see on the reported issues pages there is still a single problem in the 3.0 branch, being the detection with models that use the tilted haar features on CPU, using the old models with GPU does not give rise to the same problem. I have checked all differences between master and 2.4 and I am guessing that the introduction of the SMID calculations combined with the tilted option go wrong somewhere. However I do not succeed in finding the solution. Any ideas?

**Pull request merged**
