### PR TITLE
Added missing extra modules warning

### PR DESCRIPTION
**Pull request by mshabunin**
Extra modules from specified folder will be counted and in case when thier number is zero - warning will be shown. This should help in cases when users provide wrong path to extra modules: 
```
-DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib
# wrong! - should be path to 'modules' subfolder

-DOPENCV_EXTRA_MODULES_PATH=../opencv_contribb/modules
# wrong! - mistype
```
Discussable:
- showing message with `SEND_ERROR` mode does not allow further generation, probably `WARNING` mode could be used (but message will be less visible)
- checking module existence from `OPENCV_MODULE_opencv_${mod}_LOCATION` variable
- message text
- is it needed at all?

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
This could indeed be useful. I do not think that generation should continue once you made a mistake. That is what I kind of hate for the moment when generating using CMAKE. So :+1:

**Comment by alalek** [comment]
Looks good! Will you fix code indentation?

**Comment by mshabunin** [comment]
@alalek, done!

**Comment by alalek** [comment]
:+1:

**Pull request merged**
