### PR TITLE
Fix bug #5623: solving x^3 = 0 return "nan" roots

### PR DESCRIPTION
**Pull request by hoangviet1985**
The original solution did not handle correctly when delta = 0,
resulting as nan errors. I also wrote a test case to test solving
equation x^3 = 0 after fixing.

### CODE REVIEW

**Comment by hoangviet1985** [comment]
#5623

**Comment by hoangviet1985** [comment]
I noticed that there were 2 new tests (test_ocl, perf_ocl) which I did not see from previous successful build.
And the IOS build was also failed.

**Comment by alalek** [comment]
This build failure is not related to the patch. Please ignore it.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
