### PR TITLE
Added WinRT concurrency support.

### PR DESCRIPTION
**Pull request by mkostin**
Performance test reports can be [found here](https://github.com/MSOpenTech/opencv/wiki/Performance)

Increase performance / reduces execution time for cases when tasks can be effectively paralleled and load is enough for the parallel execution to result into substantial benefit for example for [imgproc](http://rawgit.com/wiki/MSOpenTech/opencv/test/performance/test-concurrent/5e47f433bcbde27e916dc174f380751863bc71cc/imgproc-summary.html) and [features](http://rawgit.com/wiki/MSOpenTech/opencv/test/performance/test-concurrent/5e47f433bcbde27e916dc174f380751863bc71cc/features-summary.html) modules. No impact or [limited](https://software.intel.com/en-us/articles/amdahls-law-gustafsons-trend-and-the-performance-limits-of-parallel-applications) negative impact for cases when tasks are not effectively paralleled or the gain from parallel execution is less that management expenses.

### CODE REVIEW

**Comment by mkostin** [comment]
Quite peculiar since this doesn't affect Mac "gcd" concurrency logic. I'll take a look, would appreciate your advice.

**Comment by mshabunin** [comment]
@mkostin, don't worry, this test fails sometimes on mac. I've restarted the build.

**Comment by mkostin** [comment]
@mshabunin nice one, thank you.

**Comment by vpisarev** [comment]
very nice contribution, thanks! :+1:

**Pull request merged**
