### PR TITLE
backports from master (part 2)

### PR DESCRIPTION
**Pull request by Dikay900**
#2678 - fd4df0f
#3926 - eaa9b78
#3627 - a21fb63
#3563 - 7a5aa06
#3357 - 044de41
#2939 - aad95c7
#2337 - 901d499

own fix - d9b7b30:
fixxed qt opengl example in 2.4 with 83c3363 see discussion http://stackoverflow.com/questions/4981583/problems-with-setting-up-opengl-and-visual-studio-2010

### CODE REVIEW

**Comment by Dikay900** [comment]
@StevenPuttemans maybe you can look over this aswell :)

**Comment by StevenPuttemans** [comment]
@Dikay900 I would love too, but I am drowning in work, hobbies, house building, writing OpenCV books, ... I am sure that you will make it work. I will have a look from time to time. If you have questions, do ask them and I will jump in!

**Comment by StevenPuttemans** [comment]
Checked them all, seem all legit fixes :)

**Comment by Dikay900** [comment]
If you got no time, i do not want to force anything. Thank you. :)

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
