### PR TITLE
Don't use ${CMAKE_INSTALL_PREFIX} as an install destination

### PR DESCRIPTION
**Pull request by SpecLad**
Absolute destinations are not necessary, and prevent CPack from working.

### CODE REVIEW

**Comment by asmorkalov** [comment]
@SpecLad What is the reason for the change?

**Comment by SpecLad** [comment]
> and prevent CPack from working

**Comment by StevenPuttemans** [comment]
@SpecLad this will render the very easy `sudo make install` under linux useless. Isn't there a way to check how we can keep it and also get CPack to work?

**Comment by SpecLad** [comment]
> this will render the very easy sudo make install under linux useless.

How so?

**Comment by StevenPuttemans** [comment]
Afaik the sudo make install dumps all the build binaries into the correct location right under /usr/local/bin and such? Or am I mixing stuff up?

**Comment by SpecLad** [comment]
Correct, but how does that support your claim?

This is from the documentation for the `install` command:

> DESTINATION arguments specify the directory on disk to which a file will be installed.  If a full path (with a leading slash or drive letter) is given it is used directly.  **If a relative path is given it is interpreted relative to the value of CMAKE_INSTALL_PREFIX.**  The prefix can be relocated at install time using DESTDIR mechanism explained in the CMAKE_INSTALL_PREFIX variable documentation.

Emphasis mine. In other words, `.` is equivalent to `${CMAKE_INSTALL_PREFIX}`, except for it not being absolute.

**Comment by StevenPuttemans** [comment]
Hmmm so if I understand it correctly, the only difference will now be that you will need to explicitly define where to install everyting in relation to the root folder?

For example, in the past I could do

`cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUBLAS=ON -D WITH_CUFFT=ON -D WITH_EIGEN=ON -D WITH_OPENGL=ON -D WITH_QT=ON -D WITH_TBB=ON -D BUILD_DOCS=ON -D BUILD_EXAMPLES=ON -D BUILD_TESTS=ON -D CUDA_ARCH_BIN="3.0" ../opencv_build/`

And then followed by

`sudo make -j 24
sudo make install`

and everyhting would be in the standard location. How will this change influence this then?

**Comment by SpecLad** [comment]
> Hmmm so if I understand it correctly, the only difference will now be that you will need to explicitly define where to install everyting in relation to the root folder?

Depends on who the "you" in that sentence is. If by that you mean, well, _you_, then no. If you mean the OpenCV developers, then we already need that. See every other `install` command.

> How will this change influence this then?

In no way.

**Comment by StevenPuttemans** [comment]
O then do ignore my comments :) I completely misunderstood the adaptation it seems. Thanks for the explanation!

**Comment by asmorkalov** [comment]
:+1:

**Pull request merged**
