### PR TITLE
improve cornerScore()

### PR DESCRIPTION
**Pull request by K-Shinotsuka**
I improve the simd function "cornerScore()".
Please check the changes.

### CODE REVIEW

**Comment by sushruta** [comment]
Please do squash the commits to fewer commits since most failed the checks anyways.

**Comment by K-Shinotsuka** [comment]
I squashed the commits.
Please check "a607755" or "Files changed".

**Comment by Dikay900** [comment]
doesn't seem squashed to me. Seems like you didnt push.

**Comment by K-Shinotsuka** [comment]
>doesn't seem squashed to me.
>How did you squash?
Sorry.
It was not able to successfully.

I added only the ssse3 codes.
I didn't change the existing code.
Do I have to rebase?

**Comment by sushruta** [comment]
how did you try to squash? If you want some help, I can gladly walk you through squashing.

**Comment by K-Shinotsuka** [comment]
Dear Phillip.

Sorry. I closed the pull request #6465.
Instead of it, I open the pull request #6509.
The contents are the same.

 From k-shinotsuka.

**Comment by K-Shinotsuka** [comment]
Dear sashidhar guntury.

Sorry. I closed the pull request #6465.
Instead of it, I open the pull request #6509.
The contents are the same.

 From k-shinotsuka.

**Pull request closed without merging**
