### PR TITLE
Add arm ABI hard on android

### PR DESCRIPTION
**Pull request by bhack**
This PR it is open for collecting hints to let create and ABI hard build for Android.
Initial stub to let hard ABI build fail.
See https://github.com/taka-no-me/android-cmake/issues/30

### CODE REVIEW

**Comment by vpisarev** [comment]
@alalek, could you please review it? As I understand, in order to build OpenCV with Caffe on Android, there should be possibility to disable softfp completely, @bhack, pls, correct me if needed

**Comment by bhack** [comment]
@vpisarev Yes Caffe has mainly tree CPU option for matrix library openblas/mkl/atlas. Openblas on armv7 has assembly code kernels that use hard ABI. 
Actually as workaround is used Eigen for the android effort but i don't think that maintainers want to add another dependencies. 
As reference https://github.com/BVLC/caffe/pull/2619

**Comment by alalek** [comment]
Most part of Android libraries uses `soft/softfp` (include system libraries, like libm), so heavy check is required (include Dalvik JNI bindings).

What is the problem to specify/override calling convention for "problem" functions only (BLAS/etc) and leave "default" calling convention as `softfp`? Will it work?
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0491i/CJAJBCCD.html:
```
__attribute__((pcs("aapcs-vfp")))
```

**Comment by bhack** [comment]
I'm trying to investigate vfpv3 softfp armv7a build of openblas.

**Comment by vpisarev** [comment]
@bhack, we discussed the patch with @alalek today. We can integrate it if cmake_android_arm.sh (which you renamed to cmake_android_arm_softfp.sh in this patch) will keep its name and will stay untouched, otherwise it breaks some our scripts.

**Comment by bhack** [comment]
@vpisarev Yes i can revert the name. But hard one still not build

```
 tif_config.h:121:22: error: unknown type name 'size_t'
```

**Comment by bhack** [comment]
An effort on Openblas side seems started. See https://github.com/xianyi/OpenBLAS/issues/363#issuecomment-117740627.
If we will have an openblas softfp ABI version we can close this.

**Comment by bhack** [comment]
Is there some activity at https://github.com/Itseez/opencv/pull/5098?

**Comment by bhack** [comment]
Closing as addressed in https://github.com/Itseez/opencv/pull/5098

**Pull request closed without merging**
