### PR TITLE
fix for bug 4380 (map_unmap_counting)

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
add contition to skip unmap for internally allocated memory

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@alalek @SergeySivolgin this change fixes fail in map_unmap_counting test

**Comment by alalek** [comment]
@vladimir-dudnik Please cleanup commits and remove useless "merges". Or recreate PR with non-master source branch.

**Comment by alalek** [comment]
:+1:

**Comment by apavlenko** [comment]
Guys, can you share the details what was the reason of this change?
Looks like it is the cause of spurious fails of the 'Core_UMat.getUMat' test...

**Comment by vladimir-dudnik** [comment]
When destroying UMat, obtained from Mat created on user memory, clEnqueueMapBuffer will fail, so condition was added to skip clEnqueueMapBuffer/clEnqueueUnmapBuffer in this case. As far as I understood, USER_ALLOCATED flag is used when one get UMat from Map created on user memory.

**Comment by apavlenko** [comment]
guys, please look at #5242 and share your thoughts...

**Pull request merged**
