### PR TITLE
fix for hal_intrin test on 64bit ARM

### LINKED ISSUE #6521: hal_intrin.float32x4 fails on 64bit ARM
### Please state the information for your system
- OpenCV version: 3.1 / master
- Host OS: Linux (Ubuntu 16.04 64bit)
- Architecture: aarch64 ARM 64bit (ODROID-C2)

### In which part of the OpenCV library you got the issue?
- core
- test of hal_intrin.float32x4

### Expected behaviour
- 11.054862976074219

### Actual behaviour
- 11.054863929748535

### Additional description
- This doesn't happen on ARM 32 bit or other x86, x86_64 architecture
- This doesn't happen on raspberry Pi 3 + Rasbian 32bit

### Code example to reproduce the issue / Steps to reproduce the issue

The error message is as following
```
/home/odroid/opencv-fork/modules/core/test/test_intrin.cpp:578: Failure
Value of: resF[i]
  Actual: 11.054863929748535
Expected: std::sqrt(data1[i]*data1[i] + data2[i]*data2[i])
Which is: 11.054862976074219
```
The main part of the test is comparing the result of std::sqrt against the v_sqrt based on vrsqrteq_f32.
It's very small difference, but fails on test.
For this part, I propose to add one more iteration in v_sqrt

```
@@ -427,6 +427,7 @@ inline v_float32x4 v_sqrt(const v_float32x4& x)
     float32x4_t e = vrsqrteq_f32(x1);
     e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
     e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
+    e = vmulq_f32(vrsqrtsq_f32(vmulq_f32(x1, e), e), e);
     return v_float32x4(vmulq_f32(x.val, e));
 }
```

### PR DESCRIPTION
**Pull request by tomoaki0705**
resolves #6521

### What does this PR change?
hal_intrin test fails on 64bit ARM

### CODE REVIEW

**Comment by tomoaki0705** [comment]
I don't get this.
I only modified intrin_neon.hpp and the failure comes from x64 build.

Can anyone help me on this ?

**Comment by alalek** [comment]
Don't worry, It is sporadic test failure. I will restart this build.

**Comment by tomoaki0705** [comment]
Thank you !

**Comment by alalek** [comment]
It is a template-based implementation, both floats and doubles are checked by the same code.

I suggest to do these steps:
1) wrap contents of this file into "namespace cvtest { namespace hal {"
2) add two overloads into namespace:
```
template <typename T> static inline void EXPECT_COMPARE_EQ_(const T a, const T b);
template <> inline void EXPECT_COMPARE_EQ_<float>(const float a, const float b)
{
    EXPECT_FLOAT_EQ(a, b);
}
template <> inline void EXPECT_COMPARE_EQ_<double>(const double a, const double b)
{
    EXPECT_DOUBLE_EQ(a, b);
}
```
2) add new comparator into the beginning of TheTest
```
    template <typename T1, typename T2>
    static inline void EXPECT_COMPARE_EQ(const T1 a, const T2 b)
    {
        EXPECT_COMPARE_EQ_<LaneType>((LaneType)a, (LaneType)b);
    }
```
3) Replace `EXPECT_DOUBLE_EQ` with `EXPECT_COMPARE_EQ`

P.S. There are some usages of `EXPECT_FLOAT_EQ` (for example in `test_sqrt_abs`). This looks strange to me.

**Comment by tomoaki0705** [comment]
I really appreciate your suggestion, and I'll follow that.

**Comment by alalek** [comment]
Thanks! Looks good to me.

**Comment by mshabunin** [comment]
Please, squash all commits into one before merge.

**Comment by mshabunin** [comment]
:+1:

**Comment by kgnk** [comment]
These should just be function overloads, not template functions. Also I think it is bad style to use all caps for a function. All caps is usually used to indicate a macro.
```
void expect_compare_eq( float a, float b )
{
    EXPECT_FLOAT_EQ( a, b );
}

void expect_compare_eq( double a, double b )
{
    EXPECT_DOUBLE_EQ( a, b );
}
```

**Pull request merged**
