### PR TITLE
Adding AVX2 code to HAL and Core Arithm

### PR DESCRIPTION
**Pull request by Tetragramm**
Add AVX2 code for Multiply, Divide, Reciprocal, Compare, and InRange
Also cleans up the SSE2 and NEON code for those function to match the standard.

Adds AVX2 code to the simpler math in HAL. 

```
check_regression=*Multiply*:*Divide*:*reciprocal*:*ompare*:*InRange*:*Norm*:*Sqrt*:*Magnitude*:
```

### CODE REVIEW

**Comment by Dikay900** [comment]
I would like to reference #3942 where putting AVX2 code into opencv was discussed half a year ago.
While i really like this step adding AVX2 code i think there are still the same problems mentioned in the discussion above.

Furthermore i just wanted to add that most of modern compilers will automatically evolve sse code to the appropriate and fastest code pretty much everywhere.
So using modern compilers like VS 2013++ or gcc 4.9++ will generate pretty much the same code with optimizations and avx2 enabled.

**Comment by Tetragramm** [comment]
Hmm.  I had not seen that discussion before.
I wonder if making the universal intrinsics 256 bits would make things easier.  Most of the 128 bit functions would work fine if you just did two of the 128 bit functions in a row. Then you just create a new AVX and AVX2 module.

That, of course, is a somewhat larger project, and doesn't solve the lack of build-farm computers with AVX2.

I do somewhat disagree with the idea that the compiler will match the performance. Some of the functions in this commit are more than 20% faster than without (VS 2015).  It is closer than I expected though.

**Comment by Dikay900** [comment]
Yes using own AVX2 code will be a bit faster in most cases but the main improvement (50% to 80% in general) will already be done by the compiler thats my experience. Maybe thats why you only see the 20% difference.
I did some AVX2 tests on warp functions while i needed a large amount of rotating and could only add around 5% to 8% to the speed with own code which was negated in my scenario by the complexity of the user program in the end.

**Comment by alalek** [comment]
There are some regressions on builds with disabled AVX/AVX2 optimizations (they are disabled by default) in 4-9 times on Haswell-like CPU:

Test name | base | patch | diff
--------- | ---- | ----- | ----
compare::Size_MatType_CmpType::(640x480, 8UC1, CMP_EQ) | 0.036 ms | 0.322 ms | 0.11
compare::Size_MatType_CmpType::(640x480, 8UC1, CMP_NE) | 0.036 ms | 0.322 ms | 0.11
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_EQ) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_GE) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_GT) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_LE) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_LT) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 16SC1, CMP_NE) | 0.056 ms | 0.323 ms | 0.17
compare::Size_MatType_CmpType::(640x480, 8UC4, CMP_EQ) | 0.149 ms | 1.292 ms | 0.12
compare::Size_MatType_CmpType::(640x480, 8UC4, CMP_NE) | 0.152 ms | 1.293 ms | 0.12
compare::Size_MatType_CmpType::(1920x1080, 8UC1, CMP_EQ) | 0.356 ms | 2.210 ms | 0.16
compare::Size_MatType_CmpType::(1920x1080, 8UC1, CMP_NE) | 0.350 ms | 2.205 ms | 0.16
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_EQ) | 0.637 ms | 2.311 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_GE) | 0.641 ms | 2.281 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_GT) | 0.639 ms | 2.273 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_LE) | 0.642 ms | 2.272 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_LT) | 0.638 ms | 2.288 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 16SC1, CMP_NE) | 0.641 ms | 2.287 ms | 0.28
compare::Size_MatType_CmpType::(1920x1080, 8UC4, CMP_EQ) | 1.818 ms | 8.930 ms | 0.20
compare::Size_MatType_CmpType::(1920x1080, 8UC4, CMP_NE) | 1.815 ms | 8.938 ms | 0.20

**Comment by Tetragramm** [comment]
Hmm.  I see what I did wrong with the 16S code, but the 8U code should be the same.  I just moved it from the cmp_8u to the CmpSMID<uchar> that's the standard.  I'll make sure I didn't fat finger something later today.

**Comment by Tetragramm** [comment]
All right, that should take care of it.  The general method only called the vectorized operations for LT, GT, LE, and GE.  So there should also be an improvement for 32S, which was never getting the EQ or NEQ vectorized code called.

**Comment by vpisarev** [comment]
@Tetragramm, thank you for the contribution. Since a subset of Intel IPP (IPPICV) can be used for free with OpenCV, it comes with AVX optimization, and it accelerates arithmetic functions, and because in OpenCV 3.x we will be extending OpenCV HAL with support for external acceleration functions (where those AVX optimizations can go), I think, we can close this PR.

**Pull request closed without merging**
