### PR TITLE
add a cascade classifier model visualisation tool

### PR DESCRIPTION
**Pull request by StevenPuttemans**
### What does this PR change?
It adds a tool that enables users to visualise cascade classifier models trained by the `opencv_traincascade` interface. It works for both LBP and HAAR features.

Will be backported once it gets merged into master. 

Once this is merged and the backport has happened, documentation will be generated for both the annotation tool as for this visualisation tool, which was missing and promised to add.

Example of the HAAR/LBP face model ran on a given window of Angelina Jolie, which had the same preprocessing as cascade classifier files -->24x24 pixel image, grayscale conversion and histogram equalisation:

_A video is made with for each stage each feature visualised:_

_Each stage is stored as an image for future validation of the features_

This work was created while writing [OpenCV 3 Blueprints](https://www.packtpub.com/application-development/opencv-3-blueprints), but I got promised by Packt Publishing that integrating this into the official OpenCV repo would not raise any issues.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@vpisarev As far as I am aware the last commit should fix all remaining issues. Feel free to walk through it already with suggestions where needed :)

**Comment by StevenPuttemans** [comment]
@vpisarev or @alalek any idea if I need to add something more? Once merged I can backport it to 2.4 and start working on documentation for both this and the annotation tool.

**Comment by StevenPuttemans** [comment]
@mshabunin you might wanna take a look at this related PR to the ones of yesterday? If this seems legit, I can start adding the backport also

**Comment by StevenPuttemans** [comment]
@vpisarev or @alalek might be a chance that this can get merged in? trying to clean everything up here locally :)

**Comment by alalek** [comment]
> This branch has conflicts that must be resolved

Could you please rebase patch? Something like:
```
git pull --rebase
or
git fetch upstream
git rebase -i upstream/master
```

**Comment by StevenPuttemans** [comment]
Ow sorry :D It seems that if you simply look at the pull request buildbot, simply showing all green windows is not enough! Will rebase the patch!

**Comment by StevenPuttemans** [comment]
@alalek Should be rebased correctly now! Guess the other PRs needs the same update?

**Comment by alalek** [comment]
Thanks! :+1:

> Guess the other PRs needs the same update?

With merge conflicts only.

**Comment by StevenPuttemans** [comment]
Yep just noticed they did not have the merge conflicts :+1:

**Pull request merged**
