### PR TITLE
add SSSE3 code to cornerScore()

### PR DESCRIPTION
**Pull request by K-Shinotsuka**
I improve the function "cornerScore()".
I eliminate the wasted "_mm_loadu_si128()" instruction for using ssse3 instruction.

### CODE REVIEW

**Comment by vpisarev** [comment]
@K-Shinotsuka, thanks for the contribution! do you have some numbers that's the speedup?

**Comment by K-Shinotsuka** [comment]
@vpisarev 
>thanks for the contribution! do you have some numbers that's the speedup?

Yes.
For example, ./opencv/modules/imgproc/src/canny.cpp.
1. It is possible to replace existing code with "_mm_abs_epi16()" in L370-L386 and L761-L777.
2. It is possible to replace existing code with "_mm_madd_epi16()" in L404-L420 and L795-L811.

**Comment by vpisarev** [comment]
ok, I see, but did you measure the improvements?

**Comment by K-Shinotsuka** [comment]
@vpisarev

>@K-Shinotsuka, thanks for the contribution! do you have some numbers that's the speedup brings?

I'm sorry.
I did not understand your sentense.
I understand that you want to know how many cycles the function "cornerScore()" is improved.
I'm sorry but I didn't measure the improvements.
I have linux machine only.
Are you sure that I measure this code at linux machine?

**Comment by K-Shinotsuka** [comment]
@vpisarev

I measured the function "cornerScore()".
Please observe the following.

Function,                           Average Clocks,  Faster Rate (compared with sse2)
cornerScore<8>   sse2,      62.00,                -	
cornerScore<8>   ssse3,	   59.75,                3.76%
cornerScore<12> sse2,    121.00,                -
cornerScore<12> ssse3,  117.75,                2.76%
cornerScore<16> sse2,    137.00,                -
cornerScore<16> ssse3,  133.50,                2.62%

Measurement Conditions
OS                                : Ubuntu 16.04
Compiler                       : g++ (Ubuntu 5.3.1-13ubuntu3) 5.3.1 20160330
CPU                              : Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz
Compiler Option           : -msse2 -mssse3 -O3
Measurement Function: rdtsc()
Number of Loop           : 10000

Note:
Average Clocks is derived "(sum of clocks of function call) / (Number of Loop)".
I measure the clocks at linux machine only.

**Comment by K-Shinotsuka** [comment]
@vpisarev

Sorry, there are some mistakes in my test code for measurement.
My ssse3 code is fast compared to existing sse2 code because cache worked.
So I correct my test code and measure my code and existing sse2 code again.
The speed of my ssse3 code and existing sse2 code are same.
So I will close this pull request.
Next time later, I will be careful to write test code for measurement.
I apologize for the inconvenience.

**Pull request closed without merging**
