### PR TITLE
cuda box filter for CV_32FC1

### PR DESCRIPTION
**Pull request by filipsladek**
Add option CV_32FC1 for cuda box filter.

Because of type incompatibility with previous code, I had to solve how to choose which npp function to use. I avoided class templatization with current option as default template parameter and rather chose to runtime switch based on srcType.

cuda::copyMakeBorder, which is used inside, is implemented for CV_32FC1.

### CODE REVIEW

**Comment by jet47** [comment]
Could you please extend the accuracy test with new type: https://github.com/Itseez/opencv/blob/master/modules/cudafilters/test/test_filters.cpp#L98

**Comment by jet47** [comment]
:+1:

**Comment by filipsladek** [comment]
Could you explain me, please, why I got test failed:
 OCL_MagnitudeFixture_Magnitude.Magnitude/5, where GetParam() = (1920x1080, 32FC4)

What does this have in common with my change?

**Comment by jet47** [comment]
It is an OpenCL test and it is not related with your change.

**Pull request merged**
