### PR TITLE
MSDDetector Impementation

### PR DESCRIPTION
**Pull request by m4nh**
Implementation of a Novel Feature2D Detector. See here for more infos:

https://github.com/fedassa/msdDetector

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
:+1:  nice one!

**Comment by b4rc0ll0** [comment]
Thanks for tips! :+1:

**Comment by StevenPuttemans** [comment]
@m4nh Could you close this PR down?

**Comment by StevenPuttemans** [comment]
Thank you!

**Pull request closed without merging**
