### PR TITLE
Bug #4316 fix: undefined references when BUILD_opencv_world:BOOL=ON

### PR DESCRIPTION
**Pull request by lupustr3**
May be more suitable way of fixing it.

### CODE REVIEW

**Comment by alalek** [comment]
Hi Pavel,
What build config is broken? (we need to reproduce this problem)
We have nightly `world` builds on Windows with shared (`-DBUILD_SHARED_LIBS=ON`) libraries, but these builds don't detect similar issue.

**Comment by lupustr3** [comment]
I build default config only with BUILD_opencv_world enabled.
Problem in tests build not world itself.

Same as http://code.opencv.org/issues/4316
Several undefined references in some tests.

Tests use hal calls which are used in some headers (matx.hpp at least), but in world configuration hal is a part of dll, not static lib as in general build and hal API is not exported. You need either export hal API or use static linkage everywhere.

**Comment by lupustr3** [comment]
https://github.com/Itseez/opencv/pull/4048

**Comment by lupustr3** [comment]
I see that tests build with world module is broken again after hal tests introduction.

**Comment by alalek** [comment]
Hi Pavel!
Will this work for you: https://github.com/Itseez/opencv/pull/4095 ?

**Comment by lupustr3** [comment]
It seems to be working. Thanks!

**Comment by mshabunin** [comment]
PR #4095 with the fix has been merged.

**Pull request closed without merging**
