### PR TITLE
Histogram substraction bug fix for median filter with NEON instructions

### PR DESCRIPTION
**Pull request by FlorentHoareau**

### CODE REVIEW

**Comment by vpisarev** [comment]
looks like the patch includes some API change, which is normally not allowed, but might be fine in this case. @jet47, could you please review it?

**Comment by FlorentHoareau** [comment]
Oh, I've recently pushed another commit on my github repo which actually changes one API, which was not originally supposed to be there in the pull request.

I forgot that it would be added to the pull request. What should I do ?

**Comment by jet47** [comment]
Hello @FlorentHoareau 

To split this PR onto two separate PRs:

    # checkout to your local master
    $ git checkout master
    # reset to the first commit
    $ git reset --hard 9e3b2d0
    # push your master branch to update this PR
    $ git push origin master --force
    # checkout to parent commit
    $ git checkout 466a98f
    # create new branch
    $ git checkout -b cuda-hough-segments-fix
    # cherry pick the second commit
    $ git cherry-pick abb4e77
    # push the new branch to your repo
    $ git push origin cuda-hough-segments-fix

Now create second pull request from `cuda-hough-segments-fix` branch.

**Comment by mshabunin** [comment]
Moved to #5756

**Pull request closed without merging**
