### PR TITLE
add meshgrid functionality

### PR DESCRIPTION
**Pull request by theodr**
Add a function that corresponds to the respective [meshgrid()](http://se.mathworks.com/help/matlab/ref/meshgrid.html) one from matlab.

I have written some testing functionality, which can be seen below. However, I did not know how to and if I should add it somewhere.

```
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/ts.hpp>


using namespace std;
using namespace cv;

static bool areEqual(const Mat& m1, const Mat& m2)
{
    return m1.size() == m2.size()
            && m1.type() == m2.type()
            && countNonZero(m1 != m2) == 0;
}

static void meshgrid(InputArray _xgv, InputArray _ygv, OutputArray _X, OutputArray _Y)
{
    Mat xgv = _xgv.getMat();
    Mat ygv = _ygv.getMat();

    cv::repeat(xgv.reshape(1,1), ygv.total(), 1, _X);
    cv::repeat(ygv.reshape(1,1).t(), 1, xgv.total(), _Y);
}


static void meshgrid(const cv::Range &xgv, const cv::Range &ygv, OutputArray _X, OutputArray _Y)
{
    std::vector<double> t_x, t_y;
    for (int i = xgv.start; i <= xgv.end; i++) t_x.push_back(i);
    for (int i = ygv.start; i <= ygv.end; i++) t_y.push_back(i);

    Mat __X, __Y;
    meshgrid(cv::Mat(t_x), cv::Mat(t_y), __X, __Y);

    Mat(__X).copyTo(_X);
    Mat(__Y).copyTo(_Y);
}

int main(int argc, char** argv)
{
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}

TEST(Core_Meshgrid, ValueEqualityCheckMat)
{
    Mat_<float> x = (Mat_<float>(1, 7) << -3, -2, -1, 0, 1, 2, 3);
    Mat_<float> y = (Mat_<float>(1, 6) << -3, -2, -1, 0, 1, 2);

    Mat_<float> expectedX = (Mat_<float>(6, 7) << -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3);

    Mat_<float> expectedY = (Mat_<float>(6, 7) << -3, -3, -3, -3, -3, -3, -3,
                                                  -2, -2, -2, -2, -2, -2, -2,
                                                  -1, -1, -1, -1, -1, -1, -1,
                                                   0,  0,  0,  0,  0,  0,  0,
                                                   1,  1,  1,  1,  1,  1,  1,
                                                   2,  2,  2,  2,  2,  2,  2);
    Mat X,Y;
    meshgrid(x, y, X, Y);

    ASSERT_EQ(true, areEqual(expectedX, X)) << "Test Passed";
    ASSERT_EQ(true, areEqual(expectedY, Y)) << "Test Passed";
    ASSERT_EQ(true, X.size() == Y.size()) << "Test Passed";
}

TEST(Core_Meshgrid, ValueEqualityCheckRange)
{
    Mat_<double> expectedX = (Mat_<double>(5, 3) << 1, 2, 3,
                                                    1, 2, 3,
                                                    1, 2, 3,
                                                    1, 2, 3,
                                                    1, 2, 3);

    Mat_<double> expectedY = (Mat_<double>(5, 3) << 10, 10, 10,
                                                    11, 11, 11,
                                                    12, 12, 12,
                                                    13, 13, 13,
                                                    14, 14, 14);
    Mat X,Y;
    meshgrid(cv::Range(1,3), cv::Range(10, 14), X, Y);

    ASSERT_EQ(true, areEqual(expectedX, X)) << "Test Passed";
    ASSERT_EQ(true, areEqual(expectedY, Y)) << "Test Passed";
    ASSERT_EQ(true, X.size() == Y.size()) << "Test Passed";
}

TEST(Core_Meshgrid, ValueEqualityCheckVec)
{
    vector<float> x = {-3, -2, -1, 0, 1, 2, 3};
    vector<float> y = {-3, -2, -1, 0, 1, 2};

    Mat_<float> expectedX = (Mat_<float>(6, 7) << -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3,
                                                  -3, -2, -1, 0, 1, 2, 3);

    Mat_<float> expectedY = (Mat_<float>(6, 7) << -3, -3, -3, -3, -3, -3, -3,
                                                  -2, -2, -2, -2, -2, -2, -2,
                                                  -1, -1, -1, -1, -1, -1, -1,
                                                   0,  0,  0,  0,  0,  0,  0,
                                                   1,  1,  1,  1,  1,  1,  1,
                                                   2,  2,  2,  2,  2,  2,  2);
    Mat X,Y;
    meshgrid(x, y, X, Y);

    ASSERT_EQ(true, areEqual(expectedX, X)) << "Test Passed";
    ASSERT_EQ(true, areEqual(expectedY, Y)) << "Test Passed";
    ASSERT_EQ(true, X.size() == Y.size()) << "Test Passed";
}
```
I hope that I have done everything correctly, since it is my first attempt to contribute some actual code.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Nice try @theodr but at first I think this should go directly into the contrib repository, since this is completely new functionality that was not available beforehand. 

As to the tests, all I know is that they have to be in the same format as the tests for all the other modules which you can find under the test folder.

**Comment by theodr** [comment]
@StevenPuttemans thanks. I do not know since there are only two functions that were created if it is worth to be created as a separate module into the opencv_contrib repository. Actually I followed the advice of @mshabunin from a previous question of mine.

> @theodr, there is also many information in the Coding Style Guide.
> I can say that it is better to put function definition to include/**/*.hpp file and implementation to 
> corresponding src/*.cpp file.
> Test are good to have to make sure that function is working as expected. Tests definitions can be > quite laconic:
> ```
> TEST(Core_<test-group>, <test-name>)
> {
> // 1. do something
> // 2. check result with ASSERT_EQ, EXPECT_EQ, ...
> // or
> // 2. check result manually and call one of the:
> //  - ts->set_failed_test_info(cvtest::TS::OK)
> //  - ts->set_failed_test_info(cvtest::TS::FAIL_<something>)
> }
> ```
> Or test can be implemented inside a class:
> ```
> class Core_MyTest : public cvtest::BaseTest
> {
>     void run( int) { /* implement it */ }
> }
> TEST(Core_<test-group>, <test-name>) { Core_MyTest test; test.safe_run(); }
> ```
> See modules/ts/include/opencv2/ts.hpp for BaseTest class definition. You can also browse each 
> module test subdirectory for examples.

Let's see what the devs will say.

**Comment by vpisarev** [comment]
@theodr, thank you for the contribution!

The first function provides too little functionality and utility to become a separate function. The second function might be useful if it's extended to include a delta between points (now it's 1) and handle arbitrary dimensionality (1D grid, 2D, 3D ...).

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by theodr** [comment]
@vpisarev :+1:. The function that you think that might be useful is the one with the cv::Range as inputs right, correct me if I am wrong.

**Comment by vpisarev** [comment]
@theodr, that's right

**Comment by theodr** [comment]
@vpisarev thanks. I will see what I can do and I will come back with another pr.

**Pull request closed without merging**
