### PR TITLE
documentation for the hconcat and vconcat functions

### PR DESCRIPTION
**Pull request by theodr**
documentation for the hconcat and vconcat functionality. some code snippets are provided as well.

### CODE REVIEW

**Comment by mshabunin** [comment]
@theodr, thank you for another great contribution!
1. I'd suggest to move each usage example to corresponding overloaded method.
2. Also it can be useful to add references between corresponding `hconcat` and `vconcat` methods.
   It can be added to the _See also_ section: `@sa cv::hconcat(const Mat*, size_t, OutputArray)`, `@sa cv::hconcat(InputArrayOfArrays, OutputArray)` and `@sa cv::hconcat(InputArray, InputArray, OutputArray)`.
3. Another idea is to make examples little more compact (remove `cout` line and join two blocks into one):
```.cpp
std::vector<cv::Mat> matrices = { cv::Mat(4, 1, CV_8UC1, cv::Scalar(1)),
                                  cv::Mat(4, 1, CV_8UC1, cv::Scalar(2)),
                                  cv::Mat(4, 1, CV_8UC1, cv::Scalar(3)),};
cv::Mat out;
cv::hconcat( matrices, out );
// now 'out' is
// [1, 2, 3;
//  1, 2, 3;
//  1, 2, 3;
//  1, 2, 3]
```

Although points 2 and 3 are just matter of style, use them if you wish.

**Comment by mshabunin** [comment]
:+1:

**Comment by theodr** [comment]
@mshabunin, thanks for the suggestions I think that your points were quite nice so I decided to adapt them :+1: . Moreover, I have another question for example I have implemented some functions that I am using and do not exist in the Opencv's source code. So, I would like to contirbute them as well. For example I have the corresponding matlab [meshgrid()](http://se.mathworks.com/help/matlab/ref/meshgrid.html) fucntionallity:
```
static void meshgrid(InputArray _xgv, InputArray _ygv, OutputArray _X, OutputArray _Y)
{
    Mat xgv = _xgv.getMat();
    Mat ygv = _ygv.getMat();

  cv::repeat(xgv.reshape(1,1), ygv.total(), 1, _X);
  cv::repeat(ygv.reshape(1,1).t(), 1, xgv.total(), _Y);
}

// overload function
static void meshgrid(const cv::Range &xgv, const cv::Range &ygv, OutputArray _X, OutputArray _Y)
{
  std::vector<double> t_x, t_y;
  for (int i = xgv.start; i <= xgv.end; i++) t_x.push_back(i);
  for (int i = ygv.start; i <= ygv.end; i++) t_y.push_back(i);

  Mat __X, __Y;
  meshgrid(cv::Mat(t_x), cv::Mat(t_y), __X, __Y);

  Mat(__X).copyTo(_X);
  Mat(__Y).copyTo(_Y);
}
```

Therefore, I would like to know how to do it. What I mean is should I just add to the source files that I think that they should be (e.g. core.cpp/core.hpp), document them and make a pull request or should I jump to the opencv_contrib repository. I have read the "how to contribute" documentation but it is not clear to me. Moreover, should somehow I evaluate them by some testing procedure before add them in order to secure that these functions will not cause any issues to the initial source code. If yes, how I can do that because I am not familiar with this. I read something about "google testing" evaluation way, but I think I will need some assistance to that.

**Comment by mshabunin** [comment]
@theodr, there is also many information in the [Coding Style Guide](http://code.opencv.org/projects/opencv/wiki/Coding_Style_Guide).
I can say that it is better to put function definition to `include/**/*.hpp` file and implementation to corresponding `src/*.cpp` file. 
Test are good to have to make sure that function is working as expected. Tests definitions can be quite laconic:
```.cpp
TEST(Core_<test-group>, <test-name>)
{
// 1. do something
// 2. check result with ASSERT_EQ, EXPECT_EQ, ...
// or
// 2. check result manually and call one of the:
//  - ts->set_failed_test_info(cvtest::TS::OK)
//  - ts->set_failed_test_info(cvtest::TS::FAIL_<something>)
}
```
Or test can be implemented inside a class:
```.cpp
class Core_MyTest : public cvtest::BaseTest
{
    void run( int) { /* implement it */ }
}
TEST(Core_<test-group>, <test-name>) { Core_MyTest test; test.safe_run(); }
```
See `modules/ts/include/opencv2/ts.hpp` for `BaseTest` class definition. You can also browse each module `test` subdirectory for examples.

**Comment by theodr** [comment]
@mshabunin thank you very much, when I find some time I will have a better look to your answer and if I come up with any futher questions I will let you know ;-). Thanks again, for your time.

**Pull request merged**
