### PR TITLE
Improvements of module PvAPI

### PR DESCRIPTION
**Pull request by polarfuchs99**
I have made some changes in the module PvAPI. The most changes are in the CPP file
>>>        modules/videoio/src/cap_pvapi.cpp
The following changes have been made:
1. Some minor bugs have been removed.
2. In the PvAPI module the option CAP_PROP_MONOCROME has been REMOVED because
    this option DOES NOT MAKE SENSE: For a b/w camera the option MONOCROME=false converts
    a one-channel gray image into a three-channel color image with red, green, and blue equal.
    This is NONSENSE and can be done by the user himself outside this module.
    On the other hand, in the case of a COLOR camera the option MONOCROME=false causes
    an ERROR and a CRASH of the program. Furthermore, this option has never been used by myself 
    or by any other people that I know and that are using the PvAPI module,
3. Instead the new option CAP_PROP_PVAPI_PIXELFORMAT has been added which allows
    to activate the different pixel formats (color modes) of an AVT camera. For a color camera 
    you can retrieve alternatively a one-channel gray image or a three-channel rgb image.
    This feature REPLACES the MONOCROME option and works much better.
There are some related changes in the header files 
>>>        modules/videoio/src/cap_pvapi.cpp
>>>        modules/videoio/include/opencv2/videoio/videoio_c.h
The changes have been tested successfully with an b/w AVT camera by myself and 
independently by Nick D'Ademo who has made the last major changes in the PvAPI module.

Furthermore, in the header files I have found two identical defines
(a)     CAP_PROP_MONOCROME = 19
(b)     CAP_PROP_MONOCHROME = 19
where the first one has an orthographic error. For this reason, I have removed the first one 
in favor of the second one. The changes are made in the above mentioned header files and 
in the following files
>>>        modules/java/generator/gen_java.py
>>>        modules/videoio/src/cap_dshow.cpp
The changes have been tested by a successful compilation on WINDOWS with the module
DSHOW switched on.

Sincerely,    Prof. Dr. Rudolf Haussmann, Uhldingen-Mühlhofen, Germany

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@polarfuchs99 thank you very much for updating an API which is broken as hell. That is why me and @ShaiV went on a debugging rampage in the 2.4 branch to get the interface fixed in several ways
- We ensured that the manta series is working there, and not only a preconfigured proscilla type
- We ensured that multiple AVT gigE cameras could be read at once

The result of this fix (https://github.com/Itseez/opencv/pull/3322), was that the cap_pvapi worked for the 2.4 but I now see that many of the fixes never got into master. 

What I suggest is that we try to unify both approaches and make sure that both 2.4 and master branch have identical working implementations. What do you think?

Is suggest that I will try out my AVT Manta BW camera to see if your interface is working or not. However I do think that a simple interface, like the sample (https://github.com/Itseez/opencv/blob/2.4/samples/cpp/videocapture_pvapi.cpp) added in our previous pull request should work without errors.

**Comment by polarfuchs99** [comment]
Dear Steven,
thank you for your response on my contribution. I have a Manta G31 b/w camera and tested the module on Linux and on Windows. It works perfectly. Also Nick D'Ademo, who has made a major contribution to the PvAPI module last year, has tested it successfuly with a Manta G31 camera. I think it will work also on your computer. I understand the OpenCV modules so that one can operate with a camera in a basic way. If one wants to have more features, one must write his own module. Maybe that your feature with multiple cameras was not integrated for this reaseon.

I suggest that we should clarify the things in a private communication. Here is my e-mail address: rudolf.haussmann@gmx.de. If you send me your e-mail address, I can send you the files for opencv3.0.0-beta for which I have done the tests. Then you can test my files and integrate your features. Once we have a good solution, we can go to public and make a further pull request.
Best regards,
Rudi

**Comment by StevenPuttemans** [comment]
@polarfuchs99 I got the camera connected and will try out your code this morning. Probably it will work perfectly fine. As to the feature of multiple camera access, it does work on the 2.4 branch, by simply iterating over the number of found cameras through the PvAPI.

Lets keep the communication focussed here, that allows future users to follow which changes have been applied for which reasons. 

Feel free to sent the files to steven.puttemans@kuleuven.be!

Steven

**Comment by StevenPuttemans** [comment]
@polarfuchs99 I tested your code and it works like a charm on the AVT cameras we have lying around here. What I suggest is the following.

1) Expand this PR with the same sample as the 2.4 branch, but keep PR in mind. I forgot to add this information and it is quite important to know!
2) Lets make also a 2.4 PR which copies this functionality and cleaner interface to the 2.4 branch instead of some of the workarounds that me and Shai implemented.
3) Lets clean up the cpp file. All lines of code which are commented out should be removed, it happens to much and it clugs up the code. 

I will add some remarks here and there in the available code also!
Good work!

**Comment by StevenPuttemans** [comment]
BTW it seems that the master interface has way more accessible attributes than the 2.4 branch one. Will you supply the downwards merge or should I supply it myself?

**Comment by polarfuchs99** [comment]
@StevenPuttemans 
I have sent you my changed files together with the original files for the OpenCV versions 2.4.10 and 3.0.0-beta. You can make your changes there and send me your files.

Can you please describe once again which features you want to add? 

As one feature I understand that you want to use the PvAPI with two and more cameras. When you tested the software, does it work only for one camera or also for two and more cameras?

**Comment by vpisarev** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
@polarfuchs99 could you also upload your fixes for 2.4 like you suggested by mail? It all seems to work now :)

**Pull request merged**
