### PR TITLE
changed to build opencv2.framework with opencv_contrib

### PR DESCRIPTION
**Pull request by atinfinity**
This PR is a change to build opencv2.framework with opencv_contrib.
And, I used the following command to build opencv2.framework.
<code>python opencv-3.0.0/platforms/ios/build_framework.py --contrib opencv_contrib-3.0.0 ios</code>

### CODE REVIEW

**Comment by alalek** [comment]
In general, you should not break behavior of existed build scripts.
For example, this script is used here: http://pullrequest.opencv.org/buildbot/builders/master-contrib_iOS-mac/builds/31
If you need new behavior for script, then I believe, you may add new option.

**Comment by vpisarev** [comment]
@mshabunin, could you please review it?

**Comment by atinfinity** [comment]
Thank you for your comment.
From OpenCV 3.0, <code>--contrib</code> option was added to build script('platforms/ios/build_framework.py'). When I specified this option, opencv2_contrib.framework was generated.

But, this framework is included only ’’opencv_contrib' library. So, it does not work correctly.
<http://answers.opencv.org/question/61663/how-to-make-opencv2framework-with-opencv_contrib/>

From the above background, I think that this is a bug of <code>--contrib</code> option. So, I changed a behavior of existed build scripts. I will also consider to add new option.

**Comment by alalek** [comment]
Right, separation of core and contrib parts has some issues. BTW, OpenCV needs this separation because there are several licensing/patents issues (SIFT, for example).

One of the problem is include path (Mac OS uses framework name as first part of include path by default). I believe, it will be good to replace all contrib includes to `#include <opencv_contrib/module/header.hpp>`. This change shows to developer that used module is from contrib, and it is needed to find and add opencv_contrib into project. Also this should work with opencv_contrib framework from Mac OS. But final decision of this is out of my scope (above things is my IMHO only)

**Comment by mshabunin** [comment]
@atinfinity, have you checked validity of built framework?
As I understand, it should build _opencv_world_ + _opencv_contrib_modules_ (separately), then combine all world libs into one and put it into framework, but not contrib modules.

**Comment by mshabunin** [comment]
@atinfinity, I've checked suggested patch, and it doesn't work for me. There are no opencv_contrib libraries in the resulting framework, just headers. Probably we should think about moving all contrib headers to the `opencv_contrib` folder or some other way of combining two frameworks into one.

**Comment by atinfinity** [comment]
@mshabunin, sorry for my late reply.
Please wait by next week because I was busy with my work.

**Comment by mshabunin** [comment]
@atinfinity, I will close this PR for now. Feel free to reopen if you have the solution.

**Comment by mshabunin** [comment]
@atinfinity , can you please check whether the updated variant of `build_framework.py` script works for you (#5654)?

**Comment by atinfinity** [comment]
Hi @mshabunin, I tried to build opencv2.framework with opencv_contrib.

### Environment
- Mac OS X Yosemite
- Xcode 7.1.1

### Source
- <https://github.com/mshabunin/opencv/tree/ios-framework>
- <https://github.com/Itseez/opencv_contrib/releases/tag/3.0.0>

### Build command
<code>python ./opencv-ios-framework/platforms/ios/build_framework.py ios --contrib ./opencv_contrib-3.0.0</code>

A part of the module in opencv_contrib fails to build.
So, I disabled these module from this build.

As a result, I have successfully generated the opencv2.framework with opencv_contrib.
Thank you for your help!

**Comment by ondev** [comment]
@atinfinity Hi Atinfinity,  I have build the opencv framework with you build_framework.py,  success with opencv2.framework,  there are opencv_contrib_modules's header in the framework, but when I use the xfeatures in my demo application, can't link successful.
My try to create sift instance, like:
`
cv::Ptr<Feature2D> f2d = xfeatures2d::SIFT::create();
`
but get the error:
`
Undefined symbols for architecture x86_64:
  "cv::xfeatures2d::SIFT::create(int, int, double, double, double)", referenced from:
`

**Pull request closed without merging**
