### PR TITLE
Update train_HOG.cpp

### PR DESCRIPTION
**Pull request by LorenaGdL**
Incorrect number of input arguments in main function

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Nice! Could you also supply this fix for the 2.4 branch?

**Comment by LorenaGdL** [comment]
I'm new to GitHub and surely missing a couple of things, but I think this file is not in the 2.4 branch as is  a brand new example for OpenCV 3.0.0

**Comment by StevenPuttemans** [comment]
@LorenaGdL you are right :) excuse me for the mixup :)

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
