### PR TITLE
Fixing all wrong uses of RGB channels instead of the OpenCV BGR standard

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Just like https://github.com/Itseez/opencv/pull/3974 for the master branch we need to assure that there is no documentation conflict between people believing OpenCV is reading in RGB images but then processing them using BGR functions ...

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@Dikay900 maybe this one too?

**Comment by StevenPuttemans** [comment]
@mshabunin did a grep on the documentation only and that already gave quite some fixes :)

**Comment by Dikay900** [comment]
yep seems ok :+1:

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
