### PR TITLE
add contributing guidelines

### PR DESCRIPTION
**Pull request by StevenPuttemans**
as discussed and suggested in https://github.com/Itseez/opencv/issues/5200

### CODE REVIEW

**Comment by alalek** [comment]
@StevenPuttemans Hi, Could you resolve whitespace issue?
http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/3936/steps/whitespace/logs/stdio

**Comment by StevenPuttemans** [comment]
Did so!

**Comment by vpisarev** [comment]
@StevenPuttemans, thank you for the guide. I would prefer to keep it in one place. We have https://github.com/itseez/opencv/wiki/How_to_contribute. I would suggest to extend the content of that document if needed and change CONTRIBUTING.md so that it just points to that wiki page

**Comment by StevenPuttemans** [comment]
@vpisarev I was gone for a conference last week, but I was wondering if we really want to focus on a how to contribute page? For the moment community members cannot create PRs for updating the wiki pages as I signaled before to @mshabunin

**Comment by StevenPuttemans** [comment]
Also this  contributing.MD file should be concise, else people will not read it at all. Thats the main difference with the how to contribute page.

**Comment by StevenPuttemans** [comment]
@mshabunin or @vpisarev could you guys take a second to look at how I should handle this further. The questions of the community not being able to update the wiki remains open. Same goes for https://github.com/Itseez/opencv/pull/5218#issuecomment-134088182

**Comment by StevenPuttemans** [comment]
Will reopen new PR's for this case, since I screwed up my repos locally :D

**Comment by StevenPuttemans** [comment]
@vpisarev and @mshabunin even tough I have access rights to the wiki (https://github.com/orgs/Itseez/teams/wikieditors) I cannot push changes to it. Was planning on adding those updates today to the How to contribute page. So what I did

1. Cloned the repository locally on my machine.
2. Adapted the corresponding file
3. Did a push to the repo https://github.com/Itseez/opencv.wiki.git/

But then I get a 

`remote: Permission to Itseez/opencv.wiki.git denied to StevenPuttemans.
fatal: unable to access 'https://github.com/Itseez/opencv.wiki.git/': The requested URL returned error: 403`

Any clue how to fix this?

**Comment by StevenPuttemans** [comment]
It might be that I have acces rights to the wrong repo. Looking at https://github.com/orgs/Itseez/teams/wikieditors/repositories, we can see that the repo we have access to is actually the opencv repo :D and not the https://github.com/Itseez/opencv.wiki.git/. You might want to get that fixed and give me less access rights? :D

**Comment by StevenPuttemans** [comment]
@both actually just read a bit around, and it seems that it is due to the fact that we only have read rights as a workgroup and not write rights. Ofcourse, I am still convinced that it is in the wrong repository!

**Comment by mshabunin** [comment]
@StevenPuttemans, did you try online wiki editor?
The repository is correct, *opencv.wiki.git* is connected with *opencv* repository, and team membership should provide required rights.

Git access to wiki repository should be for reading only. Please, check if online editor works for you, problem could be one of repository settings.

**Comment by mshabunin** [comment]
[Git Hub permissions levels help page](https://help.github.com/articles/repository-permission-levels-for-an-organization/) states that *Read* access level should allow *Edit wikis* action for repository (last row).

**Comment by StevenPuttemans** [comment]
@mshabunin will have a look at it.

**Comment by StevenPuttemans** [comment]
If I go to

https://github.com/Itseez/opencv/wiki/How_to_contribute

Then I have nowhere an edit button, not even if on my main page I change my ownership to Itseez member...

So I guess permissions are still off somehow?

**Comment by StevenPuttemans** [comment]
Only things I can do since I got that access, is cloning the repo locally. But I cannot change it online or through a PR.

**Comment by StevenPuttemans** [comment]
Yep even tough it states that I should be able to edit, it does not let me ...

**Comment by mshabunin** [comment]
@StevenPuttemans, please, check it again.

**Comment by StevenPuttemans** [comment]
No idea what you just did, but now the edit button appeared o_O let me try to change some content :D

**Comment by StevenPuttemans** [comment]
Okay reporting back
- I can now edit pages online
- Clone the repo locally
- NOT push changes to the repo

I guess I will have to stick to online editing?

**Comment by mshabunin** [comment]
Yes, it is recommended to use online editor, this way is safer and allows you to preview modified page.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
@mshabunin it seems that there is still something weird going on. @berak pointed out correctly on the Q&A that now every single person is able to edit the wiki, just checked with a bogus account I got lying around. This is probably not what you intended?

**Comment by mshabunin** [comment]
@StevenPuttemansm thank you for reporting. I've turned this option off for now. Probably editing will no longer work for you. We need to find some other way.

**Comment by StevenPuttemans** [comment]
@mshabunin indeed, just checked, the editing options are now indeed gone. Another option indeed might be useful, since the community is pushing me to publish some new wiki pages derived from the Q&A :)

**Pull request closed without merging**
