### PR TITLE
fixed chi square distance formulae

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Fixing bug: http://code.opencv.org/issues/2199
Chi Square formulae is wrong defined

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
The test for chi square failed but should be fixed accordingly.

        The comparison result using the method #1 (Chi-Square)
	is inaccurate (=10523.1, should be =21046.1)

Will look into it

**Comment by StevenPuttemans** [comment]
There was some dubious double test for masters, partially agreeing on this formulae.
I now made both tests and both branches identical, fingeres crossed that it builds!

**Comment by StevenPuttemans** [comment]
@vpisarev I suggest you also assign yourself to this one just like the 2.4 case, in order to ensure that they both get same implementation.

**Comment by ilya-lavrenov** [comment]
tests seem to have failed http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/2514/steps/test_imgproc_1/logs/tests%20summary

**Comment by StevenPuttemans** [comment]
Yeah I am following it up in the other PR, havent found the reason why.

**Comment by StevenPuttemans** [comment]
But feel free to look into this problem together with me. The formulae is now as it should be but the tests keep failing. Adapting them accordingly doesn't seem to work...

**Comment by vpisarev** [comment]
Hi @StevenPuttemans! I remember there was a long story about these formulas (maybe party reflected in code.opencv.org bugtracker, e-mail conversation, github patches etc.) and in the end we decided to have CV_COMP_CHISQR and CV_COMP_CHISQR_ALT that reflect both common cases. Now this patch tries to start it all over again. I suggest to retain it as is, or at least make some steps forward, not make another circle

**Comment by StevenPuttemans** [comment]
Hmm that was not clear from the patch, lets end it here than. Lets keep both measurements than, altough some of them are completely wrong :D

**Pull request closed without merging**
