### PR TITLE
2.4: export simple libs from OPENCV_LINKER_LIBS

### PR DESCRIPTION
**Pull request by alalek**
#5541

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
I believe you should also remove `OPENCV_LINKER_LIBS` usage from samples CMakeFiles when compile with OpenCV binaries...

**Comment by alalek** [comment]
I prefer to leave it as is. This variable allows to "hack" linker libs if something goes wrong.

@ilya-lavrenov Could you check CUDA builds?

**Comment by ilya-lavrenov** [comment]
yes, but I guess it should work at least without CUDA, but it fails for now

**Comment by ilya-lavrenov** [comment]
testing on our side is in progress.

**Comment by ilya-lavrenov** [comment]
cool, it works :+1:

**Pull request merged**
