### PR TITLE
NEON detection in runtime

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@asmorkalov, please, review.

**Comment by oresths** [comment]
@ilya-lavrenov thanks for implementing this.

I should note two things  : 

1) Because in filters checkHardwareSupport(CV_CPU_NEON) will be called for every line of image I think it can cause major slowdown. 
SSE version uses inline assembly so the performance impact is negligible. 
Runtime check in NEON case should be implemented outside vector operators, somehow.

2) checkHardwareSupport(CV_CPU_NEON)  is necessary for median blur to use NEON acceleration.

**Comment by ilya-lavrenov** [comment]
> I think it can cause major slowdown. 

no, all hardware checks are performed only once (when the application is starting).

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
