### PR TITLE
Add link to (external) Java tutorials

### PR DESCRIPTION
**Pull request by luigidr**
As briefly discussed via mail with @kirill-kornyakov, I would like to add a link to some OpenCV-Java (desktop) tutorials in the OpenCV 3.0 documentation, since few information about the usage of OpenCV with Java desktop are present in the current documentation.

The final goal will be to completely integrate such tutorials in the official documentation (one tutorial at time), after their complete update to OpenCV 3.0 (currently in process).
Moreover, if this pull request will be accepted, I hope to get other contributions to refine the tutorials. Such contributions would be useful for enhancing the tutorials' quality, before proposing a "real" merge into the OpenCV documentation.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
:+1: ow this is just great! Why didn't I hear of this sooner :dancers:

**Comment by alalek** [comment]
@vpisarev @kirill-kornyakov Please approve this.

**Comment by mshabunin** [comment]
Actually, we are going to add new page to http://opencv.org with links to 3rdparty sites (the one mentioned here and some other from [here](http://answers.opencv.org/question/69691/informative-websites-related-to-opencv/)), so I think this PR is not needed.

**Comment by StevenPuttemans** [comment]
:+1: btw @mshabunin I was considering making wiki pages from those topics :)

**Comment by luigidr** [comment]
Perfect, thanks for the clarification @mshabunin. Feel free to close the pull request, then...

**Comment by luigidr** [comment]
What about my "future plan":
> The final goal will be to completely integrate such tutorials in the official documentation (one tutorial at time), after their complete update to OpenCV 3.0 (currently in process).
Can I contribute by creating a pull request of one Java tutorial at time, so that the tutorials will be possibly included in the official documentation?

**Comment by StevenPuttemans** [comment]
@luigidr go ahead! Adding a tutorial a time gives you the opportunity to get decent reviews and follow ups! So please do so!

**Comment by mshabunin** [comment]
@luigidr , the "Links" page has been added to the opencv.org site: http://opencv.org/links.html

**Comment by StevenPuttemans** [comment]
:+1:

**Pull request closed without merging**
