### PR TITLE
Remove "-target-os-variant" NVCC option for CUDA 7.0

### PR DESCRIPTION
**Pull request by jet47**
It is marked as obsolete.

### CODE REVIEW

**Comment by jet47** [comment]
@asmorkalov Please review the request.

**Comment by ilya-lavrenov** [comment]
http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/2178

**Comment by jet47** [comment]
It looks like GitHub access issue, I guess it is temporal.

**Comment by asmorkalov** [comment]
:+1:

**Pull request merged**
