### PR TITLE
make Xcode 7.2 happy.

### PR DESCRIPTION
**Pull request by KeySecure**

### CODE REVIEW

**Comment by KeySecure** [comment]
make Xcode 7.2 happy.

**Comment by KeySecure** [comment]
another Xcode compiler error:
/opencv-svn/modules/calib3d/src/rho.cpp:47:10: 'precomp.hpp' file not found with <angled> include; use "quotes" instead

**Comment by alalek** [comment]
Patching 3rdparty files is not a good idea. I is hard to update these deps later in this case.

I have updated Xcode on our Mac (7.1.1 -> 7.2). But I don't see these errors, zlib and jpeg build fine (simple cmake+make / cmake -GXcode+xcodebuild).
Could your describe steps how to reproduce this problem?

**Comment by KeySecure** [comment]
The following link is my modified Xcode project settings. It can compile
the OpenCV code to REAL static library, not only a HUGE framework file
(70MB+).

https://github.com/KeySecure/OpenCV-iOS

My project settings can compiled the code to REAL static binary library,
and we can linked into our target App. It merged into the App, NOT just a
divided file such as libopencv_core.a file.

It is VERY VERY important to submit our App to the Apple App Store, or we
can NOT submit at all.

**Comment by alalek** [comment]
You should disable in your project this option to build libjpeg without hacks:  "Enable Modules (C and Objective-C)" **==> NO**

P.S. Anyway it is very strange way to build static libraries. Also "framework" is a huge static library with headers and some additional info, so you my try to reuse it.

**Comment by KeySecure** [comment]
But if I use 'framework' in my app , the size of my App will be 15MB + 70MB. It is terrible.

So I hope you can agree the others modifies. Please.

**Comment by alalek** [comment]
I understand about framework and size.
BTW, "build" directory for iOS framework contains all static libs:
```
├── build
│   ├── arm64-iPhoneOS
│   │   └─ ... library .a files here ...
│   ├── armv7-iPhoneOS
│   │   └─ ... .a files ...
│   ├── armv7s-iPhoneOS
│   │   └─ ... .a files ...
│   ├── i386-iPhoneSimulator
│   │   └─ ... .a files ...
│   └── x86_64-iPhoneSimulator
│       └── install
│           ├── include
│           │   ├── opencv
│           │   └── opencv2
│           ├── lib
│           │   └── libopencv_world.a
│           └── share
│               └── OpenCV
│                   ├── 3rdparty
│                   │   └── lib
│                   │       ├── liblibjpeg.a
│                   │       ├── liblibpng.a
│                   │       └── libzlib.a
│                   └── ...
└── opencv2.framework
    └─ ...
```
But I have no experience how to "add" them into iOS Xcode project.

Let's accept this, but there are no guarantee about saving 3rdparty changes in the future updates.
:+1:

**Comment by KeySecure** [comment]
Thanks a lot. I'm so happy. ;-)

**Pull request merged**
