### PR TITLE
Fixed ximea cmake settings

### PR DESCRIPTION
**Pull request by mzajko**
Fixed ximea cmake settings for 32bit win build and linux.

### CODE REVIEW

**Comment by mzajko** [comment]
Hi All,

what can be done for this PR to pass all tests? The last run failed on Docs:
http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/5094
Thanks for any advice.

**Comment by alalek** [comment]
Just remove trailing spaces/tabs from the mentioned lines:
http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/5094/steps/whitespace/logs/stdio
```
modules/videoio/CMakeLists.txt:135: trailing whitespace.
+    list(APPEND VIDEOIO_LIBRARIES xiapi32)	
```

**Comment by mzajko** [comment]
Thanks for the advice!

**Comment by mzajko** [comment]
Hi All,

when can I expect this PR to be merged? Thanks.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
