### PR TITLE
update camera_calibration sample

### PR DESCRIPTION
**Pull request by paroj**
- update documentation
    * correct the part about fixed aspect
    * improve formatting
    * add snippet markers to source
    * replace inline code by @ snippet
  - do not run calibration twice when using a imageList
  - make output consistent in itself (CamelCase vs no_camel_case) as well as with old camera calibrate sample
  - respect write extrinsic/ points flags
  - set the aspectRatio value when specified
  - fix writing of calibration settings. also update grammar.

### CODE REVIEW

**Comment by mshabunin** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
@mshabunin before pushing this in I think you should take a look at https://github.com/Itseez/opencv/pull/3306

@upperwal put a lot of effort in changing the tutorials on the guidelines of @vpisarev and it would be sad to see his efforts run to waste.

**Comment by mshabunin** [comment]
@StevenPuttemans, thank you for comment, I did not look at other PRs.
But these two requests are about different files and should not conflict with each other.

**Comment by StevenPuttemans** [comment]
@mshabunin sorry for the confusement :D was mixing files up, read to fast!

**Pull request merged**
