### PR TITLE
Remove "INSTALL_NAME_DIR lib" target property

### LINKED ISSUE #6005: unable to load dynamic libraries on OS X due to "lib/" prefix
On OS X there are often dynamic library loading errors because all OpenCV libraries are prefixed with "lib/" in the install name.  Examples of reported issues are

http://answers.opencv.org/question/4134/cmake-install_name_tool-absolute-path-for-library-on-mac-osx/

and 

http://stackoverflow.com/questions/26978806/dyld-library-not-loaded-lib-libopencv-core-3-0-dylib-reason-image-not-found

The problem is that the target property INSTALL_NAME_DIR is improperly being set to "lib" in the CMake build scripts.  I will submit a pull request that removes these lines and resolves this issue.

### PR DESCRIPTION
**Pull request by mleotta**
The INSTALL_NAME_DIR property of a target specifies how a dynamic library should
be found on OS X.  If INSTALL_NAME_DIR is not specified the loader will search
relative to the standard search paths.  If specified it should either be
an absolute path or relative path prefixed with either @executable_path,
@load_path, or @rpath.  Specifying "lib" does not make sense here and
causes linking error as documented here:

http://answers.opencv.org/question/4134/cmake-install_name_tool-absolute-path-for-library-on-mac-osx/

and here

http://stackoverflow.com/questions/26978806/dyld-library-not-loaded-lib-libopencv-core-3-0-dylib-reason-image-not-found

This patch removes INSTALL_NAME_DIR everywhere it is set to "lib".
An alternate solution would be to set an absolute path like
"${CMAKE_INSTALL_PREFIX}/lib" or relative path like
"@executable_path/../lib".  However, if there is not specific need for
specifying a path, it is probably best left unset.

Fixes #6005

### CODE REVIEW

**Comment by alalek** [comment]
Thanks for problem report!

I'm not sure that current fix works properly on MacOSX.
How to reproduce a problem:
```
$ cd <build_dir with usual cmake>
$ cmake -DCMAKE_INSTALL_PREFIX=`pwd`/install .
$ rm -rf ./install; make install -j5
$ cd install
$ ./bin/opencv_annotation 
dyld: Library not loaded: libopencv_highgui.2.4.dylib
  Referenced from: /build/install/./bin/opencv_annotation
  Reason: image not found
Trace/BPT trap: 5
$ otool -L ./bin/opencv_annotation 
./bin/opencv_annotation:
	libopencv_highgui.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	libopencv_imgproc.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	libopencv_core.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
# ... to run you need this approach ...
$ DYLD_LIBRARY_PATH=`pwd`/lib ./bin/opencv_annotation 
Usage: ./bin/opencv_annotation
  -images <folder_location> [example - /data/testimages/]
  -annotations <ouput_file> [example - /data/annotations.txt]

# ... without this fix it works partially also ...
$ otool -L ./bin/opencv_annotation 
./bin/opencv_annotation:
	lib/libopencv_highgui.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	lib/libopencv_imgproc.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	lib/libopencv_core.2.4.dylib (compatibility version 2.4.0, current version 2.4.12)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$ ./bin/opencv_annotation 
Usage: ./bin/opencv_annotation
  -images <folder_location> [example - /data/testimages/]
  -annotations <ouput_file> [example - /data/annotations.txt]
$ (cd bin; ./opencv_annotation)
dyld: Library not loaded: lib/libopencv_highgui.2.4.dylib
  Referenced from: /build/install/bin/./opencv_annotation
  Reason: image not found
```

I will check Linux systems later and propose some changes.

**Comment by mleotta** [comment]
Thanks for taking a look at this.

Changes to `INSTALL_NAME_DIR` should not affect other platforms like Linux.  This is specific to OS X.

It is expected behavior when not using `INSTALL_NAME_DIR` that if you install to a non-standard location then you will need to provide a library path by `DYLIB_LIBRARY_PATH` or a similar mechanism to load the libraries.  The exception is if your current working directory happens to be the where the libraries are located.  By setting `INSTALL_NAME_DIR` to `lib` you still need to use `DYLIB_LIBRARY_PATH` unless your current working directory happens to be the install root (parent directory of `lib`).  There is no reason to expect that users would want to use either of these working directories under normal use, so the `lib` prefix doesn't help anything.

Setting `INSTALL_NAME_DIR` to `lib` can cause additional problems because it is non-standard.  In particular, if you build a Mac OS X application bundle that links to OpenCV and you use CMake's `fixup_bundle` utility to pull the OpenCV libraries into the bundle it will fail because it does not know how to deal with that `lib` prefix.  This use case is what triggered me to track down this issue.

I would be interested to know if there is a valid use case for the `lib` prefix, I can't think of one and I've talked to some of the CMake developers (I work at Kitware) and they don't know why `lib` would be used as a prefix either.

As pointed out in the commit message, there are other solutions.  You can set the prefix to an absolute path.  Then it will work from anywhere.  The downside is that it is now not relocatable.  You can't move those installed libraries to a new location or copy them to a different machine with a different path.  You could also make them relative to `@rpath`, but then anyone building an executable that links to OpenCV would have to specify the `rpath` when building their program.  There is no perfect solution, but I think any of the more standard solutions is better than a `lib` prefix.

**Comment by alalek** [comment]
Thanks for update!

I agreed with fix, current values is very strange. :+1:

Moreover there is `CMAKE_INSTALL_NAME_DIR` variable which allows to control this behavior more flexible.

**Comment by jcar87** [comment]
+1 on this, hopefully it gets merged soon!

I would further suggest to prepend @rpath to the install name, like the official binaries of other libraries (Qt5 and TBB ) do.  I think OpenCV would have to make set option MACOSX_RPATH to on https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_RPATH.html. 

For any cmake project using OpenCV's imported targets, cmake would actually add OpenCV's lib dir to the rpath of any executable. Right now because of the /lib prefix, I can't even run any executable produced this way unless the libraries are in the linker's search path.

As for the executables  in OpenCV's "bin" directory, I would be curious to see what is produced by CMake / make / make instal if @rpath is included in the install name of the libraries. 


(1) if the install name is left as it is at the moment (lib/libopencv_xxx.dylib), then the libraries are not relocatable at all, and executables linked against them will only run if DYLD_LIBRARY_PATH includes opencv's base install dir (or if calling executables from a directory that contains /lib/opencv_xxx.dylib)
(2) If the install name is left as "libopencv_xxx.dylib", then this requires the libraries to be found b in DYLD_LIBRARY_PATH.  This is totally fine if the libraries are installed in /opt/local or /usr/local, but they're not relocatable beyond this. 

For options (1) and (2), utilities like CMake's fixup_bundle or Qt's macdeployqt  may not even be able to find the libraries at all. 


For the executable's in OpenCV"s <install_dir>/bin, the more ideal way would be:
- Library install names should include @rpath (as is becoming common place)
- Executables should contain this dependency 
- Executables should add @executable_path/../lib to their path. 

This would make the executables relocatable (as long as the entire install dir structure is preserved), as well as the libraries (the power of @rpath ). 

I'll do some tests and maybe I can make a pull request to fix up the ability to run all the executables in bin .

**Pull request merged**
