### PR TITLE
Fix BRISK detector&descriptor using proper AGAST.

### PR DESCRIPTION
**Pull request by cbalint13**
This PR fix issues [1] and [2] for BRISK detector and also for the descriptor parts. As part of proper fix it add AGAST detector, please see discussions and reasons in this PR [3].

[1] http://code.opencv.org/issues/3976
[2] http://code.opencv.org/issues/2491
[3] https://github.com/Itseez/opencv_contrib/pull/203

### CODE REVIEW

**Comment by cbalint13** [comment]
@vpisarev ,

* We need remove AGAST from opencv_contrib in favour of this PR. Then compile here will not fail ! I also commented over this PR: https://github.com/Itseez/opencv_contrib/pull/203

**Comment by cbalint13** [comment]
@vpisarev ,

  Any news regarding this PR ? Would like to remind that we now need to remove AGAST from contrib repo otherwise this PR will not compile here !

**Comment by vpisarev** [comment]
@cbalint13, sorry for delay. I'm absolutely fine with moving AGAST from opencv_contrib to opencv and refactoring BRISK based on that; thank you very much for this effort!
But we can only merge PR's that pass buildbot. We do it in completely automatic mode by pressing "merge" button in our internal pull request handling page. This seemingly dumb procedure results in opencv that builds fine at any moment of time.

It's good that you submitted PR to opencv and opencv_contrib from the branch with the same name "brisk". It means that our buildbot applies both patches before running build and tests. So, if you update Itseez/opencv_contrib#203 (remove AGAST) and make our buildbot "all green", we will merge both pull requests.

**Comment by cbalint13** [comment]
Will reopen one called remove AGAST.

**Comment by cbalint13** [comment]
OHH dear GITHUB  .....

**Comment by cbalint13** [comment]
Thank you _GIHUB_ for un-sync my branches ....

**Comment by cbalint13** [comment]
@vpisarev, 
Requested updates regarding contrib are done.

**Comment by vpisarev** [comment]
@cbalint13, thank you for the efforts!
Our buildbot still does not like this PR. This is because it has been submitted from "brisk" branch, whereas AGAST has been removed in "agast_r" branch. It should be PR's from the branches with the same name submitted to opencv and opencv_contrib, then our buildbot will apply both patches simultaneously and then it will likely succeed.

**Comment by cbalint13** [comment]
@vpisarev , I am done with requested things, worked on the QA side too but for "100% perfect compile" with zero warnings i would further need your help:

1. Cannot push to _extra cv/features2d/feature_detector/detector-agast.xml.gz , buildbot complains:
"Your local changes to the following files would be overwritten by merge", so with missing reference "test_feature2d" step suffer for agast !

2. I believe ABI warnings are waveable. We add agast so i think thats why it compains at all. For this step i think i cannot do anything from my side !

Notice the changes pushed : 
* PR 216 against opencv_contrib (Remove AGAST)
* PR 251 against opencv_extra (Reference datas for QA)

**Comment by vpisarev** [comment]
@cbalint13, thank you for working on it!
1) to solve the problem with tests you need to get the latest opencv_extra, make a branch with the same name and put the updated data there. It worked well many times, it would be very surprising if it fails this time.
2) ignore the complains from ABI checker, it's for the future use, now it's invoked, but the results do not influence the buildbot "green/orange/red" state.

**Comment by cbalint13** [comment]
@vpisarev ,

* Can help me with: http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/3169/steps/Merge%20opencv_extra%20with%20test%20branch/logs/stdio ?
* I told you before about this one, now you can see it. If there is no https://github.com/cbalint13/opencv_extra/commit/4d9379a39a0cdaae56637cbfb78c7cadbb5a9883 our build will fail !

**Comment by mshabunin** [comment]
@cbalint13 , it should work now. There was a problem with buildbot configuration.

**Comment by cbalint13** [comment]
@mshabunin , Thank you !
@vpisarev , Build and QA get passed.

**Comment by cbalint13** [comment]
@vpisarev ,

* Squashed all related commits. Can see all in: https://github.com/cbalint13/opencv/commit/fb56d5c482485de2b28c32b3f89b4cfff4d7989b
* Also are squashed  for opencv_extra & opencv_contrib.

If there is anything more to do please let me know.

**Comment by vpisarev** [comment]
thank you a lot! it's great that you managed to do it before 3.0 final! :+1:

**Pull request merged**
