### PR TITLE
change to improve functionality of imread

### PR DESCRIPTION
**Pull request by sturkmen72**
by this change we can set libjpeg "scale_denom" parameter and load jpeg images scaled 1/2 - 1/4 - 1/8

### CODE REVIEW

**Comment by sturkmen72** [comment]
i am newcomer here so i need to some advices.
http://answers.opencv.org/question/64798/improving-functionality-of-imread/

**Comment by vpisarev** [comment]
It's definitely not a good solution to introduce a global variable that affects imread. I would add another variant of imread (e.g. imread_reduced()). Adding a flag to imread might work too. But not in the form it's done now. Often in the code you may see imread(path, -1), which is now treated as "load the image as-is". So you should probably allocate a few bits in the flags, say, 3 bits. Use "000" and "111" as "no reduction", "001" as 1:2, "010" as 1:4, "011" as 1:8 etc.

**Comment by sturkmen72** [comment]
@vpisarev thank you. i will work to improve the code as you advised.i must confess i have no deeper knowledge of c++ but  working to improve my ability

**Comment by sturkmen72** [comment]
@vpisarev what is your opinion for last changes

**Comment by vpisarev** [comment]
looks good! the patch is basically ready for integration. Can you squash all the commits into one?

**Comment by sturkmen72** [comment]
i am thinking of some other improvements. for example 

1.now the function reduces jpeg images  1/2 1/4 1/8 (as main goal of the function ) . other formats can be reduced 1/n.
2. adding other parameters maybe a good idea like aimed_with , aimed_height etc. 

i tried to find how to squash all but i did not understand. any tips ?

**Pull request closed without merging**
