### PR TITLE
allow to retrieve videocapture properties before first frame reading

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by alalek** [comment]
There are some properties related to device controls, so proposed approach brokes this behaviour. We should allow to setup properties after open() and before first grab request.
What is about to execute grabFrame() in on-demand mode in case of empty(invalid)  width/height/etc?

**Comment by ilya-lavrenov** [comment]
> There are some properties related to device controls, so proposed approach brokes this behaviour

Changed `VideoCapture` class does not have such ones.

**Comment by alalek** [comment]
I see, you change the "image" backend of VideoCapture only.

**Comment by asmorkalov** [comment]
@alalek any comments? Are you ready for merge?

**Comment by alalek** [comment]
I have no more comments.

**Comment by ilya-lavrenov** [comment]
Let's merge it then :)

**Comment by SpecLad** [comment]
I think you need to handle the situation when grabbing fails.

**Comment by ilya-lavrenov** [comment]
> I think you need to handle the situation when grabbing fails.

Added the check, if I correctly understand you.

**Comment by SpecLad** [comment]
Not quite. If `grabFrame` fails, you shouldn't return `true` from `open` (or set `grabbedInOpen`, IMO).

**Comment by ilya-lavrenov** [comment]
I propose to take the code as is, because it keeps the original logic.

**Comment by SpecLad** [comment]
@alalek Opinion?

**Comment by ilya-lavrenov** [comment]
@alalek agree with @SpecLad. Done.

**Comment by alalek** [comment]
Right, this approach is more user friendly.
:+1:

**Pull request merged**
