### PR TITLE
Replacing license headers per PR-3700 feedback.

### PR DESCRIPTION
**Pull request by mkostin**
Replacing license headers per [PR-3700 feedback](https://github.com/Itseez/opencv/pull/3700).

### CODE REVIEW

**Comment by mkostin** [comment]
Not sure about [doxygen warnings](http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/2749) source, please advise.

**Comment by mkostin** [comment]
Is it possible that something has changed on "Docs" builder side about a day ago? Recent builds all go with similar warnings on that builder.

**Comment by alalek** [comment]
@mkostin You are right, it is testing infrastructure issue. Fixed

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
