### PR TITLE
Fixing for bug #5551 to return empty mask in case of no inliers.

### PR DESCRIPTION
**Pull request by aman11dhanpat**
Removing all the inliers if finding fundamental matrix fails.

### CODE REVIEW

**Comment by PhilLab** [comment]
Before merging this we should quickly discuss whether this behavior is desired or if we want an all-zero mask, c.f. #5551

**Comment by aman11dhanpat** [comment]
I noticed there's no official irc channel where I could discuss such doubts before implementing it. 
Any leads on this?

**Comment by aman11dhanpat** [comment]
@PhilLab , any updates on this?

**Comment by PhilLab** [comment]
@aman11dhanpat we just have to wait until some of the maintainers reads either this PR or the related issue.

**Comment by PhilLab** [comment]
@aman11dhanpat : there are whitespace errors, this is why it cannot be merged right now: http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/4501/steps/whitespace/logs/stdio . Please use spaces instead of tabs.

**Pull request closed without merging**
