### PR TITLE
Add tutorial for OpenCV Tracker

### PR DESCRIPTION
**Pull request by kurnianggoro**
This pull request contains tutorials for using OpenCV Tracker and MultiTracker

There are 3 tutorials on this pull request:
- Introduction to OpenCV Tracker and roiSelector GUI
- Using custom function for TrackerKCF
- Using MultiTracker class

### CODE REVIEW

**Comment by kurnianggoro** [comment]
@Iglesias: where is the correct place for this pull request?
If I put here then the check will be failed since it requires the files from contrib.
I Tried to put the files in contrib but the tutorial did not compiled,
or maybe I should use specific parameter for the cmake?

**Comment by iglesias** [comment]
To me it makes sense that it should go to opencv contrib.

Why did it not compile in opencv contrib? Did you get an error or it was just ignored by the build system? In case of the second, you should be right and there maybe is a parameter to set for cmake.

**Comment by mshabunin** [comment]
@kurnianggoro, try to put tutorial pages to `<opencv_contrib>/modules/tracking/tutorials` folder and all code to `<opencv_contrib>/modules/tracking/samples` folder.

**Comment by kurnianggoro** [comment]
thank you, I ported the code to contrib

**Pull request closed without merging**
