### PR TITLE
Using find_package to import custom HAL library

### PR DESCRIPTION
**Pull request by mshabunin**
Import custom HAL library using `find_package` mechanism instead of `OPENCV_HAL_HEADERS` and `OPENCV_HAL_LIBS` cmake variables.

### CODE REVIEW

**Comment by mshabunin** [comment]
cc @terfendail @asmorkalov

**Comment by asmorkalov** [comment]
Looks ok for me. @vpisarev  please look at it too.

**Comment by terfendail** [comment]
Looks ok for me.

**Comment by vpisarev** [comment]
cool! :+1:

**Pull request merged**
