### PR TITLE
Commit for opencv_extra pull request 221

### PR DESCRIPTION
**Pull request by lenlen**

### CODE REVIEW

**Comment by vpisarev** [comment]
@lenlen, could you modify some file (e.g. some description etc.) instead of adding a dummy file in the root directory?

**Comment by lenlen** [comment]
Done

**Comment by vpisarev** [comment]
:+1:

**Comment by vpisarev** [comment]
@alalek, for some reason, I'm not able to merge it, could be a problem with our merge engine. Could you look at it?

**Comment by alalek** [comment]
GitHub API returns unexpected result, need to update our scripts

**Comment by alalek** [comment]
Scripts fixed (they broke during scan of extra pull requests and because https://github.com/Itseez/opencv_extra/pull/222 has removed source repo/branch).
https://github.com/Itseez/opencv_extra/pull/221 was merged without this PR.

**Pull request closed without merging**
