### PR TITLE
Fix the issue in mouse click event

### PR DESCRIPTION
**Pull request by hyunkim9123**
This patch fixes issue to fail draw sqaure in ubuntu 14.04. #5520
I have tested with the versions of python 2.7.6 and opencv 2.4.8

### CODE REVIEW

**Comment by hyunkim9123** [comment]
I have created an issue for this pull request at #5520

**Comment by mshabunin** [comment]
@hyunkim9123, please note that your fix is made on _master_ branch. It means that it will be available only in next _3.x_ version. In case to port it to next _2.4.x_ version you have to create another pull request with same fix targeting _2.4_ branch.

**Comment by hyunkim9123** [comment]
@mshabunin,  I already verified this issue occurs in version 3.0.0 and this patch fixes that. For 2.4.x. version, will do another pull request to 2.4 branch.

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
