### PR TITLE
Added flexible and generic imreadex API that calls a user callback on each page

### PR DESCRIPTION
**Pull request by Ashod**
The new API function is flexible as it support both single- and multi-page images.
It's used to implement imreadmulti API, and includes an example code in the doc.
The API is designed for efficient and very flexible usage when loading large multi-page
images, where loading only a range of pages or certain pages is necessary.

### CODE REVIEW

**Comment by Ashod** [comment]
Python generated files don't like void*. Any ideas how to work around it?

**Comment by mshabunin** [comment]
@Ashod, I'm not sure if we can wrap method accepting callback function into python. You need either to replace `CV_EXPORTS_W` with `CV_EXPORTS` either to use C++ way with special object handling callbacks.

**Comment by Ashod** [comment]
Thanks @mshabunin. I want to support as many languages as possible.

For now, I'll use CV_EXPORTS and maybe someone can improve in the future.

**Comment by vpisarev** [comment]
@Ashod, I would postpone integration of this patch. It adds some functionality that might be useful in the future, but currently there are not real use cases for it. The lack of interaction with any codec (multi-page gif? tif? dicom? ...) in this patch proves it. I would say, when we have such support, I would only retain imreadmulti with enough extra parameters, but no any callbacks.

**Comment by Ashod** [comment]
@vpisarev I'm not sure I follow your point.

I've had private request for this (can forward the email if interested,) and I personally benefit from it as well.

The new API simply gives more control over loading multipage formats. I even merged the current imreadmuli interface to use it, which makes the new code even more useful. So I'm not sure what you mean by "lack of interaction with any code" since multipage tiffs are in the unit-tests and are used by the community.

The new API is designed for very large multipage images and to make loading more efficient (a user doesn't need to hold all pages in memory and can process them one at a time as they are opened from the file). I'm fairly certain this will prove useful to some users.

**Comment by Ashod** [comment]
@vpisarev I'm still waiting your comments on my response.
I'm not sure I understand your objection to callbacks as it seems a reasonable way to load large multi-page images without hogging the memory.

Are you suggesting a better way? I'm open to suggestions.

**Pull request closed without merging**
