### PR TITLE
Remove unnecessary segmentation faults:

### PR DESCRIPTION
**Pull request by hziSot**
$ ./bin/opencv_createsamples -w
zsh: segmentation fault (core dumped)  ./bin/opencv_createsamples -w
$ ./bin/opencv_traincascade -numThreads
zsh: segmentation fault (core dumped)  ./bin/opencv_traincascade -numThreads

### CODE REVIEW

**Comment by mshabunin** [comment]
@hziSot, I think it will be better to use _cv::CommandLineParser_ class instead. It is not well documented, but there are many examples:
- documentation: [sphinx](http://docs.opencv.org/master/modules/core/doc/command_line_parser.html) or [doxygen](http://docs.opencv.org/ref/master/d0/d2e/classcv_1_1CommandLineParser.html)
- using in [samples](https://github.com/Itseez/opencv/search?utf8=%E2%9C%93&q=CommandLineParser&type=Code)

What is your opinion? Can you do it?

**Comment by hziSot** [comment]
Will try.
Should I close this pull request and create the new one?

**Comment by mshabunin** [comment]
Thank you, I'll provide help if you need.

>Should I close this pull request and create the new one?

Usually it is not needed, but this case is slightly different: our integration system can have problems when merging with branches named `master` and `2.4`. So, the answer is: yes, please, close this pull request and create another one from branch with different name (for example _fix-apps-cmd-parse_).

**Comment by StevenPuttemans** [comment]
:+1:  nice fix! Love to see more people get involved with the cascade classifier interface :) Seems still heck a lot of bugs are out there :D

**Pull request closed without merging**
