### PR TITLE
Generalized Matrix Multiplication demo

### PR DESCRIPTION
**Pull request by Wangyida**
There is a wrong description in fundam.cpp

in line 528 to 530, such description is wrong, this coding is calculating F0 <- U'diag([W(1), W(2), 0])V:
 // F0 <- Udiag([W(1), W(2), 0])V'
 cvGEMM( &U, &W, 1., 0, 0., &TF, CV_GEMM_A_T );
 cvGEMM( &TF, &V, 1., 0, 0., &F0, 0/CV_GEMM_B_T/ );

To get Udiag([W(1), W(2), 0])V', it should be:
 cvGEMM( &U, &W, 1., 0, 0., &TF, 0 );
 cvGEMM( &TF, &V, 1., 0, 0., &F0, CV_GEMM_B_T );

### CODE REVIEW

**Comment by Dikay900** [comment]
Hi there i see you have problems creating a pr, please when creating a pr for the master branch. Go into your local repo change it to the master branch
``` git checkout master ```
then create a new branch which is different from master and all other already existing branches like:
``` git checkout -b fix_generalized_mat_mul ```
now make your changes to the code and then create a pr against the initial repo so if you started in your master branch then create a pr for the master branch.

**Comment by Wangyida** [comment]
Thanks very much, I have done it with Github for Windows, I have made a change in my local repository and made a PR in branch 2.4


Sorry for a newbie in bug repoter, I have been report bugs and bugfixes in code.opencv.com in the past, Thank you for teaching me the simple sollution.


I prepairing for GSoC 2015 for OpenCV, many works have been made with the help of OpenCV , I just made a library called LDANet in pattern recognition area. Could I made a PR to add it to further released version of OpenCV?


At last, would you told me something useful for the preparation for OpenCV GSoC 2015?


Best Wishes

 Yida Wang, PRIS laboratory in BUPT





Sent from Windows Mail





From: Philip
Sent: ‎Tuesday‎, ‎January‎ ‎20‎, ‎2015 ‎2‎:‎55‎ ‎PM
To: Itseez/opencv
Cc: wangyida123@outlook.com





Hi there i see you have problems creating a pr, please when creating a pr for the master branch. Go into your local repo change it to the master branch
git checkout master
then create a new branch which is different from master and all other already existing branches like:
git checkout -b fix_generalized_mat_mul
now make your changes to the code and then create a pr against the initial repo so if you started in your master branch then create a pr for the master branch.

**Comment by Dikay900** [comment]
Since i do not use "Github for Windows" i cannot assist you directly what you have to do there. Basic information what you have to do were stated earlier.

Please check this link i found for creating a Pull Request with Github for Windows: http://www.wdtutorials.com/2013/10/06/github-windows-tutorial-4-fork-pull-request

Again to my previous message:
You must create a new branch at your local repository, make your change in this fresh branch and then create a pull request out of this branch. If your original branch was master then you should create a PR against the master branch, if your original branch was 2.4 then your should create a PR against the 2.4 branch. I hope this helps a bit.
You have to open another Pull Request as this will get closed for sure.

For the GSoC 2015 for OpenCV maybe you get faster responses here: http://answers.opencv.org/questions/
In general i would say sure you can commit anything that will help using opencv and ofcourse new algorithms too but you have to learn yourself how to do it since the developer here cannot assist everyone to commit their changes. Please consider asking anything you like at the link above.
Furthermore I think such a library has to be a part of opencv_contrib since this library would be contributed by you so opening a PR at opencv_contrib has to be done rather than in this repo.

**Comment by ilya-lavrenov** [comment]
please, remove excess commits and reopen

**Pull request closed without merging**
