### PR TITLE
new function imread_reduced()

### PR DESCRIPTION
**Pull request by sturkmen72**
by this new function we can set libjpeg "scale_denom" parameter and load jpeg images scaled 1/2 - 1/4 - 1/8
other image formats resized after loading

### CODE REVIEW

**Comment by sturkmen72** [comment]
all commits squahed see https://github.com/Itseez/opencv/pull/4162

i am thinking of some other improvements. for example

1.now the function reduces jpeg images 1/2 1/4 1/8 (as main goal of the function ) . other formats can be reduced 1/n.maybe it need normalization for all image formats.
2. adding other parameters maybe a good idea like aimed_with , aimed_height etc.

**Comment by vpisarev** [comment]
:+1:

**Comment by sturkmen72** [comment]
thank you for your help.
i have a question. i am still thinking of some other improvements. i wonder if i can change the name of the function with more inclusive name?

**Comment by alalek** [comment]
@sturkmen72 I believe you can (we don't make public releases with current name). Feel free to create new PR.

**Comment by sturkmen72** [comment]
@alalek where can i discuss for finding a good name. 
for example some alternatives i thought 
"imreadresize" or "imreadResize"  - means function basicly imread+resize
 "imreadEx" - means imreadExtra
etc. maybe someone suggest more meaning name

**Comment by sturkmen72** [comment]
have another question if i don't bother you.

**Comment by alalek** [comment]
I believe @vpisarev can help you with function name.

Overload is possible but you need to drop default parameters values:
```
imread( const String& filename, int flags /* IMREAD_COLOR */, int scale_denom /* 1 */)
```

BTW, More general case is to use "float scale" and make inner checks for 1/2 1/4 (via `fabs(scale - 0.5) < FLT_EPSILON`)

**Comment by sturkmen72** [comment]
if overload possible then i think no need to new function. what is your opinion. 
may i make it overload

**Comment by paroj** [comment]
existing applications will look for `imread_2Arg` so you must not remove it in favour of your `imread_3Arg`. (see C++ name mangling for details)

**Pull request merged**
