### PR TITLE
Small fix on flag setting in cascade classifier model reading

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Described in title :D

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
O well forget this, stupid me breaks also the reading of features. It is only a redundant setting of the flag... this is not a correct fix.

**Comment by StevenPuttemans** [comment]
O wait I can do it correctly with an addition

**Comment by StevenPuttemans** [comment]
However I am wondering if the extra check in the if loop doesn't take as long as simply setting it :D lets call it a code beauty fix!

**Comment by vpisarev** [comment]
@StevenPuttemans, thanks for the patch, but I would disagree it's code beauty fix :) setting flag only if it was not set before is irrelevant thing and most of the time irrelevant things do not add beauty :)

**Comment by StevenPuttemans** [comment]
Okay lets ignore it then!

**Pull request closed without merging**
