### PR TITLE
[2.4] remove some functions that have no implementation

### PR DESCRIPTION
**Pull request by oli-obk**
These functions are only declared in the header files, but do not have implementations in any c(pp) files.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Yep these are old leftovers. All that stuff moved to the opencv_contrib repository! Thanks for the fix!

**Comment by vpisarev** [comment]
looks like at least colormap is used. cvStopLoop is implemented in some of backends.

**Comment by oli-obk** [comment]
@vpisarev so what is your suggested fix? I'd rather resolve this properly.

I also don't see how colormap can be used as it has no implementation.

**Comment by StevenPuttemans** [comment]
@vpisarev it seems that colormap is part of the FaceRecognizer interface as described [here](http://docs.opencv.org/2.4/modules/contrib/doc/facerec/colormaps.html?highlight=colormap#void%20applyColorMap%28InputArray%20src,%20OutputArray%20dst,%20int%20colormap%29) ... so basically it should NOT be inside the objectdetect module.

**Pull request closed without merging**
