### PR TITLE
Update imgproc.hpp

### PR DESCRIPTION
**Pull request by sturkmen72**
http://code.opencv.org/issues/4372

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
:+1: thank you!

**Comment by sturkmen72** [comment]
i wonder "using namespace std;" needed or not?
on code:block i can't compile without "using namespace std;"

also i wonder help documentation will update automatically ?

**Comment by StevenPuttemans** [comment]
Well basically std is only needed if you use standard functions. I am not seeing where these are used...

**Comment by Dikay900** [comment]
using namespace std should be fine here i do not see any problems with it.
std is used here for the vector i think? Else you can also replace vector with std:vector and your compile problems will also be solved.

**Comment by StevenPuttemans** [comment]
Completely forgot the vector :P

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
