### PR TITLE
Bugfix- findChessboardCorners causes crash (Issue# 5145)

### PR DESCRIPTION
**Pull request by robertxwu**
findChessboardCorners causes crash due to out-of-bounds memory corruption. Refer to issue #5145 for detail.

### CODE REVIEW

**Comment by robertxwu** [comment]
findChessboardCorners causes crash due to out-of-bounds memory corruption. Refer to issue #5145 for detail.

**Comment by robertxwu** [comment]
Do I have to do any to merge the change to Itseez:master? 
Thanks.

**Comment by alalek** [comment]
@robertxwu Thanks!
I can confirm crash fix for test image/code from the issue.
Could you please squash commits into one (intermediate changes in git history are not necessary):
```
git checkout Bugfix_Issue#-5145
git rebase -i HEAD~4  # (`p` for first commit and `s`/`f` for another)
git push -f <your_github_remote> Bugfix_Issue#-5145
```

**Comment by alalek** [comment]
See #5396

**Pull request closed without merging**
