### PR TITLE
ml: fix NormalBayesClassifier bulk prediction

### PR DESCRIPTION
**Pull request by berak**
see issue #5911

### CODE REVIEW

**Comment by berak** [comment]
do we need a regression test ?

``
TEST(ML_NB, regression_5911)
{
    int N=12;
    Ptr<ml::NormalBayesClassifier> nb = cv::ml::NormalBayesClassifier::create();

    // data:
    Mat_<float> X(N,4);
    X << 1,2,3,4,  1,2,3,4,   1,2,3,4,    1,2,3,4,
         5,5,5,5,  5,5,5,5,   5,5,5,5,    5,5,5,5,
         4,3,2,1,  4,3,2,1,   4,3,2,1,    4,3,2,1;
    
    // labels:
    Mat_<int> Y(N,1);
    Y << 0,0,0,0, 1,1,1,1, 2,2,2,2;
    nb->train(X, ml::ROW_SAMPLE, Y);

    // single prediction:
    Mat R1,P1;
    for (int i=0; i<N; i++)
    {
        Mat r,p;
        nb->predictProb(X.row(i), r, p);
        R1.push_back(r);
        P1.push_back(p);
    }

    // bulk prediction:
    Mat R2,P2;
    nb->predictProb(X, R2, P2);

    EXPECT_EQ(sum(R1 == R2)[0], 255 * R2.total());
    EXPECT_EQ(sum(P1 == P2)[0], 255 * P2.total());
}
``

**Comment by alalek** [comment]
@berak Thank you! :+1:
It will be nice to have regression test for this!

**Comment by berak** [comment]
added test to test_mltests.cpp

**Comment by amroamroamro** [comment]
@berak thanks for the fix!

While we're at it, perhaps also add a check for the non-continuous case. Something like:

``` cpp
    // bulk prediction, with non-continuous memory storage
    Mat R3_(N, 1+1, CV_32S),
        P3_(N, 3+1, CV_32F);
    nb->predictProb(X, R3_.col(0), P3_.colRange(0,3));
    Mat R3 = R3_.col(0).clone(),
        P3 = P3_.colRange(0,3).clone();

    ...

    EXPECT_EQ(sum(P1 == P3)[0], 255 * P3.total());
```

**Comment by berak** [comment]
good idea, sure !

**Comment by alalek** [comment]
:+1:

**Pull request merged**
