### PR TITLE
Update Variables'name with new ffmpeg version

### PR DESCRIPTION
**Pull request by jas0n1ee**
ffmpeg/libav drops deprecated code (master branch):
http://git.videolan.org/?p=ffmpeg.git;a=commit;h=183db02a51a422568084b113a7571c845ca68622
and other commits

### CODE REVIEW

**Comment by jas0n1ee** [comment]
Please provide ffmpeg version or libavcodec version

**Comment by alalek** [comment]
Could you please add PR description with information about used ffmpeg (or libav) version?

To be merged patch should not break builds for existed platforms. I believe some "#if" should be added like this (with correct ffmpeg versions):
```
#if LIBAVCODEC_BUILD >= (LIBAVCODEC_VERSION_MICRO >= 100 \
     ? CALC_FFMPEG_VERSION(54, 59, 100) : CALC_FFMPEG_VERSION(54, 28, 0))
```

**Comment by jas0n1ee** [comment]
ffmpeg just release 2.8 version these days with LIBAVUTIL_VERSION_MAJOR 55 MINOR 1 MICRO 100.

**Comment by alalek** [comment]
How to reproduce build problem? I can't reproduce problem with ffmpeg 2.8 (git tag n2.8) during build of windows ffmpeg wrapper. It builds without problems.

**Comment by jas0n1ee** [comment]
Please see FFmpeg repo master branch commit 183db02a51a42256808, they delete old_pix_fmt.h where PIX_FMT_BGR24 and other macros are defined.

**Comment by alalek** [comment]
Thanks, I see this and can reproduce build problem.
This commit is on master branch only. It is not part of 2.8 release (and not on 2.9-dev).

**Comment by jas0n1ee** [comment]
Yeah It might not be a problem right now, but there are always someone use ffmpeg's master branch.

**Comment by alalek** [comment]
Unfortunatelly this patch doesn't work on Ubuntu 12.04 LTS with libav:
```
--     FFMPEG:                      YES
--       codec:                     YES (ver 53.35.0)
--       format:                    YES (ver 53.21.1)
--       util:                      YES (ver 51.22.3)
--       swscale:                   YES (ver 2.1.0)
--       resample:                  NO
--       gentoo-style:              YES
```

Need to be more accurate here (#ifdef doesn't work with enum values, also we can't force `AVPixelFormat`, because it is undefined in the old ffmpeg versions).
I will try to provide fix for this later on this week.

**Comment by alalek** [comment]
Changes are moved to #5361

**Pull request closed without merging**
