### PR TITLE
Update cascadeclassifier.cpp

### PR DESCRIPTION
**Pull request by teng88**
evaluate minimumAcceptanceRatio condition only after consumed++, and thus consumed > 0 is automatic satisfied

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Before we allow this change, we should look into the fact why this was removed in the master branch compared to 2.4 ...

**Comment by teng88** [comment]
looked into this code and found that: for 2.4 branch, if minAR (minimumAcceptanceRatio) condition is met, the fillPassedSamples function will immediately return and then the training procedure terminated; for master branch, even if minAR condition is met, the fillPassedSamples function will continue to try fill pre-defined num of negative samples and then terminate the training procedure. SO, the master branch is a bit faster in fillPassedSamples function itself for normal case (since the minAR condition code is removed), but is slow in the last stage where minAR condition is met.

**Comment by StevenPuttemans** [comment]
@vpisarev can I have your opinion on this? I would suggest that both implementations in 2.4 and master are equally evolving so I would suggest to remove the check in the 2.4 branch also.

**Comment by teng88** [comment]
@StevenPuttemans some information: I found the latest PR merging from 2.4 incluing this minAR condition evaluation :-)

**Comment by StevenPuttemans** [comment]
Could you link it here?

**Comment by teng88** [comment]
#5757

**Comment by StevenPuttemans** [comment]
Ow that is a major branch merge. I still suggest to add your proposed fix!

**Comment by alalek** [comment]
https://github.com/Itseez/opencv/pull/5757
Check only the latest commit.

Original patch is https://github.com/Itseez/opencv/pull/3236 (2.4)

**Comment by StevenPuttemans** [comment]
So basically you just linked where it got introduced and you are now suggesting to move it a bit further?

**Comment by teng88** [comment]
I think this behavior of 2.4 is fine. When #5757 is merged, I will submit this fix also for master

**Comment by StevenPuttemans** [comment]
Ok! So this gets closed down then? Kind of confused now :D

**Comment by teng88** [comment]
@vpisarev is this PR ready for merge?

**Comment by vpisarev** [comment]
@teng88, to me getPos() and getNeg() can be quite expensive procedures, whereas the check "consumed != 0" is instant. So why do this change?

**Comment by teng88** [comment]
in theory, this should accelerate the function a little bit, since the check "consumed != 0" removed for each sample
really minor change I think :-) @vpisarev

**Comment by vpisarev** [comment]
I see; ok, so it may speed up things a little bit, it can slow down things a bit, because getPos()/getNeg() are called one extra time. So, let's close this one

**Comment by teng88** [comment]
@vpisarev it should not call getPos()/getNeg() one extra time I think, cause the minAR condition is checked every time consumed++, when the condition met, it will break just in the iteration of current sample, and thus the following setImage and predict is saved for one extra time. what's ur opinion?

**Pull request closed without merging**
