### PR TITLE
Fix bug #3989: fitEllipse bounding boxes too small

### PR DESCRIPTION
**Pull request by dhood**
If I have understood correctly, at [this point](https://github.com/Itseez/opencv/blob/master/modules/imgproc/src/shapedescr.cpp#L450) in the fitEllipse algorithm, if the ellipse has its axes parallel to the xy axes (i.e. rotated by n\*pi/2) then **both** gfp[2] and t are ~0. Thus for the example in [bug 3989](http://code.opencv.org/issues/3989), the 'else' is not entered into as gfp[2] = -1.56545e-19 and t = -1.22465e-16.

I have changed the condition to just test for t, but testing for gfp[2] as well/instead are also valid solutions I believe.

### CODE REVIEW

**Comment by dhood** [comment]
Do you have a reference to the algorithm by Dr. Daniel Weiss in use now so I can update the [documentation](http://docs.opencv.org/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#fitellipse)?

**Comment by dhood** [comment]
Actually, if you want, we can test on ```gfp[2]``` to avoid calculating ```t=sin(-2*rp[4])``` unless necessary.

**Comment by vpisarev** [comment]
@dhood, thanks for the patch and sorry for delay.
I believe, the new test is not a complete replacement for the previous one. The case when t=sin(-2.0 * rp[4]) is small, but gfp[2] is not that small, is not handled. Probably, the condition should be something like:
<pre>
if( fabs(gfp[2]) &gt; min_eps && fabs(t) gt; fabs(gfp[2])*min_eps )
  ...
</pre>

**Comment by dhood** [comment]
Hi @vpisarev, thanks for the review. 

May I ask why you propose to keep the test on t as relative to gfp[2]? I am only inferring the algorithm from the code, so I may not be correct, but isn't gfp[2] theoretically equal to (```2*(b^2-a^2)cos(theta)sin(theta)```)[(equation for C)](http://en.wikipedia.org/wiki/Ellipse#General_ellipse) and thus ```gfp[2]=-(b^2+a^2)t```? Then the ```(fabs(t) > fabs(gfp[2])*min_eps)``` test is equivalent to ```1>(b^2-a^2)*min_eps``` which is not adding much information (indeed I cannot produce an ellipse that makes this false). Can it not be just ```if( fabs(gfp[2]) > min_eps && fabs(t) > min_eps)```?

Also (again conditional on my understanding of the algorithm), I wouldn't have thought that for the case you mentioned (when t=sin(-2.0 * rp[4]) is small, but gfp[2] is not that small) we would want that behaviour, as regardless of gfp[2] the ellipse is still parallel to the xy axes and so we should use the simplified equations for rp[2] and rp[3]. So I would think that the test can just be ```if(fabs(t)>min_eps)```, without considering gfp[2].

Having said that, I can't actually produce an ellipse that gives different results using the condition you propose and the condition ```if(fabs(t)>min_eps)```, which I suspect is because testing on gfp[2] is essentially equivalent to testing on t unless it is an extremely eccentric ellipse.

That is, I see ```if(fabs(gfp[2]) > min_eps && fabs(t) > fabs(gfp[2])*min_eps)``` equivalent to ```if(fabs(gfp[2]) > min_eps)``` and ```if(fabs(t) > min_eps)``` if ```b^2-a^2 < 10^8```. I propose using the latter just to be safe.

**Comment by vpisarev** [comment]
@dhood, ok, I've checked the formulas. You are right! :+1:

**Pull request merged**
