### PR TITLE
Bug #4315 : fix CUDA bitwise operations with mask

### PR DESCRIPTION
**Pull request by jet47**
http://code.opencv.org/issues/4315

### CODE REVIEW

**Comment by jet47** [comment]
@ilya-lavrenov Could you please review the request?

**Comment by ilya-lavrenov** [comment]
is this case covered by tests? If not, we should add them.

**Comment by jet47** [comment]
Yes, I added additional tests for mask case.

**Comment by ilya-lavrenov** [comment]
:+1:

**Pull request merged**
