### PR TITLE
Universal OpenCV based annotation tool for making createsamples input data

### PR DESCRIPTION
**Pull request by StevenPuttemans**
This is a frequently asked application by many OpenCV Q&A forum users so I decided to make this interface publically available in the codebase.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
A video illustrating how this actually works can be seen here:

< iframe title="YouTube video player" width="854" height="480" src="https://www.youtube.com/watch?v=SWSUJZiuUPk?autoplay=1" frameborder="0" allowfullscreen>< /iframe>

**Comment by StevenPuttemans** [comment]
@vpisarev I was wondering if OpenCV is even interested in something like this. Reason for asking, writing a book chapter on the cascade classifier interface for PacktPub and I either supply this tool through a self made github OR I try to get it into the repo :)

**Comment by vpisarev** [comment]
:+1:  the app looks useful, but some user-visible documentation would be nice to have.

**Comment by StevenPuttemans** [comment]
@vpisarev @mshabunin  I will be adding a user visible documentation, combined with an automated Cmake file for this tool (requested in the master branch https://github.com/Itseez/opencv/pull/3654) in the near future!

**Pull request merged**
