### PR TITLE
compute fps changed (now only interop counts). fixed d3d10 and d3d11 …

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
…print info method (there were issues with texture mapping)

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@alalek @SergeySivolgin please, take a look on changed dx interop samples

**Comment by alalek** [comment]
`Timer` class doesn't provide expected results:
- it doesn't measure time between start/stop calls (measure interop operation only):
```
while (true)
{
        t.start();
        usleep(10*1000);
        t.stop();
        std::cout << i << ": " << t.fps() << std::endl; // ~50 fps is here, should be ~100
        usleep(10*1000);
}
```
- first fps() value (after start/stop) is wrong
- fps() call without any start/stop --> division by zero (actually it is not problem for FP arithmetic and NaN result)
- warning:
```
warning: declaration of ‘fps’ shadows a member of 'this' [-Wshadow]
             float fps = sz * m_tick_frequency / (m_t0 - m_t1);
```

BTW, I believe It is better to output "interop processing time in ms" instead of "strange fps".

**Comment by vladimir-dudnik** [comment]
@alalek fixed issues, please take a look

**Comment by alalek** [comment]
:+1:

**Pull request merged**
