### PR TITLE
SSE optimization

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by vpisarev** [comment]
@ilya-lavrenov, looks like the code does not build on ARM

**Comment by ilya-lavrenov** [comment]
@vpisarev, fixed.

**Comment by vpisarev** [comment]
terrific! thanks a lot! :+1:

**Comment by tpietruszka** [comment]
Hello! 
Not sure if this is the right place to comment after a merge, but..

seems like this doesn't build on ubuntu 32-bit, gcc 4.8.2 
issue:
http://code.opencv.org/issues/4145


cherry-picking this commit (a bugfix from 2.x) https://github.com/Itseez/opencv/commit/ea50be0529c248961e1b66293f8a9e4b807294a6 
solves the compilation problem, but I do not know exactly how the function is supposed work...
@ilya-lavrenov ?

**Pull request merged**
