### PR TITLE
FindCUDA.cmake backport from master

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
these cmake scripts correctly find CUDA during cross-compilation

### CODE REVIEW

**Comment by jet47** [comment]
I guess you should also port changes in `OpenCVDetectCUDA.cmake`.

**Comment by vpisarev** [comment]
@ilya-lavrenov, @jet47, so, what's the followup? should be merge the PR, close it or wait for the further changes?

**Comment by jet47** [comment]
@ilya-lavrenov Please port the changes in `OpenCVDetectCUDA.cmake` file too.

**Comment by jet47** [comment]
@ilya-lavrenov ping

**Comment by ilya-lavrenov** [comment]
@jet47, any other changes that I need to backport?

**Comment by jet47** [comment]
Please also port https://github.com/Itseez/opencv/pull/3643

**Comment by ilya-lavrenov** [comment]
done.

**Comment by jet47** [comment]
:+1:

**Pull request merged**
