### PR TITLE
C++ sample code for active contour detection.

### PR DESCRIPTION
**Pull request by samyak-268**
Added a C++ file along with a sample input image that demonstrates Active
Contour detection (Snake algorithm).

My motivation for submitting a sample for ``` cvSnakeImage() ``` originated from the fact that there is surprisingly less amount of documentation or tutorials available online for Active Contour detection. Most of the threads in online Q&A forums do not point to any meaningful places.

I have tried to make the code well-documented and self-explanatory and also provided a sample image to run the program on.  The image is a pseudo-hue transformation of a lip region (the original task for which I was applying ``` cvSnakeImage() ``` ).

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Since OpenCV2.x there was a decision to change everything to the C++ API and leave the depricated C-API. I will place some modification suggestions to reach desired results.

**Comment by StevenPuttemans** [comment]
And basically internally findContours does exactly the same, based on a given image with edges!

**Comment by samyak-268** [comment]
I see. Well, if the function is being deprecated, I agree that there isn't much use of pushing the sample. Also, I didn't quite get "program the snake behavior using the C++ interface". Does it mean providing a C++ equivalent to the C-function?

**Comment by StevenPuttemans** [comment]
Indeed, it would be nice if you could make a sample out of existing OpenCV C++ functionality, which should be possible.

**Comment by cancan101** [comment]
Once the OpenCV 3.0 release are there any plans to bring over `cvSnakeImage`?

**Pull request closed without merging**
