### PR TITLE
Add interrupt callback with default timeout of 30s. 

### LINKED ISSUE #5730: Indefinite hang when connecting to a rtsp stream
Built latest version from `HEAD` with ffmpeg support enabled on Windows 10.

When you connect to a rtsp stream and the resource (read: the streaming server) is unavailable an indefinite hang on Windows is observed.

I've done some initial research and if you want to handle transient connection issues you need to specify a interrupt callback as per [documentation](https://ffmpeg.org/doxygen/2.7/structAVFormatContext.html#a5b37acfe4024d92ee510064e80920b40) before `avformat_open_input` is called.

Digging through their bug tracker i found a related [issue](https://trac.ffmpeg.org/ticket/2694) submitted about two years ago.

Repo:

```c++
auto vc = new cv::VideoCapture();
auto success = vc->open("rstp://192.168.1.200/media/video1");
// -- indefinite hang
```

### PR DESCRIPTION
**Pull request by peters**
In order to speed up the review process I've set up a x64 debug/release project over at https://github.com/peters/opencv.ffmpeg with the latest official ffmpeg 2.8.5 binaries included.

Fixes #5730.

/cc @alalek @vpisarev

### CODE REVIEW

**Comment by alalek** [comment]
Thanks! Look good to me.
Interrupt callback has been added since: "2011-11-13 - lavf 53.21.0 / 53.15.0" , so conditional compilation may required for some legacy versions of ffmpeg.
I checked Ubuntu 12.04 LTS, there is ffmpeg format 53.21.1, so it is fine. I hope ROS builds will pass also.

Could you please squash commits into one (`git rebase -i HEAD~4`)

**Comment by peters** [comment]
> Thanks! Look good to me.

Awesome :+1: 

> Could you please squash commits into one (git rebase -i HEAD~4)

Done 

> I hope ROS builds will pass also

Is those builds internal because I can't find them in the waterfall overview.

**Comment by peters** [comment]
What is the reason hardware accelleration is disabled for the windows build? There is some documentation over at https://trac.ffmpeg.org/wiki/HWAccelIntro. But I don't want to spend more time on this if there is nothing to gain from it :)

**Comment by alalek** [comment]
:+1:

**Comment by alalek** [comment]
> What is the reason hardware accelleration is disabled for the windows build?

I believe to reduce size of binaries and additional dependencies for mingw builds

**Comment by peters** [comment]
Aha, then I have much to gain from pursuing this further. I'll do some research and possibly create a repository on github allowing hardware accelleration on Windows for those who need it :)

**Comment by peters** [comment]
The build is failing, but it appears unrelated to my changes.

**Comment by peters** [comment]
@alalek Thanks for reviewing this so fast. I'm going to donate the 500$ bounty to opencv foundation just for that :+1: :trophy:

**Comment by sturkmen72** [comment]
what should i do to take effect of this fix. recompiled the library but nothing has changed. should i download opencv_ffmpeg310.dll ?

**Comment by alalek** [comment]
OpenCV build for Windows uses prebuilt binaries with ffmpeg wrapper. And they are not updated and not integrated into OpenCV yet.

I prepared the latest version of ffmpeg wrapper binaries, but they are not tested (also ffmpeg release is not updated). They are build via this [script](https://github.com/alalek/opencv_3rdparty/blob/ffmpeg/master/build_update.sh) (Linux with Docker is required)

Also you can use [this OpenCV patch](https://github.com/Itseez/opencv/compare/Itseez:master...alalek:ffmpeg_20160207?expand=1), which automatically downloads ffmpeg binaries.

Or you can try to replace ffmpeg.dll's from [there](https://github.com/alalek/opencv_3rdparty/tree/ffmpeg/master_20160207/ffmpeg), but this may require to disable CMake [downloader](https://github.com/Itseez/opencv/blob/3.1.0/3rdparty/ffmpeg/ffmpeg.cmake#L10-L23)

**Comment by sturkmen72** [comment]
@alalek thank you so much

**Comment by BitLoose** [comment]
@alalek I'm using VS2015 on Windows, would like to modify and compile the functions such as icvSetCaptureProperty_FFMPEG_p etc., but can't find the source code.  Is it available?

**Comment by alalek** [comment]
It is just [an imported symbols](https://github.com/Itseez/opencv/blob/3.1.0/modules/videoio/src/cap_ffmpeg.cpp#L54) from ffmpeg windows wrapper.
Implementation is [here](https://github.com/Itseez/opencv/blob/3.1.0/modules/videoio/src/cap_ffmpeg_impl.hpp#L1910), but it is not easy to build ffmpeg wrapper (refer to https://github.com/Itseez/opencv_3rdparty/tree/ffmpeg/master/ffmpeg). Also you may try to use approach from this PR description.

**Comment by BitLoose** [comment]
That's a shame, if it was more accesible people would be more able to add to the code.
What's the best way in your opinion to add the audio stream playback?

**Comment by peters** [comment]
@BitLoose It's actually really easy to make changes to the wrapper on Windows. Just grab my project over at https://github.com/peters/opencv.ffmpeg and hit F5.

**Comment by PatriciaReyes** [comment]
@alalek how can I update opencv_ffmpeg.dll for linux?

**Comment by alalek** [comment]
@PatriciaReyes There is no separate opencv_ffmpeg.dll on Linux. To enable ffmpeg support in OpenCV you need to install ffmpeg development packages (-dev/-devel, depends on Linux distribution) and rerun OpenCV CMake

**Comment by PatriciaReyes** [comment]
@alalek Thanks, i'm going to check that to make sure i'm doing it fine... I have this big issue, do you think you could help me with it? [http://stackoverflow.com/questions/36750685/c-suddenly-blocks-on-reading-a-frame-from-ip-camera-using-videocapture/36756653?noredirect=1#comment61124042_36756653]

**Comment by marcassin22** [comment]
@peters I've managed to make your project work but I can't find how to use it with my other projects. Should I just copy the dll's or I need to recompile OpenCV with them?

**Comment by michaildrozdov** [comment]
@peters Even after all these years it saved my day.:)

**Comment by cbasavaraj** [comment]
Hi, does the solution here work even for capturing gstreamer pipelines? For example,
```cv2.VideoCapture("fake ! gstreamer ! pipeline", cv2.CAP_GSTEAMER)```
Thanks

**Comment by lidorshimoni** [comment]
> Hi, does the solution here work even for capturing gstreamer pipelines? For example,
> `cv2.VideoCapture("fake ! gstreamer ! pipeline", cv2.CAP_GSTEAMER)`
> Thanks

did you manage to implement the timeout with gstreamer pipeline?

**Comment by cbasavaraj** [comment]
Hi @lidorshimoni, I found this [workaround](https://stackoverflow.com/questions/38234407/opencv-videocapture-hangs-freeze-when-camera-disconnected-instead-of-returning), and adapted it for my purpose. Happy holidays!

**Pull request merged**
