### PR TITLE
Thrust allocator for temporary storage used with thrust algorithms.

### PR DESCRIPTION
**Pull request by dtmoodie**

### CODE REVIEW

**Comment by alalek** [comment]
I don't see real usage for this.
I believe, in case when it is used in your custom app/library only, there is no problem to add this directly into your code.

@jet47 Does this make any sense?

**Comment by jet47** [comment]
I don't see the usage of newly added class. We have `GpuMat::Allocator` and `BufferPool` classes, can they be used instead?

**Comment by dtmoodie** [comment]
Hi,

The main reason I added this was there are a few places where a thrust algorithm is used inside of an opencv algorithm.  Namely in orb thrust::sort is used.  These thrust algorithms use temporary memory which is causing allocations and deallocations.  By creating a ThrustAllocator class with a similar interface to the GpuMat::Allocator, I can tie the thrust allocations into my memory management.  
This optimization increased the speed of ORB feature matching on 1080P images by 8ms per frame.

I made this a class in the utilities.hpp file with the plan to update all uses of thrust algorithms with this, as well with the hopes that anytime thrust is used later on, that it would be with this allocator.

In theory you could tie the thrust allocator into the BufferPool or GpuMat::Allocator, but neither class can currently be directly passed into a thrust algorithm.  I would have to change the interface for GpuMat::Allocator or BufferPool to have the allocate, deallocate and value_type.  Which would expose __host__ __device__ decorations in the core/cuda.hpp file.  Or I would have to write an interface ThrustAllocator class which gets it's allocations from the current GpuMat::Allocator.

**Comment by dtmoodie** [comment]
Example usage can be found in my fork under the branch thrust_allocator_usage.

**Comment by jet47** [comment]
:+1:

**Pull request merged**
