### PR TITLE
New Java memory mgt doc

### PR DESCRIPTION
**Pull request by sgjava**
This is to document the recent changes I made to the Java bindings memory management.

### CODE REVIEW

**Comment by vpisarev** [comment]
@sgjava, thank for this useful description!
It clarifies the process of managing memory to me. And actually I'm very concerned about this new methodology - I must confess, I did not realize it from the previous PRs from you. So, let's adjust it before 3.0 is out.

Manual memory management in Java, as you said, is unexpected thing and I worry that it yields many, many memory leaks. On the other hand, the proposed way is more efficient of course, so we would like to keep it. So, can we combine those two methods? In other words, if user calls release(), the native object is released immediately and the corresponding field in Java class (nativeObj?) is set to null. And yet finalize() is still used. I believe, it should be doable and this is much more safe.

**Comment by sgjava** [comment]
If you look at the src dir in the build output (opencv/build/src$ grep -R -i "finalize()" .) you will see that finalize() only remains as a comment.  Indeed, finalize() has been totally removed from the generated source. What I've done is rely on Mat.release() which more natural from an OpenCV perspective at least. The new Mat.release() (starting with https://github.com/Itseez/opencv/pull/4014) looks like:

    //
    // C++: void Mat::release()
    //

    // javadoc: Mat::release()
    public void release()
    {

        n_release(nativeObj);
        n_delete(nativeObj);

        return;
    }

Since most OpenCV Java devs are calling release() now, they will not have to modify their code in order to take advantage of immediate native memory release. The only assumption I made was n_delete is doing what it needed to do with nativeObj since the old Mat.finalize() only called n_delete and nothing else (setting to null?).

The other issue was things like VideoCapture which also relied on finalize(). All of these type of objects now have:

    public void delete() {
        delete(nativeObj);
    }

So the main difference is explicit memory management by calling VideoCapture.delete() now instead of relying on implicit finalize().

The last piece to solve is to fix code that creates local Mat (or subclasses) and does not call release(). This is a little harder to track down since I cannot find how this source is generated, For example:

    //
    // C++:  void findContours(Mat& image, vector_vector_Point& contours, Mat& hierarchy, int mode, int method, Point offset = Point())
    //

    //javadoc: findContours(image, contours, hierarchy, mode, method, offset)
    public static void findContours(Mat image, List<MatOfPoint> contours, Mat hierarchy, int mode, int method, Point offset)
    {
        Mat contours_mat = new Mat();
        findContours_0(image.nativeObj, contours_mat.nativeObj, hierarchy.nativeObj, mode, method, offset.x, offset.y);
        Converters.Mat_to_vector_vector_Point(contours_mat, contours);
        contours_mat.release(); // I add this via patching
        return;
    }

findContours leaks on every call due to local Mat creation. Currently I patch this after the source is generated and recompile the Java source. This is described in my install script https://github.com/sgjava/install-opencv. Once I figure out how it's generated I'll get it in master.

**Comment by vpisarev** [comment]
well, this is not a problem with Mat only. This propagates up to all the object that contain Mat's. If Mat should be explicitly released, then the class contaning Mat's should also contain finalize etc. In other words, I consider the strict requirement to call release as too strong and neglecting one of the main Java advantages. I still believe we should put finalize() back. It's no harm to allow both explicit and implicit memory management. If users want to free memory immediately - let's give them Mat.release(). If they do not need that or forgot about it for some reason - let's still give a chance to OS to release the memory properly, sooner or later.

**Comment by sgjava** [comment]
All subclasses of Mat are automatically included since Mat.release() is public. For instance:

public class MatOfPoint2f extends Mat
public class MatOfDouble extends Mat

final MatOfPoint2f cornersProjected = new MatOfPoint2f();
final MatOfDouble distortionCoefficients = new MatOfDouble(distCoeffs);

cornersProjected.release();
distortionCoefficients.release();

I though about adding finalize() back over the weekend, but I keep coming back to the same place. Even if you have both explicit (release()/delete()) and implicit (finalize()) memory management the JVM finalizer queue will still get backed up. This survives through GC cycles and behaves differently for different JVM implementations. To me now I'm being penalized for doing proper memory management because those objects will hang out there in the finalizer queue sometimes forever even though I freed native memory. I know how it behaves because I've been using the Java bindings for a while now and running it through a profiler, Valgrind, etc. There's really no guess work on my part.

Let me put it a different way. When you open a JDBC connection you are required to close it. I see this as no different since JNI is interacting with native code and I cannot always expect it to follow Java's memory management scheme. Plus the fact that you can leak Java memory using 100% Java and run out of heap by not cleaning things up properly, so this really isn't all that unnatural.

**Comment by alalek** [comment]
Any exception will break explicit memory releases and it will be a real memory leak. Only `finalize` can resolve this case, it is the right way to cleanup native resources.

`Memory leaks` is a problem of JVMs and Java design: they don't know about real memory usage of native objects. For JVM it is only few bytes for `native pointer` instead of megabytes of image data, so GC is not started because Java heap is not used.

I believe that both explicit and implicit resource cleanup methods should exist.

Also we can try to have forced GC launches somewhere in the Java Mat constructor (for example, every 10-50-100-200-1000 Mat constructor calls `System.gc()`)

P.S. This article describes some methods how to effecienly manage native objects in Java (+one method without `finalize`, but it requires separate `cleanup` thread): http://www.devx.com/Java/Article/30192/

**Comment by sgjava** [comment]
Exception handling is required for things such as JDBC, sockect, etc., so I see this as no different. If you do not handle exceptions then you can leak resources. As I mentioned before finalize may never be called. I've seen hundreds of thousands of Mats in the finalizer queue with an application that processes millions of images.

Explicit GC is bad practice http://stackoverflow.com/questions/2414105/why-is-it-bad-practice-to-call-system-gc

finalize() is bad practice http://docs.oracle.com/cd/E13188_01/jrockit/docs142/devapp/codeprac.html#998529

Weak references are bad practice http://www.javacodegeeks.com/2012/12/weak-weaker-weakest-harnessing-the-garbage-collector-with-specialist-references.html

If you really want me to add finalize() back in I will, but I'll remove them via patching with my install script since I already know the problems it causes. I'm not trying to be a hard ass here, but I'm adverse to doing things the wrong way unless there's no other choice.

**Comment by sgjava** [comment]
Closing this out. I'll add finalize back in and resubmit modified documentation as separate pull requests.

**Comment by apavlenko** [comment]
Actually before these changes (I mean #4014) there were two options for Java API users: calling `Mat::release()` manually for immediate native memory freeing or leaving objects as is so they are released via `Mat::finalize()` call from the garbage collector. During tutorials on OpenCV Java API we suggested calling `Mat::release()` for more efficient memory management but still made possible ignore this and let the garbage collector do its work.
I strongly suggest reverting the changes made by #4014 before 3.0 release!!!

**Comment by sgjava** [comment]
I think I've demonstrated why it's bad practice to use finalize() because it doesn't work as you guys are describing (some simple research will make this self evident). I've added it back in. Like I said before I'll just strip them out with my install script.

**Pull request closed without merging**
