### PR TITLE
add checks for valid input data given to parameters

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Adding some checks to avoid problems like described here
https://github.com/Itseez/opencv/issues/5104

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@mshabunin or @vpisarev a quick question, does MaxOSX support the use of mkdir command?

**Comment by mshabunin** [comment]
@StevenPuttemans , since MacOSX build is fine, I think this function is supported.

**Comment by StevenPuttemans** [comment]
@mshabunin okay fine! I just updated it a bit this morning, had wrong checks :)

**Comment by alalek** [comment]
:+1:

**Pull request merged**
