### PR TITLE
CvLevMarq: remove fixed rows instead of setting them to zero

### PR DESCRIPTION
**Pull request by paroj**
use the same approach like in fisheye calibration: instead of setting
masked out rows to zero, remove them from the equation system.
This way JtJ does not become singular and we can use the much faster LU
decomposition instead of SVD.

This results in a speedup of the Calibrate unit tests of 3x-10x.

### CODE REVIEW

**Comment by paroj** [comment]
@vpisarev If you just recalled the code, maybe you can also take a look at this one

**Comment by vpisarev** [comment]
@paroj, sorry for delay and thank you for another useful contribution!
The patch looks great, but I do not like that LU method is now used instead of SVD. E.g. camera calibration, where this algorithm is used, is quite important task where the collection of calibration data takes from a few seconds to a few minutes, so if it spends some more time on SVD, it does not matter much as long as the results are better (even slightly better) than in the case of LU. If you want LU as an option, I would suggest to add such an option to the function that matter to you. By default I would still use SVD as the default method.

**Comment by paroj** [comment]
hmm.. did not think about that LU depends on the matrix condition while SVD does not.
However camera calibration is exactly the method that I want to speed up to be able to run it real-time.
For 34 calibration images SVD takes 20s while LU finishes after 460ms. The reprojection error of both is the
same up to the 14th fractional point (difference in 15th). This seems close enough - but is of course not representative.
As I said I got the idea looking at the fisheye calibration code, which also uses LU.
Do you have a testset (in mind) where LU would not work for camera calibration?

**Comment by vpisarev** [comment]
@paroj, I see. I do not have real examples where SVD produces noticeably better results than LU in the case of calibration task. But in the case of many images and when a complex distortion model is used I would like to play safe. So, probably, we can add CALIB_USE_LU flag, which will use LU instead of SVD. What do you think?

**Comment by vpisarev** [comment]
@paroj, excellent, thank you! :+1:

**Pull request merged**
