### PR TITLE
OCL: Fix 4006

### PR DESCRIPTION
**Pull request by alalek**
Replaces #4205

```
check_regression=*Mog2*
```

### CODE REVIEW

**Comment by alalek** [comment]
@vladimir-dudnik @vpisarev Please take a look

**Comment by alalek** [comment]
Mog2 performance goes down by 15-20% on Intel HD4600:
http://ocl.itseez.com/intel/export/perf/pr/4233/report/
Possible reason is forced READ+WRITE access mapping (but it is iGPU, so this penalty is strange). So avoid forced READ+WRITE maps we need more correct mechanics for access rights processing, but currently I have no ideas and no time to fix it.

**Comment by SergeySivolgin** [comment]
There is also small regression (10-15%) for Compare, CornerHarris, WarpPerspectiveNear functions.

**Comment by alalek** [comment]
@SergeySivolgin Reason of these regressions is performance instability (in results of the report above I see that only part of tests is slow down without regularity in parameters)

**Comment by SergeySivolgin** [comment]
OK, I see. Do you think Mog2 regression is a showstopper for this request integration?

**Comment by vpisarev** [comment]
ok, the existing tests pass and you've added some more; let's put it in :+1:

**Pull request merged**
