### PR TITLE
Addition of new functionality to NLM denoising

### PR DESCRIPTION
**Pull request by erikrk**
1) Addition of fastNlMeansDenoisingAbs and fastNlMeansDenoisingMultiAbs which accept both 8-bit and 16-bit input. They use squared sum of absolute value distances instead of sum of squared distances for weight calculation. OpenCL implementation has also been added.
http://code.opencv.org/issues/4143

2) Extension to 4-channel input.

3) Addition of overloaded versions which accept separate h-values, one for each channel.

### CODE REVIEW

**Comment by vpisarev** [comment]
@erikrk, thank you for the contribution! May I ask you about the rationale of the patch? I mean, the NLM method is okay denoising algorithm, not the best one, not the fastest one. With this patch the amount of code implementing just this single algorithm in OpenCV has been increased by an order of magnitude. So I believe there should be some strong reasons to do that.

**Comment by erikrk** [comment]
The main rationale behind working on the NLM implementation is that I am using it myself. As you pointed out NLM is not particularly fast but is does a great job with my data. The current implementation only accepts 8-bit input and uses the same h-value for all channels. Since I needed to process multichannel 16-bit data and use separate h-values per channel I decided to extend the implementation. The OpenCL implementation is also limited to 1-2 channels and the C++ implementation is limited to 1-3 channels. I have extended both of them so they accept 1-4 channels.

This necessitated an extensive refactoring since the current implementation is hard-coded for 8-bit input. Additional code had too be written too, particularly in modules/photo/src/denoising.cpp and modules/photo/src/fast_nlmeans_denoising_invoker_commons.hpp to handle the new combinations of bit depth and number of channels. The files implementing the algorithm itself, modules/photo/src/fast_nlmeans_denoising_invoker.hpp and modules/photo/src/fast_nlmeans_multi_denoising_invoker.hpp have not been extensively modified though.

16-bit/channel data is becoming more and more common and I think that an implementation that only accepts 8-bit input is eventually going to become of limited value. This has also been requested in the above-mentioned issue.

**Comment by erikrk** [comment]
Just to put things into perspective, there are currently 2394 lines implementing NLM in OpenCV and after application of the patch there are 3236 lines (in cuda/nlm.cu, opencl/nlmeans.cl, denoising.cpp, denoising.cuda.cpp,  fast_nlmeans_denoising_invoker.hpp, fast_nlmeans_denoising_invoker_commons.hpp, fast_nlmeans_denoising_opencl.hpp, fast_nlmeans_multi_denoising_invoker.hpp, and opencv2/photo.hpp). That's a 35 % increase. I don't really see how this becomes an order of magnitude.

**Comment by vpisarev** [comment]
@erikrk, that's right, increase of the source code size is not severe (but still ~35%). I was mainly talking about the binary size increase, which is something like 800%.

1) Since separate h value for each channel is extension of a single h value for all channels, can we completely replace the old version with the new one?
2) what's the reason to have 4-channel denoising? if it's mostly for convenience, probably it makes sense to extract the first 3 channels, do the denoising and then put the original alpha channel back. The extra operations are very cheap, comparing to the denoising time.

can we make the norm type (L2/L1) an additional function parameter? Otherwise there is too many similar external functions.

**Comment by erikrk** [comment]
The external interface has definitely become too complicated. The main reason behind this is that I have tried to maintain full backwards compatibility, both source-wise and binary-wise. If maintaining source compatibility is sufficient, adding the norm type as a parameter with a default value should work just fine.

The main reason for extending to 4 channels is that vector sizes in OpenCL have to be powers of 2. There are 3-component vectors though, but they occupy the same space in memory as 4-component vectors. 3-channel images thus have to be padded up to 4 channels for the OpenCL implementation to work. Consequently, processing of 4-channel images comes with little additional cost. I then decided to the extend the C++ implementation to 4 channels also in order to make it possible to run test cases which compare the OpenCV implementation to the C++ implementation.

The reason for the increase in binary size is that templates are used to generate separate codes for various different cases. This is done for reasons of speed and has not been introduced with this patch. The number of different cases has simply increased substantially. One thing that could be be done if binary size is a concern is to remove the implementations that use a single h-value for all channels. That might affect speed negatively though. If the size of denoising.cpp.o itself is a concern, it could be split up in two, with one file for fastNlMeansDenoising/fastNlMeansDenoisingColored and one for fastNlMeansDenoisingMulti/fastNlMeansDenoisingColoredMulti. That would reduce the size of statically linked binaries that use only one of those two.

**Comment by erikrk** [comment]
I have removed fastNlMeansDenoisingAbs and fastNlMeansDenoisingMultiAbs. Instead I have added a new parameter, normType, which can be either NORM_L2 or NORM_L1, to fastNlMeansDenoising and fastNlMeansDenoisingMulti. Binary compatibility is maintained since the new parameter has only been added to the new overloaded variants that take std::vector<float>const& h.

**Comment by vpisarev** [comment]
@erikrk, the latest variant looks great! thank you! :+1:

**Pull request merged**
