### PR TITLE
initialize temp_train_samples in SVM::autoTrain

### PR DESCRIPTION
**Pull request by berak**
fix for issue #5369

### CODE REVIEW

**Comment by alalek** [comment]
BTW, There was related fix in #3909

**Comment by berak** [comment]
@alalek , oh, thanks, i did not see that before, but imho, #3909 is doing the wrong thing

also, the [test](https://github.com/Itseez/opencv/blob/master/modules/ml/test/test_svmtrainauto.cpp#L76) would even pass with a plain train() with default params.

shouldn't the test data be a bit more 'edgy' , to prove, that it trainAuto() actually improves prediction ?

**Comment by alalek** [comment]
@berak Yes, It will be nice to have simple regression test for bugfix (test should fail without patch, and pass with bugfix patch).

**Comment by berak** [comment]
@alalek , magic indeed ;) , thanks for helping out again. (i only tried to vary test_data points)

should it be appended (separately) to test_svmtrainauto.cpp ? 
or should the existing CV_SVMTrainAutoTest::run() get changed ?

**Comment by alalek** [comment]
Lets add new test and leave existed smoke test with guaranteed result as is.

**Comment by alalek** [comment]
Thanks! :+1:

**Pull request merged**
