### PR TITLE
tutorials directory correction

### PR DESCRIPTION
**Pull request by IshankGulati**
Issue #5823

### CODE REVIEW

**Comment by sturkmen72** [comment]
you should change documentation files see https://github.com/Itseez/opencv/tree/master/doc/tutorials/highgui

**Comment by IshankGulati** [comment]
@sturkmen72  should i move video-input and video-write documentation to videoio folder?

**Comment by IshankGulati** [comment]
@sturkmen72  I have moved tutorials of video-input and video-write to a new (videoio) folder. Is this correct or should I move them to some other directory?

**Comment by mshabunin** [comment]
@IshankGulati , some tutorials contain references to the files you moved and they should be fixed too. I think that the whole [highgui](http://docs.opencv.org/master/d0/de2/tutorial_table_of_content_highgui.html) tutorial section should be reorganized to reflect modules changes in 3.x series.

**Comment by IshankGulati** [comment]
@mshabunin I have made the required changes. Please review.

**Comment by mshabunin** [comment]
Thank you, @IshankGulati and sorry for delay. I've moved your changes to #6105 with several additions.

**Comment by IshankGulati** [comment]
@mshabunin you're welcome :)

**Pull request closed without merging**
