### PR TITLE
bugfix_for_hog_detectMultiScale_with_weights

### PR DESCRIPTION
**Pull request by zjulujia**
bugfix_for_hog_detectMultiScale_with_weights

issue : http://code.opencv.org/issues/4284

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
:+1:  Seems good! Now lets wait and see if all buildbots pass safely.

**Comment by StevenPuttemans** [comment]
Btw it seems that the same bug is vivid in master branch. Take a look at this file: https://github.com/Itseez/opencv/blob/master/modules/objdetect/src/hog.cpp. I would suggest adding an extra PR for the master branch and adding the `weights.clear();` after each `hits.clear();` statement. 

You up for it?

**Comment by zjulujia** [comment]
yes, I do think that each weights.clear() should be added after hits.clear(), and also for the master branch.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
