### PR TITLE
Reduce variables scope

### PR DESCRIPTION
**Pull request by Dmitry-Me**
These minor defects were found with Cppcheck

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
@Dmitry-Me, would not it be better to make much more changes and make a big pull-request with a bunch of changes than commit and send us every changed line?

**Comment by Dmitry-Me** [comment]
@ilya-lavrenov That would require more effort from reviewers. We're not rushing anywhere, are we?

**Comment by vpisarev** [comment]
@Dmitry-Me, first of all, I would like to thank you for all the great work that you do with polishing opencv source code.
On the other hand, I would like to support @ilya-lavrenov suggestion. In fact, each single PR is extra press on our quite limited computational resources (for each patch, even tiny one, the library is build from scratch on several platforms and all the tests are run). And also it's some overhead, because reviewing 1 PR consisting of 10-20 small changes is nearly the same as reviewing 1 PR with a single small change.  We do not have a team of reviewers who spend 100% of their time on PRs, it's an extra activity added to our fulltime development job. Of course, it would be a bad practice if you come up with a huge pull request touching hundreds of files; as you said, it would be difficult to review. But it will be easier for us to review some more complex PRs from you. Thank you for understanding.

**Comment by vpisarev** [comment]
btw, in this particular case - why don't you put "int i" inside the for loop?

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
