### PR TITLE
Add CMake option to build tiny version of gpu module

### PR DESCRIPTION
**Pull request by jet47**
This tiny version of gpu module will support only `uchar`  and `float` image formats and will have limitations for some functions (like border modes, window sizes, etc.)

### CODE REVIEW

**Comment by jet47** [comment]
@asmorkalov Please review.

**Comment by jet47** [comment]
@asmorkalov I fixed tests in tiny mode, now the PR is finished.

**Comment by ilya-lavrenov** [comment]
@jet47, please, fix compilation errors in tests http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/2412/steps/compile%20release/logs/stdio

**Comment by jet47** [comment]
Updated.

**Comment by vpisarev** [comment]
@asmorkalov, this is big patch that waits for a long time. Should we integrate it finally?

**Comment by asmorkalov** [comment]
:+1:

**Pull request merged**
