### PR TITLE
fixing tutorial errors master branch

### PR DESCRIPTION
**Pull request by StevenPuttemans**
as described in http://code.opencv.org/issues/4154

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Weird. If I look at documentation

http://docs.opencv.org/trunk/doc/tutorials/imgproc/histograms/template_matching/template_matching.html#template-matching

Then you can see that the code at glance contains the error. But if i look at the file that should be loaded (samples/cpp/tutorial_code/Histograms_Matching/MatchTemplate_Demo.cpp) than the fix is already applied there. Someone has an idea how this is possible?

**Comment by mshabunin** [comment]
@StevenPuttemans, old [sphinx documentation](http://docs.opencv.org/trunk) (last generated on 30 Dec 2014) contained copy of the source file in the rst file: [like this](https://raw.githubusercontent.com/Itseez/opencv/055adc2302c3a2ac6f13c77b071fd160a05035ff/doc/tutorials/imgproc/histograms/template_matching/template_matching.rst).
The new [doxygen documentation](http://docs.opencv.org/ref/master) takes same source block from original `.cpp` file, thus fixing the source ([earlier](https://github.com/Itseez/opencv/commit/055adc2302c3a2ac6f13c77b071fd160a05035ff)) has fixed the docs.

It is better to use `snippet` command to include small marked code blocks from same source file if possible. 
Some details:
- [OpenCV documenting guide](http://docs.opencv.org/ref/master/d4/db1/tutorial_documentation.html#tutorial_documentation_commands_include)
- [Doxygen command reference](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsnippet)

**Comment by StevenPuttemans** [comment]
So I should change this to use the snippet command or was it just an explanation on your side?

**Comment by mshabunin** [comment]
No, additional changes are not necessary, your fix is good too. :smile:

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
