### PR TITLE
Removed ioctl calls to query for VIDIOC_G_INPUT and VIDIOC_ENUMINPUT …

### PR DESCRIPTION
**Pull request by terfendail**
* Removed ioctl calls to query for VIDIOC_G_INPUT and VIDIOC_ENUMINPUT since information returned by the calls is never used while call failure make impossible to open the camera even if it works.
* Fixed icvCaptureFromCAM_V4L return value in case of V4L2 camera initialization failure.

### CODE REVIEW

**Comment by terfendail** [comment]
@asmorkalov please review

**Comment by asmorkalov** [comment]
Looks ok for me :+1:

**Comment by asmorkalov** [comment]
@vpisarev please look at it.

**Comment by alalek** [comment]
This line can be removed also:
https://github.com/Itseez/opencv/blob/2.4.12/modules/highgui/src/cap_v4l.cpp#L320

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
