### PR TITLE
Fix run.py test detection issues for debug VS configurations

### PR DESCRIPTION
**Pull request by mshabunin**
Could not find CMAKE_BUILD_TYPE in CMakeCache, also added more aliases for debug executables (with `d` suffix).

### CODE REVIEW

**Comment by alalek** [comment]
bioinspired, features2d, xfeatures2d are valid test names, they should not lost `d`.

**Comment by alalek** [comment]
Problem is still here: http://pullrequest.opencv.org/buildbot/builders/precommit_linux64_no_opt/builds/2656
1) see tests_accuracy properties
2) missed features2d tests

**Comment by mshabunin** [comment]
@alalek , I've fixed this issue.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
