### PR TITLE
Added New Sample: Stereo Camera Calibration in Real Time

### PR DESCRIPTION
**Pull request by upperwal**
Captures images in real time by detecting chessboard corners and
calibrate the stereo camera after that.

Keyboard Shortcuts:

Initial Mode: Detecting (Chessboard Corners)
'c': Capturing (Start capturing the stereo images)
'p' Calibrate (Once all the images are captured, calibration can start by pressing 'p')

### CODE REVIEW

**Comment by upperwal** [comment]
@vpisarev hey! Any update? I have been eagerly waiting for this pr to get merged.

**Comment by StevenPuttemans** [comment]
@upperwal it seemed that @vpisarev was on holidays until 1 or 2 days ago. He has been back and is graduatly merging pull requests. Just wait a little bit more! I am sure it will get merged since it is a nice addition.

**Comment by StevenPuttemans** [comment]
Also, please merge both commits, else this will not get accepted!

**Comment by upperwal** [comment]
Thanks for replying @StevenPuttemans :) and I will definitely merge both the commits asap. :D

**Comment by vpisarev** [comment]
Hello @upperwal, terribly sorry for long response. I would prefer if this sample will be combined with the offline stereo_calib. We are trying to cleanup OpenCV samples, remove duplicates or close variations, so it would be nice if we have a single calibration sample. This may be difficult, then I'd prefer that at least monocular camera calibration and stereo calibration are 2 samples, not 3 or more.

**Comment by upperwal** [comment]
Hey @vpisarev, thanks for replying and don't be sorry, I know you guys are very busy. OpenCV samples contain 3 type of calibration files 3calibration.cpp, calibration.cpp and stereo_calib.cpp. Are you suggesting to merge all these samples into one? As my sample is an extension to stereo_calib.cpp (which calibrate using pre saved stereo images, where as my code works on the live video feed) Will it be fine to merge these two samples and let the user decide which method to use?

**Comment by vpisarev** [comment]
@upperwal, yes, I meant merging your sample and stereo_calib.cpp. 3calibration.cpp can probably be removed and we plan to extend calibration.cpp. So, there is no need to merge everything together, just retaining a single stereo calibration sample would be good enough solution for now.

**Comment by upperwal** [comment]
:+1: got that. Will try to merge my sample with stereo_calib.cpp and then I will get back to you. Thanks :)

**Comment by upperwal** [comment]
@vpisarev @StevenPuttemans 
What from the following is advisable, to load stereo images in the program:
1. Maintain a images name file (such as images.yml) from which name of an image is read and that string is used in imread().
2. Ask the user to give a folder, image prefix (Ex: "image_left_", "image_right_"), image post fix (Ex: "jpg") and no of images and iterate using image prefix+i+image post fix to read the images. Given image are image_left_1.jpg, image_right_1.jpg etc.

I am sorry if this is a lame question, but I came across the first method in almost all samples and according to me the second one is more efficient to do. (user does not need to create a file for the name of the images). Please correct me, if I am wrong.
Thanks

**Comment by StevenPuttemans** [comment]
@upperwal it kind of depends I guess. Since you are building the sample, you can choose the method you like. The reason why people use a name file with locations, is because reading files is universal in different OS. Reading from a folder gives different sequences since ordering is different on several OS.

But hey, you choose what fits you the best!

**Comment by upperwal** [comment]
Thanks @StevenPuttemans :+1: I used the second method for the time being. To have a single sample for stereo calibration I have merged stereo_calib with my sample. The sample can now work on already saved stereo images or click the images on the go.

**Comment by StevenPuttemans** [comment]
Great :+1:

**Comment by StevenPuttemans** [comment]
Could you also use your PR to delete the double samples?

**Comment by upperwal** [comment]
@StevenPuttemans As stereo_calib is updated, there are two calibration samples left. 1. "3calibration.cpp" and 2. "calibration.cpp". So "3calibration.cpp" should be deleted as suggested by @vpisarev as "calibration.cpp" is used for single camera calibration. Correct?

**Comment by upperwal** [comment]
@vpisarev hi. Can you please review the code?

**Comment by StevenPuttemans** [comment]
@upperwal I know it is taking some time, but please be patient, I have the idea that some of the devs are on holidays or taking a break :)

**Comment by upperwal** [comment]
:+1: @StevenPuttemans

**Comment by upperwal** [comment]
Thanks @StevenPuttemans. You are a great support :+1:  :)

**Comment by askerpro** [comment]
got an error with imread
cv::imwrite could not find a writer for the specified extension
                //std::ostringstream leftString, rightString;
		//leftString << dir << "/" << prefixLeft << pairIndex << postfix;
	        //rightString << dir << "/" << prefixRight << pairIndex << postfix;
		std::string leftString = dir + "/" + prefixLeft + to_string(pairIndex) + "." + postfix;
		std::string rightString = dir + "/" + prefixRight + to_string(pairIndex) + "." + postfix;
		imwrite(leftString, leftImage);
		imwrite(rightString, rightImage);
works with this

**Comment by upperwal** [comment]
@askerpro :+1: will fix it ASAP. Thanks :)

**Comment by StevenPuttemans** [comment]
@upperwal I do not think you should close it down. Just update this branch?

**Comment by upperwal** [comment]
Hey @StevenPuttemans This PR already have 9 commits, I was thinking of creating a new PR after resolving the merge conflict and incorporating the above suggestion. Will that be fine?

**Comment by StevenPuttemans** [comment]
@upperwal there is a very nice tool in git called `git rebase -i HEAD~9` (change number accordingly) which allows you to concatenate commits and make it a clean PR again. No needc in making a new branch for the fixes!

**Comment by upperwal** [comment]
@StevenPuttemans Very well then. Let me try it and reopen this PR. Thanks Steven. :)

**Comment by upperwal** [comment]
Sorry @StevenPuttemans I tried using rebase but it was all messed up and then I did a force push to my repo. I think, now I need to create a new PR for this.

**Comment by StevenPuttemans** [comment]
Ok no problem at least you tried :D

**Comment by upperwal** [comment]
:) Thanks @StevenPuttemans

**Pull request closed without merging**
