### PR TITLE
Fixed inverse cv::linearPolar transform missing-patch-in-output bug.

### PR DESCRIPTION
**Pull request by Aravind-Suresh**
Fixes https://github.com/Itseez/opencv/issues/5764.

### CODE REVIEW

**Comment by Aravind-Suresh** [comment]
I am getting an error like:  ` remoteFailed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
] `. I think it is not related to patch. Should I do anything to fix it?

**Comment by Aravind-Suresh** [comment]
I am getting an error ( buildbot ) like: 
`command timed out: 180 seconds without output running buildenv python ../opencv/modules/ts/misc/run.py --gtest_output=xml:results_perf_stitching.xml -t stitching --check --perf_impl=plain, attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=196.235178`

Please help me in fixing it. I think rebuilding will solve the problem.

**Comment by Aravind-Suresh** [comment]
Please restart the iOS build as it says `not_queued` for a long time. Thanks :)

**Comment by Aravind-Suresh** [comment]
Please let me know if this is correct.

**Comment by Aravind-Suresh** [comment]
@alalek Yeah I get your point. Any ideas on how to proceed? I have gone through the source code many times and tried whatever possible.

**Comment by alalek** [comment]
There is a problem with gap between 360 and 0 degrees. I added border (wrap mode) to resolve this.
Replaced by #6206

**Pull request closed without merging**
