### PR TITLE
videoio: VideoWriter H264/.mp4 support via ffmpeg

### PR DESCRIPTION
**Pull request by alalek**

### CODE REVIEW

**Comment by vpisarev** [comment]
:+1:

**Comment by PhilLab** [comment]
Awesome! Is mp4 writing possible out-of-the-box with the included ffmpeg dll (https://github.com/Itseez/opencv/tree/master/3rdparty/ffmpeg) ?

**Comment by alalek** [comment]
@PhilLab Right, Windows is not fixed (only mp4 reading is available): ffmpeg wrapper dll should be rebuilded.

**Comment by PhilLab** [comment]
@alalek oh, do you know if it is planned for 3.0 ? Would be of value, e.g. for smartphone compatibility or HTML5 compatibility

**Pull request merged**
