### PR TITLE
XML file path correction

### PR DESCRIPTION
**Pull request by enesates**
in documentation exact path is images/CameraCalibration/VID5

### CODE REVIEW

**Comment by mshabunin** [comment]
Probably the file `VID5.xml` in the same folder should be fixed too.

**Comment by enesates** [comment]
just the documentation says in here: http://docs.opencv.org/doc/tutorials/calib3d/camera_calibration/camera_calibration.html#results

**Comment by enesates** [comment]
and default.xml file in the project main folder give reference to this path:
http://docs.opencv.org/_downloads/in_VID5.xml

**Comment by mshabunin** [comment]
There is also reference to `VID.xml`, in sentence:
>Here’s an example of this.

Please, note that you have modified documentation on _master_ branch, and corresponding tutorial link is: http://docs.opencv.org/master/d4/d94/tutorial_camera_calibration.html
But you are referring to the 2.4.11 documentation located on the site root: http://docs.opencv.org/doc/tutorials/calib3d/camera_calibration/camera_calibration.html
If you want to change it you should also create analogous PR for the _2.4_ branch.

**Comment by enesates** [comment]
Thank you @mshabunin . I have created for the 2.4 branch.

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
