### PR TITLE
add fixed video

### PR DESCRIPTION
**Pull request by StevenPuttemans**
resolves https://github.com/Itseez/opencv/issues/6429 for 2.4 branch

BACKPORT

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@alalek Could you check this backport also?

**Comment by alalek** [comment]
@StevenPuttemans Could you please replace video from here (same codec and without audio stream): https://github.com/Itseez/opencv/files/225814/tree.avi.zip
Thanks!

**Comment by StevenPuttemans** [comment]
@alalek there you go!

**Comment by alalek** [comment]
:+1:

**Pull request merged**
