### PR TITLE
Fix issue #5234

### PR DESCRIPTION
**Pull request by philippefoubert**
UMat::convertTo when noScale

### CODE REVIEW

**Comment by philippefoubert** [comment]
PR #5235 created.

**Comment by ilya-lavrenov** [comment]
Please, also modify the tests in core/tests/ocl as
* From 
```
OCL_TEST_P(ConvertTo, Accuracy)
{
    for (int j = 0; j < test_loop_times; j++)
    {
        generateTestData();

        double alpha = randomDouble(-4, 4), beta = randomDouble(-4, 4);

        OCL_OFF(src_roi.convertTo(dst_roi, dstType, alpha, beta));
        OCL_ON(usrc_roi.convertTo(udst_roi, dstType, alpha, beta));

        double eps = CV_MAT_DEPTH(dstType) >= CV_32F ? 2e-4 : 1;
        OCL_EXPECT_MATS_NEAR(dst, eps);
    }
}
```
* To
```
OCL_TEST_P(ConvertTo, WithScale_Accuracy)
{
    for (int j = 0; j < test_loop_times; j++)
    {
        generateTestData();

        double alpha = randomDouble(-4, 4), beta = randomDouble(-4, 4);

        OCL_OFF(src_roi.convertTo(dst_roi, dstType, alpha, beta));
        OCL_ON(usrc_roi.convertTo(udst_roi, dstType, alpha, beta));

        double eps = CV_MAT_DEPTH(dstType) >= CV_32F ? 2e-4 : 1;
        OCL_EXPECT_MATS_NEAR(dst, eps);
    }
}

OCL_TEST_P(ConvertTo, NoScale_Accuracy)
{
    for (int j = 0; j < test_loop_times; j++)
    {
        generateTestData();
    
        OCL_OFF(src_roi.convertTo(dst_roi, dstType, 1, 0));
        OCL_ON(usrc_roi.convertTo(udst_roi, dstType, 1, 0));
        
        double eps = CV_MAT_DEPTH(dstType) >= CV_32F ? 2e-4 : 1;
        OCL_EXPECT_MATS_NEAR(dst, eps);
    }
}
```

**Comment by philippefoubert** [comment]
@ilya-lavrenov, can you merge it ? I don't have write access to the repository.

**Comment by ilya-lavrenov** [comment]
I don't have such access too.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
