### PR TITLE
Py-tutorial docs function error

### PR DESCRIPTION
**Pull request by markroxor**
In the function cv2.kmeans(z,2,None,criteria,10,flags). The third parameter should be criteria, not "None".
This function was not working in my local machine with the given parameters.

### CODE REVIEW

**Comment by vpisarev** [comment]
@markroxor, do you use OpenCV 3?
my kmeans gives this:
<pre>
>>> import cv2
>>> cv2.kmeans.__doc__
'kmeans(data, K, bestLabels, criteria, attempts, flags[, centers]) -> retval, bestLabels, centers'
</pre>
i.e. criteria if 4-th parameter, not the 3-rd

**Comment by markroxor** [comment]
I used opencv 2. Let me post the screenshots in a minute.

**Comment by markroxor** [comment]
screenshot from 2016-03-27 14 05 34

"TypeError: an integer is required"

**Comment by vpisarev** [comment]
no need to supply screenshots. master branch is for OpenCV 3.x. If you are using OpenCV 2.4.x, use the branch 2.4

**Pull request closed without merging**
