### PR TITLE
Fixing typo; ts cannot be internal

### PR DESCRIPTION
**Pull request by BKNio**
@mshabunin  Fixing typo; ts cannot be internal

### CODE REVIEW

**Comment by alalek** [comment]
If you really need this you can try to introduce some cmake flag for this.
IMHO, OpenCV test system is not a part of public OpenCV API, it is not same as regular module like opencv_imgproc, so it should not be packaged for users.

**Comment by BKNio** [comment]
As I know it always be public. Since when it is not part of public packages? Since 3.0?

**Comment by ilya-lavrenov** [comment]
> IMHO, OpenCV test system is not a part of public OpenCV API

But it should be! It's very useful when users implement their OpenCV benchmarks using built-in TS module!

**Comment by mshabunin** [comment]
To make _ts_ module public we need to hide gtest symbols somehow to avoid conflicts with external gtest library. Please, see related issue: http://code.opencv.org/issues/3225

**Comment by mshabunin** [comment]
I'd suggest the following: leave _ts_ module marked as INTERNAL __but__ install headers and libraries for internal modules. This will remove _ts_ from the list of public modules but it will be still available. 
- Users who want to link with _ts_ will need to state it explicitly: `target_link_libraries(myapp ${OpenCV_LIBS} opencv_ts)`.
- Other users will not have conflicts when linking with external gtest library like this: `target_link_libraries(myapp ${OpenCV_LIBS} ${GTEST_LIB})`.
- Same scheme will work for pkg-config users.

Another way is to have cmake option which would enable installation of internal modules: `OPENCV_INSTALL_INTERNAL_MODULES`, and will be turned off by default.

These methods can also help us to avoid several hacks in cmake scripts:
##### OpenCVConfig.cmake.in
```.cmake
  if(GTest_FOUND OR GTEST_FOUND)
    list(REMOVE_ITEM OpenCV_FIND_COMPONENTS opencv_ts)
  endif()
```
##### OpenCVUtils.cmake
```.cmake
  if (NOT CMAKE_VERSION VERSION_LESS "2.8.8"
      AND NOT OPENCV_MODULE_${target}_CHILDREN
      AND NOT OPENCV_MODULE_${target}_CLASS STREQUAL "BINDINGS"
      AND NOT ${target} STREQUAL "opencv_ts"
    )
```
##### OpenCVGenABI.cmake
```.cmake
set(modules "${OPENCV_MODULES_PUBLIC}")
ocv_list_filterout(modules "opencv_ts")
```

**Comment by BKNio** [comment]
Can we leave ts as a part of public API, but make it OFF by default?

**Comment by mshabunin** [comment]
@BKNio, I don't think, it is a good solution as it will affect many users who get used to have tests built by default.

I have one more question: how did you use _ts_ module when there were no _cvconfig.h_ file included to the installation set (it has been added only two-three weeks ago)?

https://github.com/Itseez/opencv/blob/master/modules/ts/include/opencv2/ts.hpp#L7

**Comment by vpisarev** [comment]
if I remember correctly, the only difference between internal modules and not is that internal modules are not installed with "make install", right? If yes, than it's not particularly important. "make install" is not recommended to do with opencv anyway. Use cmake for your apps, tests, or rather modularize your code and put the processing part into opencv-like module, add the path to parent directory of your module directory in OPENCV_EXTRA_MODULES_PATH and you are done - you will have ts available to your tests.

**Comment by vpisarev** [comment]
I'd actually suggest _not_ to add new flags to our cmake scripts. We already much more configuration flags in OpenCV than we should have. Remember, with each single configuration flag added we double the number of possible configurations. It's already probably millions of combinations. Do we really need this much flexibility? I build opencv with default flags most of the time, even though I would make static build the default option.

**Comment by BKNio** [comment]
@mshabunin removes broken include
@vpisarev 
>Use cmake for your apps, tests

You mean manually specify ts's include and libs from build? Well, I think it is in some way inconvenient, but if OpenCV guys decided to make ts internal - ok then

**Comment by alalek** [comment]
@BKNio No, Vadim's suggestion is to make your app as OpenCV module (see opencv_contrib) and use all things (include ts) from OpenCV build. But this will propagate all existed/possible problems from OpenCV build system. (I don't recommend do this).

**Pull request closed without merging**
