### PR TITLE
Bug in SVM::trainAuto

### PR DESCRIPTION
**Pull request by Nuzhny007**

### CODE REVIEW

**Comment by vpisarev** [comment]
@Nuzhny007, thanks! Can you please squash 4 commits into a single one?

**Comment by Nuzhny007** [comment]
How can I it do?
I do in terminal: git rebase -i HEAD~3
And...

**Comment by alalek** [comment]
Try this:
git fetch <Itseez/opencv remote name>
git rebase -i <Itseez/opencv remote name>/master

For example:
git fetch origin
git rebase -i origin/master

**Comment by vpisarev** [comment]
@Nuzhny007, maybe it makes sense for simplicity close this PR and submit new one from a fresh branch with just that one line changed?

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
