### PR TITLE
camera view was enabled to visible when the app launched

### PR DESCRIPTION
**Pull request by qubick**

### CODE REVIEW

**Comment by alalek** [comment]
Use spaces instead of tabs

**Comment by qubick** [comment]
0) When this sample is ran, the view is not visible - showing only white screen surfaceview it is not visible.
1) Will do
2) added, but not committed. will also push the change.

**Comment by alalek** [comment]
It is very strange. Could you add some information about your Android version / device?

**Comment by qubick** [comment]
Device: GT-I9500
Android Studio, API 23: Android 6.0 (Marshmallow)

**Comment by alalek** [comment]
Thanks! Looks like it is related to new behaviour of Android 6.0.
This patch works fine with Android 4.3 (doesn't break anything).
:+1:

**Comment by qubick** [comment]
Awesome! Thanks for reviewing

**Pull request merged**
