### PR TITLE
Update cascadeclassifier.cpp

### PR DESCRIPTION
**Pull request by teng88**
minor fix since predict() returun int

### CODE REVIEW

**Comment by teng88** [comment]
could u plz have a look at this @StevenPuttemans

**Comment by StevenPuttemans** [comment]
@teng88 this seems indeed correct. Could you also adapt the following line, where the same mistake happens: https://github.com/Itseez/opencv/blob/master/apps/traincascade/cascadeclassifier.cpp#L294

It is inside the iterative prediction function.

**Comment by StevenPuttemans** [comment]
Forget my remark about the second predict. This is not the case since this is the function of the internal boosting function.

**Comment by teng88** [comment]
Ya, thx

**Comment by StevenPuttemans** [comment]
BTW could you apply the same fix to the master branch?

**Comment by teng88** [comment]
done for branch 2.4

**Comment by StevenPuttemans** [comment]
:+1: THANKS!

**Comment by vpisarev** [comment]
Semantically, the patch does not change anything. Why is it needed?

**Comment by StevenPuttemans** [comment]
Because it is just inconsistent. The output of the function is an integer, so why compare it to an explicit float? Besides the fact that we want indeed only needed patches, we should also strive for clearability and readable/understandable code.

**Comment by teng88** [comment]
@vpisarev what's your opinion?

**Comment by vpisarev** [comment]
ok, it's not principal, actually, but let's put it in :+1:

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by teng88** [comment]
:+1:

**Pull request merged**
