### PR TITLE
Binary storage for OpenCV data structures.

### PR DESCRIPTION
**Pull request by asolis**
Useful when file size is more relevant than file readability.
It follows a similar design to the FileStorage class.

Use the following procedure to write something to a binary file:
 -# Create new BFileStorage and open it for writing.
 -# Write all the data you want using the streaming operator `<<`, just like in the case of STL
 streams.
 -# Close the file using BFileStorage::release. BFileStorage destructor also closes the file.

 Use the following procedure to read something from a binary file:
 -#  Open the file storage using BFileStorage constructor.
 -#  Read the data you are interested in sequentially in the same order it was written.
 Use the operator `>>`, just like in the case of STL streams
 -#  Close the storage using BFileStorage::release. BFileStorage destructor also closes the file.

 To write/read your own data structures you need to implement two functions:

 static void writeB(std::ostream &f, const YOURTYPE &example);
 static void readB(std::istream &f, YOURTYPE &example);

Example:
```C++
#include <vector>
#include "opencv2/opencv.hpp"

using namespace std;
using namespace cv;

class B
{
private:
    vector<float> _vec;
    float _float;
    int _int;
    Mat _mat;

public:
    void write(ostream &f) const
    {
        cv::writeB(f, _vec);
        cv::writeB(f, _float);
        cv::writeB(f, _int);
        cv::writeB(f, _mat);
    }
    void read(istream &f)
    {
        cv::readB(f, _vec);
        cv::readB(f, _float);
        cv::readB(f, _int);
        cv::readB(f, _mat);
    }
};

static void writeB(std::ostream &f, const B &example)
{
    example.write(f);
}
static void readB(std::istream &f, B &example)
{
    example.read(f);
}


int main(int , char**)
{
    string filename = "file.bin";
    B writeExample;

    BFileStorage bfs(filename, BFileStorage::Mode::WRITE);
    bfs << writeExample;
    bfs.release();

    B readExample;
    BFileStorage bfs2(filename, BFileStorage::Mode::READ);
    bfs2 >> readExample;
    bfs2.release();
}
```

### CODE REVIEW

**Comment by alalek** [comment]
What is about HDF5?

I believe, access interface should be unified with existed FileStorage

**Comment by asolis** [comment]
@alalek: Yes, HDF5 could be another nice extension. Definitely more elaborated that this simple "serialization" alternative.  What would be your suggestion to unified the current implementation with the existing FileStorage?
Also, first time submitting to OpenCV and trying to understand  the build checks, I am getting some errors that I am not completely sure belongs to my code additions....

**Comment by alalek** [comment]
I mean to reuse existed interfaces of FileStorage/FileNode/etc:
- read transparently, from files/memory of both formats: current plain text and some binary format without additional options
- write data files via specifying of some additional "BINARY" flag somehow
- there are a lot of OpenCV parts uses FileStorage (one of important part is cv::Algorithm), so preserving existed interfaces are good.

BTW, FileStorage had been developed a long time ago via migration from "C" interface, so I'm not sure, that it is very easy to extent it without significant refactoring.

Some of build failures are not related to this patch. I restarted them

**Comment by asolis** [comment]
Thanks. I will have a look at it and see what I can do about it.

**Comment by asolis** [comment]
Hello @alalek, 
I ended up implementing all the binary FileStorage using HDF5 :) The hierarchical format was necessary to keep the the same 'reading interface' .  As of this moment is using the same FileStorage/FileNode interfaces but I need some guidance/help to include/link HDF5 into the OpenCV project. 


If you would like to have a look at the code you could check it [here](https://github.com/asolis/binaryStorage). I am using class names such as Storage (i.e. FileStorage), StorageNode (i.e. FileNode), and NodeIterator (i.e. FileNodeIterator) to avoid name collitions. I checked the implementation with the xml/yml example of FileStorage available in the OpenCV documentation (i.e. included in the project) and it works great.

**Comment by asolis** [comment]
Hello @alalek, 
Is it there any doc/guide how to add a 3rd party library to the OpenCV cmakes? I want to add HDF5 so I can submit a PR with the new implementation. 
Thanks

**Comment by cbalint13** [comment]
@asolis ,

There is already one HDF5 starting with 3.1.0 opencv_contrib:

http://docs.opencv.org/trunk/d6/dee/group__hdf5.html#gsc.tab=0
http://docs.opencv.org/trunk/d3/d23/classcv_1_1hdf_1_1HDF5.html#gsc.tab=0

I believe is decent enough to cover all needs. Soon will work on the fly when Mat is non-continuous too.

**Comment by vpisarev** [comment]
@asolis, I like the idea, but don't quite like the implementation. The major problems with the proposed file storage are:
1. it can only contain flat sequences of scalars, but not sequences or maps.
2. it does not contain information about the stored types, and thus it's very unsafe. For example, you can write an array of float's and then try to read it as array of double's.
3. it does not use the FileStorage API. It means that in order to use this storage, you should basically write new code, possibly in parallel with existing serialization code for normal FileStorage.

May I suggest 2 alternative solutions:

1) If compactness is the main goal, you can try compressed FileStorage's, i.e.
<pre>
FileStorage fs("compressed_fs.xml.gz", FileStorage::WRITE);
...
</pre>

it will compress the produced xml file using zlib. You can also compress existing .xml/.yml files and then read them as usual.

2) It would be nice to extend FileStorage to use base64 encoding for all/some of the data. It's not as compact as purely binary representation, but it can encode 32-bit float in ~6 bytes and 64-bit double in ~11 bytes and the encoding/decoding is much faster than to/from textual decimal representation. At the same time, all the tags and other things will stay the same, so that the existing serialization code and the existing FileStorage API may be reused:

<pre>
// the proposal for now ...
FileStorage fs("b64_fs.xml", FileStorage::WRITE + FileStorage::BASE64)
</pre>

**Comment by asolis** [comment]
Hello @vpisarev, 

Thanks for the comments, in fact this is not the latest implementation that I am trying to push in. After some comments from the community I decided to add those features you mention. I reimplemented and refactored the current FileStorage interfaces and added HDF5 data format.  Code available [here](https://github.com/asolis/binaryStorage). 

The new version supports sequences and map using the same interface of FileStorage. Actually as of right now it manage all types that FileStorage does.  Its usage it's exactly the same as the FileStorage/FileNode/FileNodeIterator interfaces. The implementation  also uses HDF5 hyperslabs to buffered  write and read large data.

I started to refactor the classes FileStorage and FileNode / FileNodeIterator so they use 
Writer, Reader Interfaces so we could easy extend to different formats using polymorphism. So we could have multiple hierarchal data formats such as XML{Writer|Reader}, YML{Writer|Reader} H5{Writer|Reader} ..... etc

The usage is just like 
```C++
FileStorage fs(filename, FileStorage::WRITE | FileStorage::FORMAT_H5);

```

My concern and the reason I haven't push the new code in a PR is that I would need to include/link HDF5 to the OpenCV project using the cmake/3rdparty structure(i think?). If I could get some help about it, I could start refactoring the old code with the FileStorage interface and make it extensible while adding Hdf5 storage.... 

The link with the [binaryStorage](https://github.com/asolis/binaryStorage) project I included uses cmake to include hdf5, but I have the feeling that something more elaborated needs in order that include it into OpenCV build pipeline. 

Please let me know what do you think about it and how can I proceed.

**Comment by alalek** [comment]
@asolis I have prepared example of [hdf5 integration](https://github.com/Itseez/opencv/compare/master...alalek:hdf5) (with some "usage example" in the second commit, but it is wrong - I believe we should use FileStorage classes directly).
It should work on Linux with installed hdf5-devel package.
You can start to play with it.

**Comment by asolis** [comment]
@alalek 
Thanks, this is good news, I will have a look at it after work today.

**Pull request closed without merging**
