### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by wizztjh**
to include getting started for beginner.
Correct me if I am wrong

### CODE REVIEW

**Comment by alalek** [comment]
"INSOURCE" builds are not recommended.
"make install" is not recommended. You should use package manager to add and remove(!) software from the system. "make" can work, but it is only for Unix like systems ("cmake --build . --config release" is more universally).

BTW: Some info is located here: http://docs.opencv.org/doc/tutorials/introduction/table_of_content_introduction/table_of_content_introduction.html

**Comment by wizztjh** [comment]
Just updated the Readme to link the user to the tutorial.
User can go to the tutorial via docs link.
But there are chances that they might get lost there and did not go to the introduction tutorial.

**Comment by vpisarev** [comment]
sorry for delay with followup. Could you please use the following link for the master branch:
http://docs.opencv.org/master/df/d65/tutorial_table_of_content_introduction.html

**Comment by vpisarev** [comment]
ok, it's tiny PR with one not quite correct link. It would be easier to recreate it perhaps when needed

**Pull request closed without merging**
