### PR TITLE
Cmake configuration fails with the latest version of gcc (5.1.1).

### PR DESCRIPTION
**Pull request by AVshokurov**
The latest version (5.1.1) of gnu compiler return just its major version ("5") when given the "-dumpversion" argument. GCC compiler developers don't consider this to be an error. A workaround for this case has been made.

### CODE REVIEW

**Comment by AVshokurov** [comment]
https://bugzilla.novell.com/show_bug.cgi?id=941428#c4
@alalek

**Comment by alalek** [comment]
Just update PR source branch. No need to reopen PR.

**Comment by AVshokurov** [comment]
I wanted to squash the last to comments, but github didn't let me. I thought closing the pull request would help. ... but all in vain.

**Comment by alalek** [comment]
Try to push  with "force" flag: `git push -f ...`

**Comment by alalek** [comment]
:+1:

**Comment by AVshokurov** [comment]
thanks! yes, the force option does the trick.

**Pull request merged**
