### PR TITLE
Enabled build with LLVM libc++ for Android

### PR DESCRIPTION
**Pull request by asmorkalov**
Fixed compilation with LLVM libc++ STL on Android

### CODE REVIEW

**Comment by apavlenko** [comment]
`opencv/modules/objdetect/include/opencv2/objdetect/objdetect.hpp` needs to be split into C part in `opencv/modules/objdetect/include/opencv2/objdetect/objdetect_c.h` and C++ part in `opencv/modules/objdetect/include/opencv2/objdetect/objdetect.hpp`, then C samples should include `opencv2/objdetect/objdetect_c.h` instead of `.hpp` !

**Comment by apavlenko** [comment]
@asmorkalov , are you going to split headers?
or should this PR be closed?

**Comment by asmorkalov** [comment]
@apavlenko addressed.

**Comment by apavlenko** [comment]
:+1:

**Pull request merged**
