### PR TITLE
fixed dynamic memory overrun in UMat download/upload methods for non contiguous umat

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
fixes for non contiguous UMat download/upload

### CODE REVIEW

**Comment by alalek** [comment]
What case is fixed here?

**Comment by vladimir-dudnik** [comment]
this fixes the memory overrun issue detected in tests UMat/UMatBasicTests.copyTo, the specific case when
    if(useRoi)
    {
        UMat roi_ua;
        Mat roi_a;
        roi_ua = UMat(ua, roi);
        roi_a = Mat(a, roi);
        roi_ua.copyTo(roi_a); - there, at OpenCLAllocator.download memory overrun happens when AlignedDataPtr is destructed and back copy from temporary aligned memory buffer to matrix memory is hapens. The root cause is that AlignedDataPtr keeps contiguous memory buffer and if it try to copy to non contiguous memory in matrix it uses wrong size for copied amount of data.
The issue is detected and reported by debug CRT in visual studio at debug build.

**Comment by alalek** [comment]
Will you enable `copyTo()` test in test_umat.cpp?

**Comment by alalek** [comment]
:+1:

**Pull request merged**
