### PR TITLE
Fix compat with Mingw-w64

### PR DESCRIPTION
**Pull request by fspindle**
I propose the following changes that I have to apply in order to be able to use OpenCV with Mingw-w64 as a 3rd party. I also notice other issues that can be found following http://www.irisa.fr/lagadic/visp/documentation/visp-2.10.0/tutorial-install-win81-mingw64.html#issue_win81_mingw. The work arround consist in turning tiff, dshow and ipp support OFF during CMake configuration.

Fabien

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/2411/steps/whitespace/logs/stdio

**Comment by fspindle** [comment]
I have removed the trailing whitespace

**Comment by SpecLad** [comment]
Can you tell me more about why the endianness test doesn't work with MinGW? Have you tried to debug the problem?

**Comment by fspindle** [comment]
I get the issue http://www.irisa.fr/lagadic/visp/documentation/visp-2.10.0/tutorial-install-win81-mingw64.html#issue_win81_mingw_opencv_endianness

I don't try to debug.

**Comment by ilya-lavrenov** [comment]
@SpecLad, are you satisfied by the answer?

**Comment by SpecLad** [comment]
Well... not entirely. I'd still like to know why the test doesn't work with MinGW. I was going to investigate in my copious free time, although if anyone knows already, then do tell.

**Comment by SpecLad** [comment]
OK, so I _did_ investigate, and... it worked. At least, the test worked, I haven't actually tried to build OpenCV afterwards.

So I need more details. What CMake version are you using? What version of GCC?

**Comment by fspindle** [comment]
g++ 4.8.3
cmake 3.1.0

**Comment by ilya-lavrenov** [comment]
@SpecLad, do you need any additional information or you can approve this MR?

**Comment by ilya-lavrenov** [comment]
@fspindle, please, resolve merge conflicts.

**Comment by SpecLad** [comment]
Oh yeah, thanks for reminding me. I actually tested the versions you posted, @fspindle, and it worked fine for me. So I can only conclude that the problem is in something other than the build script. Indeed, the errors shown in that screenshot seem to indicate some form of configuration problem. If you find out the cause of the problem and it turns out to be insoluble without disabling the check, then please post an explanation.

As for your other change, that has already been independently integrated in #3889. Tell me if the current version doesn't work for you.

Closing for now; reopen if you have any new information.

**Pull request closed without merging**
