### PR TITLE
opencv_cuda : sort unclassified routines from the module and remove it

### PR DESCRIPTION
**Pull request by jet47**

### CODE REVIEW

**Comment by jet47** [comment]
Sanity : https://github.com/Itseez/opencv_extra/pull/243

**Comment by ilya-lavrenov** [comment]
@jet47, please, fix warnings http://pullrequest.opencv.org/buildbot/builders/precommit_android/builds/2237/steps/compile%20release/logs/warnings%20%282%29

**Comment by jet47** [comment]
Fixed.

**Comment by ilya-lavrenov** [comment]
:+1:

**Pull request merged**
