### PR TITLE
Fix for a potential data race condition

### PR DESCRIPTION
**Pull request by rajithr**
Fix for a potential data race condition, reported in Coverity Scan

### CODE REVIEW

**Comment by vpisarev** [comment]
@LeonidBeynenson, could you please review this tiny patch?

**Comment by LeonidBeynenson** [comment]
Hi @rajithr and @vpisarev 

As far as I remember, I have not added these locks in this place of the code to avoid deadlocks in the case if an exception happens inside a locked part of the code (it happened couple of times when I debugged this class, debugging of deadlock was unpleasant).

I think that this change may be accepted now, although I'd prefer to make a bit more changes in the code and also move lines 448..459 to the function cv::workcycleObjectDetectorFunction (it will make the class even more stable, since finalization part will be  in one clause lock..unlock).

**Comment by rajithr** [comment]
@LeonidBeynenson, Can do that. Need raise a new PR for that?

**Comment by vpisarev** [comment]
@rajithr, nope, just make another commit to the same branch

**Comment by rajithr** [comment]
@LeonidBeynenson, I have updated with the code changes based on your comments, please have a look

**Comment by LeonidBeynenson** [comment]
Ok, looks good!

:+1:

**Pull request merged**
