### PR TITLE
Doc videoio enums

### PR DESCRIPTION
**Pull request by PkLab**
resolves: Documenting the `CAP_*` enums in `videoio.hpp`

### What does this PR change?
 - Current code comments for `CAP_*` enums have been converted in valid doxygen inline doc.
 - References to enums in VideoCapture and VideoWriter methods have been replaced by `copydoc` or auto linked (thanks to the fullname)
 - no changes in code (really `CAP_FIREWIRE` and `CAP_FIREWARE` have been switched in the list)

### CODE REVIEW

**Comment by PkLab** [comment]
May be @StevenPuttemans  or @alalek might help me to solve this PR because I'm not sure I'm on the right way.

Point is that this PR was being in conflict  with #6619 that has been merged later. So I've merged  Itseez:master into PR:branch than solved the conflict with `videoio.hpp`.

In addiction 1 error checked but it seems not related to current changes... (test_hal_core.cpp)

any suggestions ?

**Comment by alalek** [comment]
This is sporadic failure. Build has been restarted.

**Comment by alalek** [comment]
Well done! Looks good to me.

**Comment by mshabunin** [comment]
I suggest naming all enumerations to make it possible to refer them from corresponding function documentation. See [documentation for cv::imread](http://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56) for example.

**Comment by PkLab** [comment]
@mshabunin I've this in my plan but I choose to make an atomic/simple PR as my 1st. If you want I can do this within this PR

**Comment by mshabunin** [comment]
@PkLab , ok then, lets merge this PR first.

**Comment by PkLab** [comment]
@mshabunin  Just opened a new issue #6746  about naming all enumerations

**Comment by apavlenko** [comment]
:+1:

**Pull request merged**
