### PR TITLE
add visualisation tool for 2.4 branch

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Backport of https://github.com/Itseez/opencv/pull/6354

### CODE REVIEW

**Comment by alalek** [comment]
Looks good to me! :+1:

**Comment by StevenPuttemans** [comment]
Thanks! Nice to see it moving!

**Comment by teng88** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
@alalek I do suggest that the master version is merged seperately and not through a 2.4 --> master port, because there are quite the differences between both.

Thanks again!

**Pull request merged**
