### PR TITLE
swap broken video with fixed video

### PR DESCRIPTION
**Pull request by StevenPuttemans**
resolves issue https://github.com/Itseez/opencv/issues/6429

### What does this PR change?
Add fixed video tree.avi supplied by @garybradski

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@alalek could you check this?

**Comment by StevenPuttemans** [comment]
Backport: https://github.com/Itseez/opencv/pull/6431

**Comment by StevenPuttemans** [comment]
Guessing the reported OpenCL problem has nothing to do with this PR.

**Comment by alalek** [comment]
@StevenPuttemans Lets put fix into 2.4 at first and then I will propagate this change into master via "merge 2.4" process (to reduce size of patches).

**Comment by StevenPuttemans** [comment]
:+1: if that works better for you then sure, go ahead!

**Pull request closed without merging**
