### PR TITLE
Fix MinGW detection on x86

### PR DESCRIPTION
**Pull request by nitsch**
MinGW-w64 always uses "w64" as vendor key which the previously
used check for "64" anywhere in the target triplet matched. This
would lead to MinGW-w64 setups always being treated as x64.

Since we are actually interested in finding the "64" in the
triplet's operating system key, this fix makes sure to look for
"mingw64" and thus avoids the false match.

Fixes issue #3835. Credits to Lode Leroy for the original patch.

### CODE REVIEW

**Comment by mshabunin** [comment]
1. Isn't it `x86_64-w64-mingw32` on 64-bit and something like `i686-w64-mingw32` on 32-bit?
2. There is similar block several lines before, can it be reused?
```{.cmake}
if(CMAKE_OPENCV_GCC_TARGET_MACHINE MATCHES "amd64|x86_64|AMD64")
  set(MINGW64 1)
endif()
```
3. There is `if` statement at line 102 which will set `x86_64` flag if `MINGW64` is `True`. Can it be related with the problem?
4. Can you please provide the platform and cmake parameters you are using for build?

**Comment by SpecLad** [comment]
> There is similar block several lines before, can it be reused?

That one sets `MINGW64`, but not `OpenCV_ARCH`. I think what actually needs to be done here is that the whole bit after `set(OpenCV_RUNTIME mingw)` needs to be replaced with:

```
if(MINGW64)
    set(OpenCV_ARCH x64)
else()
    set(OpenCV_ARCH x86)
endif()
```

**Comment by nitsch** [comment]
> Isn't it x86_64-w64-mingw32 on 64-bit and something like i686-w64-mingw32 on 32-bit?

You are right, there is never mingw64 in that triplet, only mingw32. I must have mixed that up somewhere in my testing yesterday. %-)

And I believe @SpecLad is right. The detection of MinGW and x64 vs x86 was already done when we reach the point where `OpenCV_ARCH` should be set. The detection itself looks alright and does also yield the correct results, so we should trust it.

**Comment by SpecLad** [comment]
:+1:

**Pull request merged**
