### PR TITLE
GraphCut deprecated in CUDA 7.5 and removed in 8.0

### PR DESCRIPTION
**Pull request by jet47**
### What does this PR change?
Fixes compilation with CUDA 8.0.

### CODE REVIEW

**Comment by jet47** [comment]
@ilya-lavrenov Please review the request.

**Comment by ilya-lavrenov** [comment]
:+1:

**Comment by asmorkalov** [comment]
:+1:

**Comment by ohnozzy** [comment]
Just curious, how do you get Cuda 8.0? 
Does it support VS2015?

**Comment by guruvishnuvardan** [comment]
Hi Folks,
I tried to change the code of graphcuts.cpp to the following, but its readonly

+#if !defined (HAVE_CUDA) || defined (CUDA_DISABLER) || (CUDART_VERSION >= 8000)

**Comment by MohamedEhabHafez** [comment]
I am new with opencv and cuda. I faced the same problem
[  7%] Built target opencv_core
make: *** [all] Error 2
I saw you were talking about the solution but I did not get it. It will be much appreciated if anyone can explain simply what should I do??

**Comment by k89231** [comment]
@MohamedEhabHafez plz look at the [files changed]

**Pull request merged**
