### PR TITLE
Fix small error in traincascade application

### PR DESCRIPTION
**Pull request by vbystricky**
Small fix in boost codes in traincascade application

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@vbystricky can you explain what is the result of this error in previous trained models? Quite interested since I am using this software on a daily base!

**Comment by vbystricky** [comment]
@StevenPuttemans 
If `is_buf_16u == true` we fill `udst` array, but we tried to sort `idst` in the code before changing.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by vpisarev** [comment]
oops. how did it work then? :O  :+1:

**Comment by StevenPuttemans** [comment]
Well that was what I was wondering too. This seems quite crutial...


Verzonden vanaf Samsung Mobile.


-------- Oorspronkelijk bericht --------
Van: Vadim Pisarevsky
Datum:05-02-2015 08:47 (GMT+01:00)
Aan: Itseez/opencv
Cc: Steven Puttemans
Onderwerp: Re: [opencv] Fix small error in traincascade application (#3669)


oops. how did it work then? :O [:+1:]

**Pull request merged**
