### PR TITLE
Fixed wrong-name-for-changelog-of-native-package warning for deb packages

### PR DESCRIPTION
**Pull request by asmorkalov**

### CODE REVIEW

**Comment by asmorkalov** [comment]
@ilya-lavrenov please look at it.

**Comment by alalek** [comment]
Changelog has been moved here: https://github.com/Itseez/opencv/wiki/ChangeLog

**Comment by asmorkalov** [comment]
Fixed!

**Comment by ilya-lavrenov** [comment]
:+1:

**Pull request merged**
