### PR TITLE
Fix missing self-assignment check in Size_

### PR DESCRIPTION
**Pull request by NewProggie**

### CODE REVIEW

**Comment by alalek** [comment]
What is a real problem?

If there is no real problem so I suggest to close this, because unnecessary branch has significant performance impact.

**Comment by NewProggie** [comment]
Ok, so am I supposed to open a pull request directly to master for this?

**Comment by alalek** [comment]
Just describe here the problem that you are trying to solve by this patch.

**Comment by NewProggie** [comment]
Never mind. I've just checked again and saw that self-assignment checks only make sense in case of manual memory management, which the Size_ class is not doing. You were right concerning the performance impact.

**Pull request closed without merging**
