### PR TITLE
enable VideoWriter class for java

### PR DESCRIPTION
**Pull request by berak**
fixing fourcc
small test case: https://gist.github.com/berak/28ba78093943d3120dd4

hmm,    https://github.com/Itseez/opencv/pull/4006

i guess, this won't get merged into trunk (due to the android issue), 
still, please let me run this through the buildbot once, so we know we got a valid patch to send
folks from answers.opencv.org to. (this is asked soo often from desktop java users..)

### CODE REVIEW

**Comment by vpisarev** [comment]
@mshabunin, should it be merged in?

**Comment by berak** [comment]
i originally thought @sgjava's commit was reverted because of the finalizer issues, 
only saw @apavlenko 's objection in #4006 after submitting.

well, if some innocent soul tries it on android, and it crashes without further explanation, - maybe we should not merge it now. 

are there plans to add the new standalone mjpg encoder to android ? folks there would definitely like to save a video file now and then... (and this would at least partly solve the 'missing backend' problem there)

again, imho, there's no hurry, as long as there's a simple patch for those desktop java users, who urgently need it.

**Comment by sgjava** [comment]
This was reverted, but I use patching to fix the memory leaks. See https://github.com/sgjava/opencvmem

**Comment by berak** [comment]
ah, sorry, @sgjava,  probably should not have pinged you.

this is all about the VideoWriter, not about any memory issues.

**Comment by sgjava** [comment]
My scripts also generate VideoWriter for Java, but I believe they were saying this crashes on Android. I'm using the "Desktop" version of OpenCV. I'm still run this on Android sticks, but they are running Ubuntu :)

**Comment by berak** [comment]
@sgjava : maybe we can activate you for  http://answers.opencv.org/questions/scope:all/sort:activity-desc/page:1/query:java%20netbeans/ ? :)

(you seem to have all the answers lacking there ;)

**Comment by sgjava** [comment]
Well, if I had unlimited time I'd be happy to. Most of the questions revolve around Windows/NetBeans. I'm primary developing on Ubuntu and targeting Mini PCs like ODROID C1. See https://github.com/sgjava/ubuntu-mini.

**Comment by apavlenko** [comment]
@berak , @sgjava , I don't mind enabling `VideoWriter` in Java - let's just handle it correctly on Android!

**Comment by mshabunin** [comment]
Thank you!
I've checked VideoWriter on Android (armeabi-v7a with NEON) and desktop java and it works fine with new MotionJPG codec.
:+1:

**Comment by sgjava** [comment]
Now we just need to work on const_ignore_list in order to enable required constants. My install script comments out CV_CAP_PROP_FPS, CV_CAP_PROP_FOURCC and CV_CAP_PROP_FRAME_COUNT which work as expected. I haven't tested others yet.

**Comment by PhilLab** [comment]
:+1: for the Android+MJPEG!

**Comment by damanzano** [comment]
Hi excuse me if this is not the place to post this issue, I have jus clone the repository and built the it on Mac os Yosemite and the VideoWriter class still does not appear in the java jar. I followed the instructions on this page http://blogs.wcode.org/2014/10/howto-install-build-and-use-opencv-macosx-10-10/ to install opencv on my device. I appreciated any help with this.

**Comment by apavlenko** [comment]
@damanzano , to get these changes you need to compile opencv master instead of using a public package - they have not been released yet.

**Comment by sgjava** [comment]
For 3.0.0 release and earlier you can comment out VideoWriter in modules/java/generator/gen_java.py prior to compiling. Master already has this change as apavlenko pointed out.

**Pull request merged**
