### PR TITLE
HAL reorganization

### PR DESCRIPTION
**Pull request by mshabunin**
- moved HAL back to core module
- added another HAL implementation example (in `samples/hal`)
- ability to provide HAL replacement headers and libraries as lists (`;`-separated) to cmake
- _split_ and _merge_ replacement entry point

__Locations:__
- functions implemented in HAL: `<core-include>/hal/hal.hpp`
- public interface to be used by external implemetations: `<core-include>/hal/interface.h`
- HAL dummy replacement functions and macros: `<core-src>/hal_replacement.hpp`
- HAL samples: `samples/hal`

check_regression=*

### CODE REVIEW

**Comment by vpisarev** [comment]
@mshabunin, even though it's *WIP* still, I dare to make some comments. Overall, it looks great. I do not quite like the name "broken" in the HAL sample. I would probably rename it to ext_hal, rename functions, and put comments to some of the functions like
<pre>
return CV_HAL_ERROR_UNKNOWN; // test how OpenCV handles various error codes returned by HAL functions
</pre>
(of course, there can be different error codes like NOT_IMPLEMENTED, NULLPTR etc.)

This is because "broken" name is quite confusing and people may think that this sample is not usable and they should not look at it.

**Comment by mshabunin** [comment]
@vpisarev , I've renamed hal samples and added readme file with the basic instructions.

**Comment by vpisarev** [comment]
thank you! :+1:

**Comment by mshabunin** [comment]
Should be merged with Itseez/opencv_contrib#475

**Pull request merged**
