### PR TITLE
Fixed compilation of examples

### PR DESCRIPTION
**Pull request by sansuiso**

### CODE REVIEW

**Comment by sansuiso** [comment]
Fixed error message: `error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >` with clang on macosx

**Comment by Dikay900** [comment]
unfortunately this causes build errors on all buildbots please see the errors and try to fix them: http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/3388/steps/compile%20release/logs/stdio

**Comment by alalek** [comment]
Is it possible to use `cv::format` here instead of this code?

**Comment by vpisarev** [comment]
ok, looks like this is abandoned patch

**Pull request closed without merging**
