### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mzajko**
Dear OpenCV team,

I would like to propose an update of the XIMEA
camera adapter that includes these updates:

- replaced m3api/m3apiX64 binaries with latest xiapi32/xiapi64 to support latest camera models
- added new parameter definitions to videoio_c.h and SetProperty/GetProperty calls
- added acquisition resetting for specific parmateters in SetProperty call
- added new error return value evaluators

Please let me know whether this information is
sufficient as I am not a frequent user of GitHub.
Thank you.

Best regards,
Marian Zajko

### CODE REVIEW

**Comment by mzajko** [comment]
Hi All,

from the pull request 5628 buildbot report it seems that none has passed. Could you please advise
what can be done as the reported errors do not seem to be related to the camera adapter code that 
was updated. Looking forward to your response.

Regards,
Marian

**Comment by alalek** [comment]
Please remove unrelated commits from the patch and fix whitespace problems reported by buildbot.

**Comment by mzajko** [comment]
Hi, sorry for bothering you, I removed the previous changes, but the build is failing now on all
instances. I am not sure which whitespaces to remove, as I did not find any rules that I could follow. Please advise.

**Comment by alalek** [comment]
Reverting commits is not the same as removing commits.
Try something like this and leave only "XIMEA adapter update" commit during "rebase" step:

1) https://help.github.com/articles/configuring-a-remote-for-a-fork/
2)
```
git fetch upstream
git rebase -i upstream master
git push -f origin master
```

**Comment by mzajko** [comment]
Thanks, I was not able to do the proposed operations. So I checked commit b5fd7868a861600f16e8b1c04ef0ea8d84dd8834 and created a branch with a respective name.
In this branch I commited the udpated files and issued a new pull request:
https://github.com/mzajko/opencv/pull/1
So what did I do wrong now? Sorry, I new to github...

**Comment by alalek** [comment]
You made PR into your fork, you need to make PR into Itseez/opencv (instead of this PR)

**Comment by mzajko** [comment]
Closing this PR, managed to do it properly here https://github.com/Itseez/opencv/pull/5635.

**Pull request closed without merging**
