### PR TITLE
VS2015/Windows 10 and Universal Windows App support

### PR DESCRIPTION
**Pull request by GregoryMorse**
Almost exclusively needed to update the task library to compile under the new library situation

### CODE REVIEW

**Comment by alalek** [comment]
Could you please specify license in new files.

**Comment by vpisarev** [comment]
thanks! :+1:

**Comment by GregoryMorse** [comment]
The ppltasks_winrt and agile_wrl are adapted from Microsoft's code.  These are necessary to use native c++ without the CX extension.  I will check and perhaps Microsoft would give us permission given they are a contributor.  We may be okay with BSD but I'm unsure.  I will research this.

**Comment by GregoryMorse** [comment]
VCLibDiffMerge project in process - already takes care of all version of agile.h, ppltasks.h will take a while - kindly a few days and we will remove all the Microsoft library code and generation the needed files.

**Pull request merged**
