### PR TITLE
Revert of "Merge pull request #4014" and "Merge pull request #4006"

### PR DESCRIPTION
**Pull request by apavlenko**
reverted from commit 52fa55a770cb07a6401aa6617b81f413d1165771 and commit 4743184

### CODE REVIEW

**Comment by sgjava** [comment]
The reverts screwed up gen_java.py in master, so now it only generates delete() without finalize().

**Comment by apavlenko** [comment]
Thanks for pointing to this: the #4006 also needs to be reverted since it removes `finalize()`.

**Comment by sgjava** [comment]
https://github.com/Itseez/opencv/pull/4035 will put everything I changed back to its previous state.

**Comment by vpisarev** [comment]
:+1:

**Comment by sgjava** [comment]
I've created documentation describing the memory issues with the Java
bindings https://github.com/sgjava/opencvmem

On Thu, May 21, 2015 at 8:32 AM, OpenCV Pushbot <notifications@github.com>
wrote:

> Merged #4031 <https://github.com/Itseez/opencv/pull/4031>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itseez/opencv/pull/4031#event-310569428>.
>



-- 
Steven P. Goldsmith

**Pull request merged**
