### PR TITLE
fixed memory leak in ANN

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Comment by jet47** [comment]
:+1:

**Comment by berak** [comment]
i do not think, this needs a backport into master, since the [3.0 code](https://github.com/Itseez/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L1251) is using `vector<int>` already for the layer sizes.

**Comment by ilya-lavrenov** [comment]
It's even better :smile:

**Comment by Dikay900** [comment]
as already stated this patch is not needed in master using vector<int>, getting freed upon leaving function "read".

Or did i understand something wrong @ilya-lavrenov ?

**Pull request merged**
